ALTER TABLE pdp_piecerefs ADD COLUMN IF NOT EXISTS caching_task_started TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE pdp_piecerefs ADD COLUMN IF NOT EXISTS caching_task_completed TIMESTAMP WITH TIME ZONE DEFAULT NULL;
