#!/usr/bin/env bash
set -e

# Curio devnet entrypoint.
#
# Startup phases:
# 1. Wait until Lotus is online and chain head passes bootstrap threshold.
# 2. On first run only:
#    - wait for lotus-miner bootstrap to finish
#    - create miner actor and Curio cluster config
#    - attach local storage
#    - import/register PDP key in Curio (FSRegister)
#    - start a couple of CC sectors for initial chain activity
# 3. Start Curio in steady-state mode.
# 4. In parallel, complete provider-side contract bootstrap:
#    - resolve provider id in service registry
#    - approve provider in FWSS state view
#    - add endorsement
#    - fund provider with USDFC
# 5. Fail fast if provider bootstrap does not converge.

# Service endpoints and bootstrap metadata.
myip=`nslookup curio | grep -v "#" | grep Address | awk '{print $2}'`
CURIO_WEBRPC_URL="${CURIO_WEBRPC_URL:-http://${myip}:4701/api/webrpc/v0}"
LOTUS_RPC_URL="${LOTUS_RPC_URL:-http://lotus:1234/rpc/v1}"
PDP_SERVICE_NAME="${PDP_SERVICE_NAME:-curio}"
PDP_SERVICE_DESCRIPTION="${PDP_SERVICE_DESCRIPTION:-curio-devnet}"
PDP_SERVICE_LOCATION="${PDP_SERVICE_LOCATION:-C=US}"
PDP_WALLET_FUND_AMOUNT="${PDP_WALLET_FUND_AMOUNT:-1000}"

# Contract artifacts shared from contracts-bootstrap.
CONTRACT_ADDRESSES_FILE="${CONTRACT_ADDRESSES_FILE:-/var/lib/contracts/contract_addresses.json}"
DEPLOYER_PRIVATE_KEY_FILE="${DEPLOYER_PRIVATE_KEY_FILE:-/var/lib/contracts/deployer.private-key}"

# Provider bootstrap worker state.
PROVIDER_READY_FILE="${PROVIDER_READY_FILE:-/var/lib/contracts/provider.ready}"
PROVIDER_LOCK_FILE="${PROVIDER_LOCK_FILE:-/var/lib/contracts/provider.bootstrap.lock}"
DEPLOYER_TX_LOCK_FILE="${DEPLOYER_TX_LOCK_FILE:-/var/lib/contracts/deployer.tx.lock}"
PDP_USDFC_FUND_AMOUNT_WEI="${PDP_USDFC_FUND_AMOUNT_WEI:-200000000000000000000000}"
PROVIDER_BOOTSTRAP_RETRY_INTERVAL_SEC="${PROVIDER_BOOTSTRAP_RETRY_INTERVAL_SEC:-5}"
PROVIDER_BOOTSTRAP_MAX_RETRIES="${PROVIDER_BOOTSTRAP_MAX_RETRIES:-120}"

# Curio keeps its own state under CURIO_REPO_PATH; default markers are remapped there.
if [[ "$PROVIDER_READY_FILE" == "/var/lib/contracts/provider.ready" ]]; then
  PROVIDER_READY_FILE="${CURIO_REPO_PATH}/provider.ready"
fi
if [[ "$PROVIDER_LOCK_FILE" == "/var/lib/contracts/provider.bootstrap.lock" ]]; then
  PROVIDER_LOCK_FILE="${CURIO_REPO_PATH}/provider.bootstrap.lock"
fi

provider_log() {
  echo "[provider-bootstrap] $*"
}

provider_fail() {
  echo "[provider-bootstrap][error] $*" >&2
  return 1
}

# Call Curio WebRPC methods used for PDP bootstrap (ImportPDPKey, FSRegister).
jsonrpc_call() {
  local method="$1"
  local params_json="$2"
  local payload response

  payload="$(jq -cn --arg method "CurioWeb.${method}" --argjson params "$params_json" '{jsonrpc:"2.0", id:1, method:$method, params:$params}')"
  response="$(curl -sS -X POST "$CURIO_WEBRPC_URL" -H 'Content-Type: application/json' --data "$payload")"

  if [[ -z "$response" ]]; then
    echo "Empty JSON-RPC response for ${method}" >&2
    return 1
  fi

  if echo "$response" | jq -e '.error != null' >/dev/null; then
    echo "JSON-RPC ${method} failed: $(echo "$response" | jq -c '.error')" >&2
    return 1
  fi
}

# Wait until the delegated Filecoin address resolves to a chain actor.
wait_for_delegated_actor() {
  local delegated_addr="$1"
  local retries=0

  until lotus state get-actor "$delegated_addr" >/dev/null 2>&1; do
    retries=$((retries + 1))
    if [[ "$retries" -gt 180 ]]; then
      echo "Delegated actor not found after 180s: ${delegated_addr}" >&2
      return 1
    fi
    sleep 1
  done
}

# Wait for env file generated by contracts-bootstrap and source it in this shell.
wait_and_source_contract_env() {
  if [[ -z "${CONTRACT_ENV_FILE:-}" ]]; then
    return 0
  fi

  echo "Waiting for contract env file at $CONTRACT_ENV_FILE ..."
  local retries=0
  while [[ ! -f "$CONTRACT_ENV_FILE" ]]; do
    retries=$((retries + 1))
    if [[ $retries -gt 120 ]]; then
      echo "Contract env file not found after 120s: $CONTRACT_ENV_FILE"
      return 1
    fi
    sleep 1
  done

  # shellcheck disable=SC1090
  source "$CONTRACT_ENV_FILE"
  echo "Loaded contract env file: $CONTRACT_ENV_FILE"
}

# Wait for all contract bootstrap artifacts required for EVM calls and signing.
wait_for_contract_artifacts() {
  local tries=0
  while [[ ! -f "$CONTRACT_ENV_FILE" || ! -f "$CONTRACT_ADDRESSES_FILE" || ! -f "$DEPLOYER_PRIVATE_KEY_FILE" ]]; do
    tries=$((tries + 1))
    if [[ "$tries" -gt 300 ]]; then
      echo "Contract artifacts not found in time: $CONTRACT_ENV_FILE / $CONTRACT_ADDRESSES_FILE / $DEPLOYER_PRIVATE_KEY_FILE" >&2
      return 1
    fi
    sleep 1
  done
}

# Normalize cast output to unsigned decimal (accept hex or decimal).
to_decimal() {
  local raw
  raw="$(echo "${1:-0}" | tr -d '\r\n' | awk '{print $1}')"
  if [[ -z "$raw" ]]; then
    echo "0"
    return 0
  fi
  if [[ "$raw" =~ ^0x[0-9a-fA-F]+$ ]]; then
    cast to-dec "$raw" | tr -d '\r\n[:space:]'
    return $?
  fi
  if [[ "$raw" =~ ^[0-9]+$ ]]; then
    echo "$raw"
    return 0
  fi
  return 1
}

# Serialize deployer-key transactions across containers to avoid nonce races.
with_deployer_tx_lock() {
  local lock_dir
  lock_dir="$(dirname "$DEPLOYER_TX_LOCK_FILE")"
  mkdir -p "$lock_dir" 2>/dev/null || {
    echo "[provider-bootstrap][error] unable to create deployer tx lock dir: $lock_dir" >&2
    return 1
  }
  touch "$DEPLOYER_TX_LOCK_FILE" 2>/dev/null || {
    echo "[provider-bootstrap][error] unable to write deployer tx lock file: $DEPLOYER_TX_LOCK_FILE" >&2
    return 1
  }
  if command -v flock >/dev/null 2>&1; then
    (
      flock 8
      "$@"
    ) 8>"$DEPLOYER_TX_LOCK_FILE"
  else
    "$@"
  fi
}

# Execute one provider bootstrap attempt.
# This function is idempotent: if state already exists on-chain, it only validates.
bootstrap_provider_once() {
  provider_log "Starting attempt: loading contract artifacts and provider state"
  wait_for_contract_artifacts || return 1
  wait_and_source_contract_env || return 1

  local deployer_private_key
  local service_registry_address
  local fwss_address
  local fwss_view_address
  local endorsements_address
  local usdfc_address
  local provider_native_address
  local provider_private_key_hex
  local provider_eth_address
  local provider_id_raw
  local provider_id
  local approved_raw
  local endorsed_raw
  local provider_balance_raw
  local provider_balance_dec

  # Read deployer key used to submit admin EVM transactions.
  deployer_private_key="$(tr -d '\r\n[:space:]' < "$DEPLOYER_PRIVATE_KEY_FILE")"
  [[ "$deployer_private_key" =~ ^0x[0-9a-fA-F]{64}$ ]] || {
    echo "Invalid deployer private key in $DEPLOYER_PRIVATE_KEY_FILE" >&2
    return 1
  }

  # Resolve contract addresses from JSON first, then env fallbacks.
  service_registry_address="$(jq -r '.contracts.service_provider_registry_proxy // .contracts.service_provider_registry // empty' "$CONTRACT_ADDRESSES_FILE")"
  fwss_address="$(jq -r '.contracts.filecoin_warm_storage_service_proxy // .contracts.filecoin_warm_storage_service // empty' "$CONTRACT_ADDRESSES_FILE")"
  fwss_view_address="$(jq -r '.contracts.filecoin_warm_storage_service_state_view // empty' "$CONTRACT_ADDRESSES_FILE")"
  endorsements_address="$(jq -r '.contracts.endorsements // empty' "$CONTRACT_ADDRESSES_FILE")"
  usdfc_address="$(jq -r '.contracts.usdfc // empty' "$CONTRACT_ADDRESSES_FILE")"

  [[ "$service_registry_address" =~ ^0x[0-9a-fA-F]{40}$ ]] || service_registry_address="${CURIO_DEVNET_SERVICE_REGISTRY_ADDRESS:-}"
  [[ "$fwss_address" =~ ^0x[0-9a-fA-F]{40}$ ]] || fwss_address="${CURIO_DEVNET_FWSS_ADDRESS:-}"
  [[ "$fwss_view_address" =~ ^0x[0-9a-fA-F]{40}$ ]] || fwss_view_address="${CURIO_DEVNET_FWSS_STATE_VIEW_ADDRESS:-}"
  [[ "$endorsements_address" =~ ^0x[0-9a-fA-F]{40}$ ]] || endorsements_address="${CURIO_DEVNET_ENDORSEMENTS_ADDRESS:-}"
  [[ "$usdfc_address" =~ ^0x[0-9a-fA-F]{40}$ ]] || usdfc_address="${CURIO_DEVNET_USDFC_ADDRESS:-}"

  [[ "$service_registry_address" =~ ^0x[0-9a-fA-F]{40}$ ]] || { provider_fail "invalid service registry address"; return 1; }
  [[ "$fwss_address" =~ ^0x[0-9a-fA-F]{40}$ ]] || { provider_fail "invalid FWSS proxy address"; return 1; }
  [[ "$fwss_view_address" =~ ^0x[0-9a-fA-F]{40}$ ]] || { provider_fail "invalid FWSS view address"; return 1; }
  [[ "$endorsements_address" =~ ^0x[0-9a-fA-F]{40}$ ]] || { provider_fail "invalid endorsements address"; return 1; }
  [[ "$usdfc_address" =~ ^0x[0-9a-fA-F]{40}$ ]] || { provider_fail "invalid USDFC address"; return 1; }

  # PDP wallet is produced by bootstrap_pdp_registry on first Curio init.
  [[ -f "$CURIO_REPO_PATH/pdp_wallet.addr" ]] || { provider_fail "missing PDP wallet marker: $CURIO_REPO_PATH/pdp_wallet.addr"; return 1; }
  provider_native_address="$(tr -d '\r\n[:space:]' < "$CURIO_REPO_PATH/pdp_wallet.addr")"
  provider_log "Using provider native address: $provider_native_address"
  wait_for_delegated_actor "$provider_native_address" || return 1

  # Derive provider EVM address from the delegated Lotus wallet key.
  provider_private_key_hex="$(lotus wallet export "$provider_native_address" | xxd -r -p | jq -r '.PrivateKey' | base64 -d | xxd -p -c 256 | tr -d '\r\n[:space:]')"
  [[ "$provider_private_key_hex" =~ ^[0-9a-fA-F]{64}$ ]] || { provider_fail "invalid provider private key material from lotus wallet export"; return 1; }
  provider_eth_address="$(cast wallet address --private-key "0x${provider_private_key_hex}" | tr -d '\r\n[:space:]')"
  [[ "$provider_eth_address" =~ ^0x[0-9a-fA-F]{40}$ ]] || { provider_fail "invalid provider EVM address derived from private key"; return 1; }
  provider_log "Resolved provider EVM address: $provider_eth_address"

  # Service provider id must exist before approvals/endorsements can succeed.
  provider_id_raw="$(cast call "$service_registry_address" "getProviderIdByAddress(address)(uint256)" "$provider_eth_address" --rpc-url "$LOTUS_RPC_URL" | tr -d '\r\n' || true)"
  provider_id="$(to_decimal "$provider_id_raw" || true)"
  [[ "$provider_id" =~ ^[0-9]+$ ]] || { provider_fail "invalid provider id response from service registry: ${provider_id_raw:-<empty>}"; return 1; }
  [[ "$provider_id" != "0" ]] || { provider_fail "provider id not assigned yet for provider address $provider_eth_address"; return 1; }
  provider_log "Resolved provider id: $provider_id"

  # Ensure provider is approved in FWSS.
  approved_raw="$(cast call "$fwss_view_address" "isProviderApproved(uint256)(bool)" "$provider_id" --rpc-url "$LOTUS_RPC_URL" | tr -d '\r\n[:space:]' || true)"
  if [[ "$approved_raw" != "true" ]]; then
    provider_log "Provider not approved; sending addApprovedProvider for provider id $provider_id"
    with_deployer_tx_lock cast send "$fwss_address" "addApprovedProvider(uint256)" "$provider_id" \
      --rpc-url "$LOTUS_RPC_URL" \
      --private-key "$deployer_private_key" \
      --gas-limit 10000000000 >/dev/null || return 1
    approved_raw="$(cast call "$fwss_view_address" "isProviderApproved(uint256)(bool)" "$provider_id" --rpc-url "$LOTUS_RPC_URL" | tr -d '\r\n[:space:]' || true)"
    [[ "$approved_raw" == "true" ]] || { provider_fail "provider approval failed for provider id $provider_id"; return 1; }
  fi
  touch "$CURIO_REPO_PATH/.init.pdp.approved"
  provider_log "Provider approval confirmed"

  # Ensure provider id is present in endorsements set.
  endorsed_raw="$(cast call "$endorsements_address" "containsProviderId(uint256)(bool)" "$provider_id" --rpc-url "$LOTUS_RPC_URL" | tr -d '\r\n[:space:]' || true)"
  if [[ "$endorsed_raw" != "true" ]]; then
    provider_log "Provider not endorsed; sending addProviderId for provider id $provider_id"
    with_deployer_tx_lock cast send "$endorsements_address" "addProviderId(uint256)" "$provider_id" \
      --rpc-url "$LOTUS_RPC_URL" \
      --private-key "$deployer_private_key" \
      --gas-limit 10000000000 >/dev/null || return 1
    endorsed_raw="$(cast call "$endorsements_address" "containsProviderId(uint256)(bool)" "$provider_id" --rpc-url "$LOTUS_RPC_URL" | tr -d '\r\n[:space:]' || true)"
    [[ "$endorsed_raw" == "true" ]] || { provider_fail "provider endorsement failed for provider id $provider_id"; return 1; }
  fi
  touch "$CURIO_REPO_PATH/.init.pdp.endorsed"
  provider_log "Provider endorsement confirmed"

  # Ensure provider has USDFC balance for PDP/FWSS flows.
  provider_balance_raw="$(cast call "$usdfc_address" "balanceOf(address)(uint256)" "$provider_eth_address" --rpc-url "$LOTUS_RPC_URL" | tr -d '\r\n' || true)"
  provider_balance_dec="$(to_decimal "$provider_balance_raw" || true)"
  if [[ ! "$provider_balance_dec" =~ [1-9] ]]; then
    provider_log "Provider USDFC balance is zero; transferring funding amount $PDP_USDFC_FUND_AMOUNT_WEI"
    with_deployer_tx_lock cast send "$usdfc_address" "transfer(address,uint256)" "$provider_eth_address" "$PDP_USDFC_FUND_AMOUNT_WEI" \
      --rpc-url "$LOTUS_RPC_URL" \
      --private-key "$deployer_private_key" \
      --gas-limit 100000000 >/dev/null || return 1
    provider_balance_raw="$(cast call "$usdfc_address" "balanceOf(address)(uint256)" "$provider_eth_address" --rpc-url "$LOTUS_RPC_URL" | tr -d '\r\n' || true)"
    provider_balance_dec="$(to_decimal "$provider_balance_raw" || true)"
    [[ "$provider_balance_dec" =~ [1-9] ]] || { provider_fail "provider USDFC funding failed for $provider_eth_address"; return 1; }
  fi
  touch "$CURIO_REPO_PATH/.init.pdp.usdfc"

  printf 'provider_id=%s\nprovider_eth_address=%s\n' "$provider_id" "$provider_eth_address" > "$PROVIDER_READY_FILE"
  provider_log "Provider bootstrap done; wrote readiness file $PROVIDER_READY_FILE"
  return 0
}

# Long-running provider bootstrap worker with lock + bounded retries.
bootstrap_provider_background() {
  local attempts=0
  mkdir -p "$(dirname "$PROVIDER_READY_FILE")"
  if command -v flock >/dev/null 2>&1; then
    exec 9>"$PROVIDER_LOCK_FILE"
    if ! flock -n 9; then
      echo "Provider bootstrap worker already running; skipping duplicate worker"
      return 0
    fi
  fi

  while true; do
    attempts=$((attempts + 1))
    provider_log "Attempt $attempts"
    if bootstrap_provider_once; then
      echo "Provider bootstrap complete"
      return 0
    fi
    if [[ "$PROVIDER_BOOTSTRAP_MAX_RETRIES" -gt 0 && "$attempts" -ge "$PROVIDER_BOOTSTRAP_MAX_RETRIES" ]]; then
      echo "Provider bootstrap failed after $attempts attempts"
      return 1
    fi
    echo "Provider bootstrap not ready yet; retrying in ${PROVIDER_BOOTSTRAP_RETRY_INTERVAL_SEC}s..."
    sleep "$PROVIDER_BOOTSTRAP_RETRY_INTERVAL_SEC"
  done
}

# One-time PDP setup against Curio JSON-RPC:
# - create/import PDP delegated key
# - register storage provider metadata via FSRegister
bootstrap_pdp_registry() {
  local pdp_key_marker="$CURIO_REPO_PATH/.init.pdp.key"
  local pdp_register_marker="$CURIO_REPO_PATH/.init.pdp.register"
  local pdp_wallet_file="$CURIO_REPO_PATH/pdp_wallet.addr"
  local pdp_wallet
  local pdp_private_key_hex
  local fund_cid

  if [[ ! -f "$pdp_key_marker" ]]; then
    if [[ -f "$pdp_wallet_file" ]]; then
      pdp_wallet="$(tr -d '\r\n' < "$pdp_wallet_file")"
    else
      pdp_wallet="$(lotus wallet new delegated | tr -d '\r\n')"
      echo "$pdp_wallet" > "$pdp_wallet_file"
    fi

    fund_cid="$(lotus send "$pdp_wallet" "$PDP_WALLET_FUND_AMOUNT" | awk '/^bafy/{print $1}' | tail -n1 | tr -d '\r\n')"
    [[ -n "$fund_cid" ]] || {
      echo "Failed to fund PDP wallet: $pdp_wallet" >&2
      return 1
    }
    lotus state wait-msg "$fund_cid" >/dev/null
    wait_for_delegated_actor "$pdp_wallet"

    pdp_private_key_hex="$(lotus wallet export "$pdp_wallet" | xxd -r -p | jq -r '.PrivateKey' | base64 -d | xxd -p -c 256 | tr -d '\r\n')"
    jsonrpc_call "ImportPDPKey" "$(jq -cn --arg key "$pdp_private_key_hex" '[$key]')"
    touch "$pdp_key_marker"
  fi

  if [[ ! -f "$pdp_register_marker" ]]; then
    jsonrpc_call "FSRegister" "$(jq -cn --arg n "$PDP_SERVICE_NAME" --arg d "$PDP_SERVICE_DESCRIPTION" --arg l "$PDP_SERVICE_LOCATION" '[$n, $d, $l]')"
    touch "$pdp_register_marker"
  fi
}

# Wait for Lotus sync/bootstrap threshold before starting mutable setup.
echo CURIO_REPO_PATH=$CURIO_REPO_PATH
echo Wait for lotus is ready ...
lotus wait-api
head=0
# Loop until the head is greater than 9
while [[ $head -le 9 ]]; do
    head=$(lotus chain list | awk '{print $1}' | awk -F':' '{print $1}' | tail -1)
    if [[ $head -le 9 ]]; then
        echo "Current head: $head, which is not greater than 9. Waiting..."
        sleep 1  # Wait for 4 seconds before checking again
    else
        echo "The head is now greater than 9: $head"
    fi
done

echo All ready. Lets go

# First-run setup block.
# All steps here create persistent markers under CURIO_REPO_PATH.
if [ ! -f $CURIO_REPO_PATH/.init.curio ]; then
  echo Wait for lotus-miner is ready ...
  lotus-miner wait-api

  # Create miner actor once.
  if [ ! -f $CURIO_REPO_PATH/.init.setup ]; then
  export DEFAULT_WALLET=`lotus wallet default`
	echo Create a new miner actor ...
	sptool --actor t01000 actor new-miner --owner $DEFAULT_WALLET --worker $DEFAULT_WALLET --from $DEFAULT_WALLET --sector-size 8MiB --confidence 1
	touch $CURIO_REPO_PATH/.init.setup
	fi

	# Create Curio market config once.
	if [ ! -f $CURIO_REPO_PATH/.init.config ]; then

	newminer=`lotus state list-miners | grep -v t01000`
	echo "New Miner is $newminer"
	echo Initiating a new Curio cluster ...
	curio config new-cluster $newminer
	echo Creating market config...
  curio config get base | sed -e 's/#Miners = \[\]/Miners = ["'"$newminer"'"]/g' | curio config set --title base
  CONFIG_CONTENT='[HTTP]
    DelegateTLS = true
    DomainName = "curio"
    Enable = true

  [Ingest]
    MaxDealWaitTime = "0h0m30s"

  [Market]
    [Market.StorageMarketConfig]
      [Market.StorageMarketConfig.IPNI]
        DirectAnnounceURLs = ["http://indexer:3001"]
        ServiceURL = ["http://indexer:3000"]
      [Market.StorageMarketConfig.MK12]
          ExpectedPoRepSealDuration = "0h1m0s"
          ExpectedSnapSealDuration = "0h1m0s"
          PublishMsgPeriod = "0h0m10s"

      [[Market.StorageMarketConfig.PieceLocator]]
        URL = "http://piece-server:12320/pieces"

  [Subsystems]
    EnableCommP = true
    EnableDealMarket = true
    EnableParkPiece = true
    EnablePDP = true

  [Batching]
    [Batching.PreCommit]
      Timeout = "0h0m5s"
      Slack = "6h0m0s"
    [Batching.Commit]
      Timeout = "0h0m5s"
      Slack = "1h0m0s"
	  '
  echo "$CONFIG_CONTENT" | curio config create --title market
  touch $CURIO_REPO_PATH/.init.config
  fi

  wait_and_source_contract_env

  # Start temporary Curio process to run storage attach and initial PDP registration.
  echo Starting Curio node to attach storage ...
  curio run --nosync --layers seal,post,market,gui &
  CURIO_PID=`echo $!`
  until curio cli --machine $myip:12300 wait-api; do
    echo "Waiting for the curio CLI to become ready..."
    sleep 5
  done
  curio cli --machine $myip:12300 storage attach --init --seal --store $CURIO_REPO_PATH
  touch $CURIO_REPO_PATH/.init.curio

  echo "Bootstrapping PDP key and service registration..."
  bootstrap_pdp_registry

  # Kick off a couple of sectors so chain state starts moving.
  echo "Starting sealing 2 sectors"
  curio seal start --cc --actor $newminer --now --count 2

  echo Stopping Curio node ...
  echo Try to stop curio...
      kill -15 $CURIO_PID || kill -9 $CURIO_PID
	echo Done
fi

wait_and_source_contract_env

# Start steady-state Curio process.
echo Starting curio node ...
curio run --nosync --name devnet --layers seal,post,market,gui &
CURIO_MAIN_PID=$!

# Run provider contract bootstrap in parallel with main Curio process.
echo "Starting provider bootstrap worker ..."
bootstrap_provider_background &
PROVIDER_BOOTSTRAP_PID=$!

# If main Curio exits first, propagate that exit code.
while kill -0 "$PROVIDER_BOOTSTRAP_PID" >/dev/null 2>&1; do
  if ! kill -0 "$CURIO_MAIN_PID" >/dev/null 2>&1; then
    wait "$CURIO_MAIN_PID"
    exit $?
  fi
  sleep 1
done

# Provider bootstrap failed: stop Curio and exit non-zero.
wait "$PROVIDER_BOOTSTRAP_PID"
PROVIDER_BOOTSTRAP_RC=$?
if [[ "$PROVIDER_BOOTSTRAP_RC" -ne 0 ]]; then
  echo "Provider bootstrap failed; stopping curio"
  kill -15 "$CURIO_MAIN_PID" >/dev/null 2>&1 || true
  wait "$CURIO_MAIN_PID" >/dev/null 2>&1 || true
  exit "$PROVIDER_BOOTSTRAP_RC"
fi

# Provider bootstrap succeeded; keep container lifecycle tied to Curio main process.
wait "$CURIO_MAIN_PID"
