# Help and quick usage guidance.

.PHONY: help
help:
	@echo "Curio Makefile help"
	@echo ""
	@echo "Core targets"
	@echo "  make deps         Build external/native dependencies only (ffi/blst/supraseal as needed)"
	@echo "  make build        Build default binaries: curio + sptool"
	@echo "  make calibnet     Same as build, plus calibnet tag"
	@echo "  make debug        Same as build, plus debug tag"
	@echo "  make 2k           Same as build, plus 2k tag"
	@echo "  make gen          Run full generation pipeline (forces FFI_USE_OPENCL=1)"
	@echo "  make test         Run integration test target from scripts/makefiles/20-test.mk"
	@echo "  make cov          Run Go coverage and open coverage report"
	@echo "  note: CI currently runs go test directly (not make test)"
	@echo ""
	@echo "Build variant model"
	@echo "  build/calibnet/debug/2k all run the same build pipeline; they differ by CURIO_TAGS only."
	@echo "  - build:    CURIO_TAGS defaults to CURIO_TAGS_BASE + optional extras"
	@echo "  - calibnet: build + calibnet"
	@echo "  - debug:    build + debug"
	@echo "  - 2k:       build + 2k"
	@echo ""
	@echo "Common override examples"
	@echo "  make build FFI_USE_OPENCL=1"
	@echo "  make build FFI_USE_OPENCL=0 DISABLE_SUPRASEAL=1"
	@echo "  make build FFI_USE_OPENCL=0 FFI_USE_CUDA_SUPRASEAL=0"
	@echo "  make calibnet FFI_USE_OPENCL=1"
	@echo "  make debug GOFLAGS='-mod=mod -trimpath'"
	@echo "  make 2k CURIO_TAGS='cunative 2k debug'"
	@echo "  make curio-native GOAMD64_NATIVE=v2"
	@echo "  make gen GOCACHE_CLEAN=1"
	@echo ""
	@echo "Current resolved values (for this invocation)"
	@echo "  GOCC=$(GOCC)"
	@echo "  FFI_USE_OPENCL=$(if $(FFI_USE_OPENCL),$(FFI_USE_OPENCL),<unset>)"
	@echo "  FFI_USE_CUDA=$(FFI_USE_CUDA)"
	@echo "  FFI_USE_CUDA_SUPRASEAL=$(FFI_USE_CUDA_SUPRASEAL)"
	@echo "  FFI_USE_CUDA_SUPRASEAL_EFFECTIVE=$(FFI_USE_CUDA_SUPRASEAL_EFFECTIVE)"
	@echo "  DISABLE_SUPRASEAL=$(DISABLE_SUPRASEAL)"
	@echo "  CURIO_TAGS_BASE=$(CURIO_TAGS_BASE)"
	@echo "  CURIO_TAGS=$(CURIO_TAGS)"
	@echo "  GOFLAGS=$(if $(GOFLAGS),$(GOFLAGS),<unset>)"
	@echo ""
	@echo "Detailed variable guide: documentation/en/developer/make-variables.md"
	@echo "Build scenarios: documentation/en/developer/make-variables.md#detailed-make-build-scenarios"
