name: 'Install Dependencies'
description: 'Install common dependencies including CUDA for supraseal linking'

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          gcc-13 g++-13 \
          pkg-config \
          autoconf automake libtool \
          curl wget git \
          ca-certificates gnupg \
          python3 python3-pip python3-dev python3-venv \
          xxd nasm \
          ocl-icd-opencl-dev libhwloc-dev \
          libfuse3-dev uuid-dev libssl-dev libnuma-dev libaio-dev libarchive-dev libkeyutils-dev libncurses-dev \
          libgmp-dev libconfig++-dev
      shell: bash

    - name: Set up GCC 13 as default
      run: |
        sudo update-alternatives --remove-all gcc 2>/dev/null || true
        sudo update-alternatives --remove-all g++ 2>/dev/null || true
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100
        echo "CC=gcc-13" >> $GITHUB_ENV
        echo "CXX=g++-13" >> $GITHUB_ENV
      shell: bash

    - name: Install CUDA Toolkit
      run: |
        if [ -f "/usr/local/cuda/bin/nvcc" ]; then
          echo "CUDA already installed"
          exit 0
        fi
        wget -q https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
        sudo dpkg -i cuda-keyring_1.1-1_all.deb
        rm cuda-keyring_1.1-1_all.deb
        sudo apt-get update
        sudo apt-get -y install cuda-toolkit
      shell: bash

    - name: Set up CUDA environment
      run: |
        echo "/usr/local/cuda/bin" >> $GITHUB_PATH
        echo "CUDA_HOME=/usr/local/cuda" >> $GITHUB_ENV
        # Set up CUDA stubs for linking without GPU
        STUBS="/usr/local/cuda/lib64/stubs"
        if [ -d "$STUBS" ]; then
          sudo ln -sf "$STUBS/libcuda.so" "$STUBS/libcuda.so.1" 2>/dev/null || true
          echo "LD_LIBRARY_PATH=$STUBS:/usr/local/cuda/lib64" >> $GITHUB_ENV
          echo "LIBRARY_PATH=$STUBS:/usr/local/cuda/lib64" >> $GITHUB_ENV
        fi
      shell: bash

    # NOTE: CI sometimes flakes on large/full fetches (HTTP/2 early EOF).
    # We only need tags (and only from origin) for versioning/metadata, so keep
    # this fetch minimal and retry with HTTP/1.1.
    - name: Fetch tags (resilient)
      run: |
        set -euo pipefail
        git config --global http.version HTTP/1.1
        git config --global http.postBuffer 524288000 || true

        # Fetch only from origin (if present) and only tags; retry on transient network errors.
        tries=0
        until [ "$tries" -ge 4 ]; do
          tries=$((tries+1))
          if git fetch origin --tags --force --prune --no-recurse-submodules; then
            exit 0
          fi
          echo "git fetch failed (attempt $tries/4), retrying in $((tries*5))s..." >&2
          sleep $((tries*5))
        done
        echo "git fetch failed after 4 attempts" >&2
        exit 1
      shell: bash

    - name: Sync submodules
      run: git submodule sync
      shell: bash

    - name: Update submodules
      run: git submodule update --init --recursive
      shell: bash

