name: 'Install Dependencies'
description: 'Install common dependencies including CUDA 12 and GCC 12 for supraseal'

runs:
  using: 'composite'
  steps:
    - name: Free up disk space
      run: |
        # Remove unnecessary packages to free up space for CUDA installation
        # NOTE: Do NOT remove $AGENT_TOOLSDIRECTORY as it contains tools installed
        # by actions/setup-go and other setup actions
        sudo apt-get clean
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
      shell: bash

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          curl ca-certificates gnupg \
          ocl-icd-opencl-dev libhwloc-dev \
          build-essential \
          gcc-12 g++-12 \
          nasm \
          pkg-config \
          autoconf automake libtool \
          libssl-dev \
          libnuma-dev \
          uuid-dev \
          libaio-dev \
          libfuse3-dev \
          libarchive-dev \
          libkeyutils-dev \
          libncurses-dev \
          python3 python3-pip python3-dev python3-venv \
          wget git \
          xxd \
          libconfig++-dev \
          libgmp-dev
      shell: bash

    - name: Set up GCC 12 as default
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 100
        sudo update-alternatives --set gcc /usr/bin/gcc-12
        sudo update-alternatives --set g++ /usr/bin/g++-12
        echo "GCC version: $(gcc --version | head -1)"
      shell: bash

    - name: Get Ubuntu version for cache key
      id: ubuntu-version
      run: echo "version=$(lsb_release -rs)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache CUDA installation
      id: cache-cuda
      uses: actions/cache@v4
      with:
        path: /usr/local/cuda
        key: cuda-toolkit-ubuntu-${{ steps.ubuntu-version.outputs.version }}-12-v2

    - name: Install CUDA Toolkit from NVIDIA Repository
      if: steps.cache-cuda.outputs.cache-hit != 'true'
      run: |
        # Install CUDA using official NVIDIA repository for Ubuntu 24.04
        # Source: https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=24.04&target_type=deb_local
        
        # Skip if CUDA is already installed (shouldn't happen without cache, but just in case)
        if [ -f "/usr/local/cuda/bin/nvcc" ]; then
          echo "CUDA already installed"
          /usr/local/cuda/bin/nvcc --version
          exit 0
        fi
        
        # Download and install the CUDA keyring package
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
        sudo dpkg -i cuda-keyring_1.1-1_all.deb
        rm cuda-keyring_1.1-1_all.deb
        
        # Update package list and install CUDA toolkit
        sudo apt-get update
        sudo apt-get -y install cuda-toolkit
        
        # Verify installation and find CUDA location
        if [ -d "/usr/local/cuda" ]; then
          echo "CUDA installed at /usr/local/cuda"
          ls -la /usr/local/cuda*/bin/nvcc || true
          # Show CUDA version for debugging
          /usr/local/cuda/bin/nvcc --version || true
        else
          echo "ERROR: CUDA installation not found"
          exit 1
        fi
      shell: bash

    - name: Set up CUDA environment
      run: |
        # Verify CUDA installation exists
        if [ ! -d "/usr/local/cuda" ]; then
          echo "ERROR: /usr/local/cuda not found"
          echo "Searching for CUDA installations:"
          ls -la /usr/local/cuda* 2>/dev/null || echo "No CUDA directories found"
          exit 1
        fi
        
        # Export PATH locally to verify nvcc works
        export PATH="/usr/local/cuda/bin:$PATH"
        export CUDA_HOME=/usr/local/cuda
        
        # Add CUDA stubs to library paths for build-time linking
        # The stubs allow linking against libcuda.so.1 without requiring the actual NVIDIA driver
        CUDA_STUBS_DIR="/usr/local/cuda/lib64/stubs"
        if [ -d "$CUDA_STUBS_DIR" ]; then
          echo "Found CUDA stubs at $CUDA_STUBS_DIR"
          export LD_LIBRARY_PATH="$CUDA_STUBS_DIR:/usr/local/cuda/lib64:${LD_LIBRARY_PATH}"
          export LIBRARY_PATH="$CUDA_STUBS_DIR:/usr/local/cuda/lib64:${LIBRARY_PATH}"
        else
          echo "WARNING: CUDA stubs directory not found at $CUDA_STUBS_DIR"
          export LD_LIBRARY_PATH="/usr/local/cuda/lib64:${LD_LIBRARY_PATH}"
        fi
        
        # Verify nvcc is available and show version
        echo "Verifying CUDA installation:"
        nvcc --version
        
        # Check CUDA version meets minimum requirements (12+)
        CUDA_VERSION=$(nvcc --version | grep "release" | sed -n 's/.*release \([0-9]*\)\.\([0-9]*\).*/\1/p')
        echo "Detected CUDA version: $CUDA_VERSION"
        if [ "$CUDA_VERSION" -lt 12 ]; then
          echo "ERROR: CUDA $CUDA_VERSION is too old. Need CUDA 12 or newer."
          exit 1
        fi
        
        # Set environment for subsequent steps
        echo "/usr/local/cuda/bin" >> $GITHUB_PATH
        echo "CUDA_HOME=/usr/local/cuda" >> $GITHUB_ENV
        if [ -d "$CUDA_STUBS_DIR" ]; then
          echo "LD_LIBRARY_PATH=$CUDA_STUBS_DIR:/usr/local/cuda/lib64:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "LIBRARY_PATH=$CUDA_STUBS_DIR:/usr/local/cuda/lib64:$LIBRARY_PATH" >> $GITHUB_ENV
        else
          echo "LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Fetch all tags
      run: git fetch --all
      shell: bash

    - name: Sync submodules
      run: git submodule sync
      shell: bash

    - name: Update submodules
      run: git submodule update --init --recursive
      shell: bash

