name: 'Install Dependencies'
description: 'Install common dependencies'

runs:
  using: 'composite'
  steps:
    - name: Fetch all tags
      run: git fetch --all
      shell: bash

    - name: Sync submodules
      run: git submodule sync
      shell: bash

    - name: Update submodules
      run: git submodule update --init
      shell: bash

