name: Support Ticket
description: Support ticket for requesting help from Curio team
title: "[Support Ticket]: "
labels: ["support", "triage"]
body:
- type: checkboxes
  attributes:
    label: Curio component
    description: Please select the Curio component you are filing a bug for
    options:
      - label: PoRep Pipeline
        required: false
      - label: Snap Deals
        required: false
      - label: Market
        required: false
      - label: IPNI provider
        required: false
      - label: Curio UI
        required: false
      - label: Other
        required: false
- type: textarea
  id: version
  attributes:
    label: Curio Version
    render: text
    description: Enter the output of `curio --version`.
    placeholder: |
      e.g. 
      curio version 1.23.1+mainnet+git_038c7c3_2024-09-30T14:27:56+04:00
  validations:
    required: true
- type: textarea
  id: Description
  attributes:
    label: Describe the problem
    description: |
      This is where you get to tell us what went wrong, when doing so, please try to provide a clear and concise description of the bug with all related information:
      * What you were doing when you experienced the problem?
      * Any *error* messages you saw, *where* you saw them, and what you believe may have caused them (if you have any ideas).
      * What is the expected behaviour?
  validations:
    required: true
- type: textarea
  id: extraInfo
  attributes:
    label: Logging Information
    render: text
    description: |
      Please provide detailed logs for the problem. You can get set log level control as per the below example:
      * use `curio cli log list` to get all log systems available and set level by `curio cli log set-level`.
  validations:
    required: true
- type: textarea
  id: RepoSteps
  attributes:
    label: Repo Steps
    description: "Steps to reproduce the behavior if available"
    value: |
      1. Run '...'
      2. Do '...'
      3. See error '...'
      ...
  validations:
    required: false
