// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"ko": &dictionary{index: koIndex, data: koData},
		"zh": &dictionary{index: zhIndex, data: zhData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"   Then export its private key with:":                                                                    0,
	"(debug tool) Copy LM sector metadata into Curio DB":                                                      1,
	"(for init) limit storage space for sectors (expensive for very large paths!)":                            2,
	"(for init) path weight":                                                                                  3,
	"(for init) use path for long-term storage":                                                               4,
	"(for init) use path for sealing":                                                                         5,
	"--machine flag in cli command should point to the node where storage to redeclare is attached":           6,
	"1. Test your PDP service with: pdptool ping --service-url https://%s --service-name public":              7,
	"1. Test your PDP service with: pdptool ping --service-url https://your-domain.com --service-name public": 8,
	"1278 (3.5 years)":           9,
	"2 KiB":                      10,
	"2. Register your FWSS node": 11,
	"3. Explore FWSS & PDP tools at https://www.filecoin.services": 12,
	"32 GiB (recommended for mainnet)":                             13,
	"4. Join the community: Filecoin Slack #fil-pdp":               14,
	"64 GiB":                          15,
	"8 MiB":                           16,
	"<sector>":                        17,
	"Aborting migration.":             18,
	"Aborting remaining steps.":       19,
	"Accept a proposed service actor": 20,
	"Add URL to fetch data for offline deals":                21,
	"Add new storage path":                                   22,
	"Additional info is at http://docs.curiostorage.org":     23,
	"Address to listen for the GUI on":                       24,
	"Amount in FIL":                                          25,
	"Amount to deposit (FIL)":                                26,
	"Amount to redeem (FIL)":                                 27,
	"Analyze and display the layout of batch sealer threads": 28,
	"Analyze and display the layout of batch sealer threads on your CPU.\n\nIt provides detailed information about CPU utilization for batch sealing operations, including core allocation, thread\ndistribution for different batch sizes.": 29,
	"Both (seal and store)": 30,
	"CSV file location to use for multiple deal input. Each line in the file should be in the format 'uuid,raw size,url,header1,header2...'": 31,
	"Cancel a pending client withdrawal request":                            32,
	"Cancel a pending service withdrawal request":                           33,
	"Cannot reach the DB: %s":                                               34,
	"Cannot read the config.toml file in the provided directory, Error: %s": 35,
	"Check data integrity in unsealed sector files":                         36,
	"Client actor":                      37,
	"Client actor address":              38,
	"Client sender address":             39,
	"Collection of debugging utilities": 40,
	"Command separated list of hostnames for yugabyte cluster": 41,
	"Compare the configurations %s to %s. Changes between the miner IDs other than wallet addreses should be a new, minimal layer for runners that need it.": 42,
	"Complete a pending client withdrawal after the withdrawal window elapses":                                                                               43,
	"Complete a pending service withdrawal after the withdrawal window elapses":                                                                              44,
	"Compute WindowPoSt for performance and configuration testing.":                                                                                          45,
	"Compute WindowPoSt vanilla proofs and verify them.":                                                                                                     46,
	"Compute a proof-of-spacetime for a sector (requires the sector to be pre-sealed). These will not send to the chain.":                                    47,
	"Configuration 'base' was created to resemble this lotus-miner's config.toml .":                                                                          48,
	"Configuration 'base' was updated to include this miner's address":                                                                                       49,
	"Configuration 'base' was updated to include this miner's address (%s) and its wallet setup.":                                                            50,
	"Configuring HTTP settings for PDP...":                                                                                                                   51,
	"Connected to Yugabyte":                                                                                                                                  52,
	"Connected to Yugabyte. Schema is current.":                                                                                                              53,
	"Continue to connect and update schema.":                                                                                                                 54,
	"Continue to verify the addresses and create a new miner actor.":                                                                                         55,
	"Cordon a machine, set it to maintenance mode":                                                                                                           56,
	"Could not create repo from directory: %s. Aborting migration":                                                                                           57,
	"Could not lock miner repo. Your miner must be stopped: %s\n Aborting migration":                                                                         58,
	"Create a check task for a specific sector, wait for its completion, and output the result.\n   <miner-id>: The storage provider ID\n   <sector-number>: The sector number": 59,
	"Create a client voucher":                                        60,
	"Create a new miner":                                             61,
	"Create a new offline verified DDO deal for Curio":               62,
	"Create a provider voucher":                                      63,
	"Create new configuration for a new cluster":                     64,
	"Creating PDP configuration layer...":                            65,
	"Ctrl+C pressed in Terminal":                                     66,
	"Cumulative amount (FIL)":                                        67,
	"Custom `HEADER` to include in the HTTP request":                 68,
	"Database config error occurred, abandoning migration: %s ":      69,
	"Database: %s":                                                   70,
	"Delete %s":                                                      71,
	"Deposit FIL into the Router contract (client)":                  72,
	"Deposit funds into the service pool (service role)":             73,
	"Documentation: ":                                                74,
	"Downgrade a cluster's database to a previous software version.": 75,
	"Each step needs your confirmation and can be reversed. Press Ctrl+C to exit at any time.": 76,
	"Enable load balancing for connecting to the Postgres database in Yugabyte cluster":        77,
	"Enter %s address":                    78,
	"Enter storage path to add":           79,
	"Enter the Yugabyte database %s":      80,
	"Enter the Yugabyte database host(s)": 81,
	"Enter the info to connect to your Yugabyte database installation (https://download.yugabyte.com/)": 82,
	"Enter the info to create a new miner":                             83,
	"Enter the owner address":                                          84,
	"Enter the path to the configuration directory used by %s":         85,
	"Enter your delegated wallet private key (hex format):":            86,
	"Enter your domain name (e.g., market.mydomain.com)":               87,
	"Error connecting to Yugabyte database: %s":                        88,
	"Error connecting to full node API: %s":                            89,
	"Error expanding path: %s":                                         90,
	"Error generating PDP config: %s":                                  91,
	"Error getting API: %s":                                            92,
	"Error getting home directory: %s":                                 93,
	"Error getting token: %s":                                          94,
	"Error loading existing PDP config: %s":                            95,
	"Error saving PDP config: %s":                                      96,
	"Error saving config to layer: %s. Aborting Migration":             97,
	"Error writing file: %s":                                           98,
	"Error writing storage.json: %s":                                   99,
	"Ethereum address (0x): %s":                                        100,
	"Execute cli commands":                                             101,
	"Failed to create auth token: %s":                                  102,
	"Failed to create the miner actor: %s":                             103,
	"Failed to decode private key: %s":                                 104,
	"Failed to generate default config: %s":                            105,
	"Failed to generate random bytes for secret: %s":                   106,
	"Failed to get API info for FullNode: %s":                          107,
	"Failed to import PDP key: %s":                                     108,
	"Failed to insert 'base' config layer in database: %s":             109,
	"Failed to insert config into database: %s":                        110,
	"Failed to load base config from database: %s":                     111,
	"Failed to parse base config: %s":                                  112,
	"Failed to parse sector size: %s":                                  113,
	"Failed to parse the address: %s":                                  114,
	"Failed to regenerate base config: %s":                             115,
	"Fetch proving parameters":                                         116,
	"Filecoin %s channels: %s and %s":                                  117,
	"Filecoin decentralized storage network provider":                  118,
	"Filter by storage provider ID":                                    119,
	"Filter events by actor address; lists all if not specified":       120,
	"Filter events by sector number; requires --actor to be specified": 121,
	"Fix Boost migration":                                              122,
	"For detailed documentation, see: https://docs.curiostorage.org/experimental-features/enable-pdp":                        123,
	"For more servers, make /etc/curio.env with the curio.env database env and add the CURIO_LAYERS env to assign purposes.": 124,
	"Generate a supra_seal configuration": 125,
	"Generate a supra_seal configuration for a given batch size.\n\nThis command outputs a configuration expected by SupraSeal. Main purpose of this command is for debugging and testing.\nThe config can be used directly with SupraSeal binaries to test it without involving Curio.": 126,
	"Get Curio node info": 127,
	"Get a config layer by name. You may want to pipe the output to a file, or use 'less'": 128,
	"Get information about unsealed data":                                                  129,
	"Go Back":                                                                              130,
	"Host: %s":                                                                             131,
	"How long to commit sectors for":                                                       132,
	"How would you like to proceed?":                                                       133,
	"I want to:":                                                                           134,
	"If, however, the upgrade has a serious bug and you need to downgrade, first shutdown all nodes in your cluster and then run this command. Finally, only start downgraded nodes.": 135,
	"Ignore sectors that cannot be migrated": 136,
	"Import delegated wallet private key":    137,
	"Increase reliability using redundancy: start multiple machines with at-least the post layer: 'curio run --layers=post'": 138,
	"Initializing a new miner actor.":                                                           139,
	"Initiate a withdrawal request from the client's deposit":                                   140,
	"Initiate a withdrawal request from the service pool":                                       141,
	"Interpret stacked config layers by this version of curio, with system-generated comments.": 142,
	"Invalid private key: %s":                                                                   143,
	"Layer %s created. ":                                                                        144,
	"Limit output to the last N events":                                                         145,
	"List config layers present in the DB.":                                                     146,
	"List data from the sectors_unseal_pipeline and sectors_meta tables":                        147,
	"List log systems":                                                                          148,
	"List pipeline events":                                                                      149,
	"Listen address for HTTP server":                                                            150,
	"Location of the service provider":                                                          151,
	"Lotus-Miner to Curio Migration.":                                                           152,
	"Make sure to send FIL/tFIL to your 0x wallet address for PDP operations.":                  153,
	"Manage batch sealing operations":                                                           154,
	"Manage logging":                                                                            155,
	"Manage node config by layers. The layer 'base' will always be applied at Curio start-up.": 156,
	"Manage storage paths for this server.":                                                    157,
	"Manage the sealing pipeline":                                                              158,
	"Manage unsealed data":                                                                     159,
	"Math Utils":                                                                               160,
	"Maximum piece size":                                                                       161,
	"Migrate from existing Lotus-Miner":                                                        162,
	"Migrating lotus-miner config.toml to Curio in-database configuration.":                    163,
	"Migrating metadata for %d sectors.":                                                       164,
	"Miner %s created successfully":                                                            165,
	"Miner creation error occurred: %s ":                                                       166,
	"Minimum number of hugepages required":                                                     167,
	"Minimum piece size":                                                                       168,
	"Moves funds from the deal collateral wallet into escrow with the storage market actor": 169,
	"Name of the Postgres database in Yugabyte cluster":                                     170,
	"New Miner initialization complete.":                                                    171,
	"New service actor address":                                                             172,
	"Next steps:":                                                                           173,
	"No address provided":                                                                   174,
	"No domain provided, skipping HTTP configuration":                                       175,
	"No host provided":                                                                      176,
	"No path provided":                                                                      177,
	"No path provided, abandoning migration ":                                               178,
	"No private key provided":                                                               179,
	"No value provided":                                                                     180,
	"No, abort":                                                                             181,
	"No, keep it":                                                                           182,
	"Non-SP cluster configuration complete":                                                 183,
	"Non-SP cluster configuration created successfully":                                     184,
	"Non-SP cluster setup complete!":                                                        185,
	"Note: This command is intended to be used to verify PoSt compute performance.\nIt will not send any messages to the chain. Since it can compute any deadline, output may be incorrectly timed for the chain.": 186,
	"Number of 1GB hugepages to configure": 187,
	"Number of sectors to start":           188,
	"One database can serve multiple miner IDs: Run a migration for each lotus-miner.": 189,
	"Optional setup steps (you can skip these and configure later):":                   190,
	"Other":                              191,
	"Output file path (default: stdout)": 192,
	"Owner Wallet: %s":                   193,
	"PDP":                                194,
	"PDP (Proof of Data Possession) Configuration":                         195,
	"PDP configuration layer created":                                      196,
	"PDP layer already exists. What would you like to do?":                 197,
	"PDP setup complete!":                                                  198,
	"PDP wallet configured":                                                199,
	"PDP wallet imported":                                                  200,
	"PDP wallet imported successfully!":                                    201,
	"Password for connecting to the Postgres database in Yugabyte cluster": 202,
	"Password: %s":                                                         203,
	"Path already exists":                                                  204,
	"Path to miner repo":                                                   205,
	"Please do not run guided-setup again as miner creation is not idempotent. You need to run 'curio config new-cluster %s' to finish the configuration": 206,
	"Please do not run guided-setup again. You need to run 'curio config new-cluster' manually to finish the configuration":                               207,
	"Port for connecting to the Cassandra database in Yugabyte cluster":                                                                                   208,
	"Port for connecting to the Postgres database in Yugabyte cluster":                                                                                    209,
	"Port: %s":                                        210,
	"Pre-initialization steps complete":               211,
	"Print default node config":                       212,
	"Private key":                                     213,
	"Private key cannot be empty":                     214,
	"Propose a new service actor":                     215,
	"Provider actor":                                  216,
	"Provider actor address":                          217,
	"Provider sender address":                         218,
	"Provides a sample of CIDs from an indexed piece": 219,
	"Query the service state":                         220,
	"Query the state of a client":                     221,
	"Query the state of a provider":                   222,
	"Read Miner Config":                               223,
	"Really delete %s?":                               224,
	"Reconfigure PDP":                                 225,
	"Redeem a client voucher (service role)":          226,
	"Redeem a provider voucher (provider role)":       227,
	"Register a PDP service provider with Filecoin Service Registry Contract": 228,
	"Remove a named config layer.":                                            229,
	"Remove unsealed copies of sector containing this deal":                   230,
	"SP ID to compute WindowPoSt for":                                         231,
	"Seal (fast storage for sealing operations)":                              232,
	"Sector Size: %s":              233,
	"Sector selection failed: %s ": 234,
	"Sectors can be stored across many filesystem paths. These\ncommands provide ways to manage the storage a Curio node will use to store sectors\nlong term for proving (references as 'store') as well as how sectors will be\nstored while moving through the sealing pipeline (references as 'seal').": 235,
	"Select the Sector Size":                                    236,
	"Select the location of your lotus-miner config directory?": 237,
	"Sender Wallet: %s":                                         238,
	"Sender address":                                            239,
	"Service provider description":                              240,
	"Service provider name":                                     241,
	"Service sender address":                                    242,
	"Set a config layer or the base by providing a filename or stdin.": 243,
	"Set log level": 244,
	"Set the log level for logging systems:\n\n   The system flag can be specified multiple times.\n\n   eg) log set-level --system chain --system chainxchg debug\n\n   Available Levels:\n   debug\n   info\n   warn\n   error\n\n   Environment Variables:\n   GOLOG_LOG_LEVEL - Default log level for all log systems\n   GOLOG_LOG_FMT   - Change output log format (json, nocolor)\n   GOLOG_FILE      - Write logs to file\n   GOLOG_OUTPUT    - Specify whether to output to file, stderr, stdout or a combination, i.e. file+stderr\n": 245,
	"Set the target unseal state for a sector": 246,
	"Set the target unseal state for a specific sector.\n   <miner-id>: The storage provider ID\n   <sector-number>: The sector number\n   <target-state>: The target state (true, false, or none)\n\n   The unseal target state indicates to curio how an unsealed copy of the sector should be maintained.\n\t   If the target state is true, curio will ensure that the sector is unsealed.\n\t   If the target state is false, curio will ensure that there is no unsealed copy of the sector.\n\t   If the target state is none, curio will not change the current state of the sector.\n\n   Currently when the curio will only start new unseal processes when the target state changes from another state to true.\n\n   When the target state is false, and an unsealed sector file exists, the GC mark step will create a removal mark\n   for the unsealed sector file. The file will only be removed after the removal mark is accepted.\n": 247,
	"Setting up PDP wallet...": 248,
	"Setup SPDK for batch sealing (configures hugepages and binds NVMe devices)": 249,
	"Setup SPDK for batch sealing operations.\n\nThis command automatically:\n- Downloads SPDK if not already available\n- Configures 1GB hugepages (36 pages minimum)\n- Binds NVMe devices for use with SupraSeal\n\nRequires root/sudo access for SPDK setup operations.": 250,
	"Setup non-Storage Provider cluster": 251,
	"Shortest frequency interval in epochs at which the SP is willing to prove access to the stored dataset": 252,
	"Skip PDP setup":                                     253,
	"Skip optional steps":                                254,
	"Skip wallet setup for now":                          255,
	"Specify actor address for the deal":                 256,
	"Specify actor address to start sealing sectors for": 257,
	"Specify wallet address to send the funds from":      258,
	"Start Curio web interface":                          259,
	"Start a Curio process":                              260,
	"Start an instance of Curio web interface. \n\tThis creates the 'web' layer if it does not exist, then calls run with that layer.": 261,
	"Start new sealing operations manually":                      262,
	"Start sealing new CC sectors":                               263,
	"Start sealing sectors for all actors now (not on schedule)": 264,
	"Step Complete: %s\n":                                        265,
	"Stop a running Curio process":                               266,
	"Storage":                                                    267,
	"Storage Configuration":                                      268,
	"Storage can be attached to a Curio node using this command. The storage volume\nlist is stored local to the Curio node in storage.json set in curio run. We do not\nrecommend manually modifying this value without further understanding of the\nstorage system.\n\nEach storage volume contains a configuration file which describes the\ncapabilities of the volume. When the '--init' flag is provided, this file will\nbe created using the additional flags.\n\nWeight\nA high weight value means data will be more likely to be stored in this path\n\nSeal\nData for the sealing process will be stored here\n\nStore\nFinalized sectors that will be moved here for long term storage and be proven\nover time\n   ": 269,
	"Storage path %s added as %s. You'll need to initialize it with: curio cli storage attach --init --%s %s": 270,
	"Storage path %s removed from configuration":                                                              271,
	"Storage path added":             272,
	"Storage path deleted":           273,
	"Storage paths for this server:": 274,
	"Storage price per TiB per month in USDFC, Default is 1 USDFC.": 275,
	"Storage type for %s":                          276,
	"Store (long-term storage for sealed sectors)": 277,
	"Supports IPNI IPFS CID indexing":              278,
	"Supports IPNI piece CID indexing":             279,
	"Supra consensus testing utilities":            280,
	"Test the windowpost scheduler by running it on the next available curio. If tasks fail all retries, you will need to ctrl+c to exit.":                                                               281,
	"The '%s' layer stores common configuration. All curio instances can include it in their %s argument.":                                                                                               282,
	"This interactive tool creates a new miner actor and creates the basic configuration layer for it.":                                                                                                  283,
	"This interactive tool migrates lotus-miner to Curio in 5 minutes.":                                                                                                                                  284,
	"This interactive tool sets up a non-Storage Provider cluster for protocols like PDP, Snark market, and others.":                                                                                     285,
	"This process is partially idempotent. Once a new miner actor has been created and subsequent steps fail, the user need to run 'curio config new-cluster < miner ID >' to finish the configuration.": 286,
	"This setup does not create or migrate a Filecoin SP actor.":                                                                                                                                         287,
	"This will configure PDP settings for your Curio cluster.":                                                                                                                                           288,
	"To run Curio: With machine or cgroup isolation, use the command (with example layer selection):":                                                                                                    289,
	"To start Curio with PDP enabled, run:":                                                                                                                                                              290,
	"To start the cluster, run: curio run --layers basic-cluster":                                                                                                                                        291,
	"To start, ensure your sealing pipeline is drained and shut-down lotus-miner.":                                                                                                                       292,
	"To work with the config: ":                                            293,
	"Token contract for payment (IERC20(address(0)) for FIL)":              294,
	"Tool Box for Curio":                                                   295,
	"Try the web interface with %s ":                                       296,
	"URL of the service provider":                                          297,
	"Uncordon a machine, resume scheduling":                                298,
	"Unmigratable sectors found. Do you want to continue?":                 299,
	"Update data for messages in wait queue":                               300,
	"Updated DB with message data missing from chain node":                 301,
	"Use existing key, ending in %s":                                       302,
	"Use synthetic PoRep":                                                  303,
	"Use the arrow keys to navigate: ↓ ↑ → ← ":                             304,
	"Username for connecting to the Postgres database in Yugabyte cluster": 305,
	"Username: %s":                                                      306,
	"Using existing PDP wallet key: %s":                                 307,
	"Utility functions for testing":                                     308,
	"Validate a client voucher signature":                               309,
	"Validate a provider voucher signature":                             310,
	"Voucher nonce":                                                     311,
	"Voucher signature (hex)":                                           312,
	"Wait for Curio api to come online":                                 313,
	"Where should we save your database config file?":                   314,
	"Withdrawal amount (in FIL)":                                        315,
	"Worker Wallet: %s":                                                 316,
	"YYYYMMDD when your cluster had the preferred schema. Ex: 20251128": 317,
	"Yes, continue":                                                     318,
	"Yes, delete it":                                                    319,
	"You can add other layers for per-machine configuration changes.":   320,
	"You can create a new delegated wallet using Lotus:":                321,
	"You can now migrate your market node (%s), if applicable.":         322,
	"You can now start using Curio for protocols like PDP, Snark markets, and others.": 323,
	"You can set up the wallet later using the Curio GUI or CLI":                       324,
	"You need a delegated Filecoin wallet address to use with PDP.":                    325,
	"Your non-SP cluster has been configured successfully.":                            326,
	"Zen3 and later supports two sectors per thread, set to false for older CPUs":      327,
	"[SP actor address...]":           328,
	"[deadline index]":                329,
	"[layer name]":                    330,
	"[level]":                         331,
	"[miner address] [sector number]": 332,
	"[path]":                          333,
	"[sectorSize]":                    334,
	"`URL` to send the request to":    335,
	"a layer's file name":             336,
	"a list of layers to be interpreted as the final config":                             337,
	"allow overwrite of existing layer if source is a different layer":                   338,
	"attach local storage path":                                                          339,
	"check how many entries need to be fixed":                                            340,
	"comma or space separated list of layers to be interpreted (base is always applied)": 341,
	"could not get API info for FullNode: %w":                                            342,
	"curio run --layers=gui,pdp":                                                         343,
	"custom node name":                                                                   344,
	"deadline to compute WindowPoSt for ":                                                345,
	"depends on output being a TTY":                                                      346,
	"detach local storage path":                                                          347,
	"do not interpret source layer":                                                      348,
	"don't check full-node sync status":                                                  349,
	"don't comment default values":                                                       350,
	"duration to wait till fail":                                                         351,
	"edit a config layer":                                                                352,
	"editor to use":                                                                      353,
	"enables very verbose mode, useful for debugging the CLI":                            354,
	"find sector in the storage system":                                                  355,
	"generate ipni chunks from a file":                                                   356,
	"generate vanilla proof for a sector":                                                357,
	"host address and port the gui will listen on":                                       358,
	"host address and port the worker api will listen on":                                359,
	"indicates that deal index should not be announced to the IPNI":                      360,
	"initialize the path first":                                                          361,
	"layer name":                                                                         362,
	"limit to log system":                                                                363,
	"list local storage paths":                                                           364,
	"list of layers to be interpreted (atop defaults). Default: base":                    365,
	"location of boost.db file":                                                          366,
	"lotus wallet export <address> | xxd -r -p | jq -r '.PrivateKey' | base64 -d | xxd -p -c 32": 367,
	"lotus wallet new delegated":                                 368,
	"machine host:port (curio run --listen address)":             369,
	"manage open file limit":                                     370,
	"manage sector storage":                                      371,
	"maximum fee in FIL user is willing to pay for this message": 372,
	"only list local storage paths":                              373,
	"only run init, then return":                                 374,
	"output in json format":                                      375,
	"partition to compute WindowPoSt for":                        376,
	"path group names":                                           377,
	"path groups allowed to pull data from this path (allow all if not specified)": 378,
	"piece-cid": 379,
	"redeclare sectors in a local storage path":               380,
	"save the whole config into the layer, not just the diff": 381,
	"source config layer":                                     382,
	"start epoch by when the deal should be proved by provider on-chain (default: 2 days from now)": 383,
	"start sealing a deal sector early":                                       384,
	"title of the config layer (req'd for stdin)":                             385,
	"true if --source is set":                                                 386,
	"use color in display output":                                             387,
	"yugabyte hosts to connect to over cassandra interface eg '127.0.0.1'":    388,
	"yugabyte password to connect to over cassandra interface eg 'cassandra'": 389,
	"yugabyte username to connect to over cassandra interface eg 'cassandra'": 390,
}

var enIndex = []uint32{ // 392 elements
	// Entry 0 - 1F
	0x00000000, 0x00000029, 0x0000005c, 0x000000a9,
	0x000000c0, 0x000000ea, 0x0000010a, 0x00000168,
	0x000001c6, 0x0000022e, 0x0000023f, 0x00000245,
	0x00000260, 0x0000029d, 0x000002be, 0x000002ed,
	0x000002f4, 0x000002fa, 0x00000303, 0x00000317,
	0x00000331, 0x00000351, 0x00000379, 0x0000038e,
	0x000003c1, 0x000003e2, 0x000003f0, 0x00000408,
	0x0000041f, 0x00000456, 0x0000053a, 0x00000550,
	// Entry 20 - 3F
	0x000005d7, 0x00000602, 0x0000062e, 0x00000649,
	0x00000692, 0x000006c0, 0x000006cd, 0x000006e2,
	0x000006f8, 0x0000071a, 0x00000753, 0x000007f0,
	0x00000839, 0x00000883, 0x000008c1, 0x000008f4,
	0x00000968, 0x000009b6, 0x000009f7, 0x00000a56,
	0x00000a7b, 0x00000a91, 0x00000abb, 0x00000ae2,
	0x00000b21, 0x00000b4e, 0x00000b8e, 0x00000bdf,
	0x00000c87, 0x00000c9f, 0x00000cb2, 0x00000ce3,
	// Entry 40 - 5F
	0x00000cfd, 0x00000d28, 0x00000d4c, 0x00000d67,
	0x00000d7f, 0x00000dae, 0x00000def, 0x00000dff,
	0x00000e0c, 0x00000e3a, 0x00000e6d, 0x00000e81,
	0x00000ec0, 0x00000f19, 0x00000f6b, 0x00000f7f,
	0x00000f99, 0x00000fbb, 0x00000fdf, 0x00001041,
	0x00001066, 0x0000107e, 0x000010ba, 0x000010f0,
	0x00001123, 0x00001150, 0x00001179, 0x00001195,
	0x000011b8, 0x000011d1, 0x000011f5, 0x00001210,
	// Entry 60 - 7F
	0x00001239, 0x00001258, 0x00001290, 0x000012aa,
	0x000012cc, 0x000012e9, 0x000012fe, 0x00001321,
	0x00001349, 0x0000136d, 0x00001396, 0x000013c8,
	0x000013f3, 0x00001413, 0x0000144b, 0x00001478,
	0x000014a8, 0x000014cb, 0x000014ee, 0x00001511,
	0x00001539, 0x00001552, 0x0000157b, 0x000015ab,
	0x000015c9, 0x00001604, 0x00001645, 0x00001659,
	0x000016b9, 0x00001730, 0x00001754, 0x00001864,
	// Entry 80 - 9F
	0x00001878, 0x000018cd, 0x000018f1, 0x000018f9,
	0x00001905, 0x00001924, 0x00001943, 0x0000194e,
	0x000019fe, 0x00001a25, 0x00001a49, 0x00001ac0,
	0x00001ae0, 0x00001b18, 0x00001b4c, 0x00001ba6,
	0x00001bc1, 0x00001bdb, 0x00001bfd, 0x00001c23,
	0x00001c66, 0x00001c77, 0x00001c8c, 0x00001cab,
	0x00001ccc, 0x00001cec, 0x00001d35, 0x00001d55,
	0x00001d64, 0x00001dbd, 0x00001de3, 0x00001dff,
	// Entry A0 - BF
	0x00001e14, 0x00001e1f, 0x00001e32, 0x00001e54,
	0x00001e9a, 0x00001ec0, 0x00001ee1, 0x00001f0b,
	0x00001f30, 0x00001f43, 0x00001f99, 0x00001fcb,
	0x00001fee, 0x00002008, 0x00002014, 0x00002028,
	0x00002058, 0x00002069, 0x0000207a, 0x000020a6,
	0x000020be, 0x000020d0, 0x000020da, 0x000020e6,
	0x0000210c, 0x0000213e, 0x0000215d, 0x00002229,
	0x0000224e, 0x00002269, 0x000022ba, 0x000022f9,
	// Entry C0 - DF
	0x000022ff, 0x00002322, 0x00002336, 0x0000233a,
	0x00002367, 0x00002387, 0x000023bc, 0x000023d0,
	0x000023e6, 0x000023fa, 0x0000241c, 0x00002461,
	0x00002471, 0x00002485, 0x00002498, 0x0000252f,
	0x000025a5, 0x000025e7, 0x00002628, 0x00002634,
	0x00002656, 0x00002670, 0x0000267c, 0x00002698,
	0x000026b4, 0x000026c3, 0x000026da, 0x000026f2,
	0x00002722, 0x0000273a, 0x00002756, 0x00002774,
	// Entry E0 - FF
	0x00002786, 0x0000279b, 0x000027ab, 0x000027d2,
	0x000027fc, 0x00002844, 0x00002861, 0x00002897,
	0x000028b7, 0x000028e2, 0x000028f5, 0x00002919,
	0x00002a3c, 0x00002a53, 0x00002a8d, 0x00002aa2,
	0x00002ab1, 0x00002ace, 0x00002ae4, 0x00002afb,
	0x00002b3c, 0x00002b4a, 0x00002d48, 0x00002d71,
	0x000030f7, 0x00003110, 0x0000315b, 0x0000325b,
	0x0000327e, 0x000032e5, 0x000032f4, 0x00003308,
	// Entry 100 - 11F
	0x00003322, 0x00003345, 0x00003378, 0x000033a6,
	0x000033c0, 0x000033d6, 0x00003455, 0x0000347b,
	0x00003498, 0x000034d3, 0x000034ed, 0x0000350a,
	0x00003512, 0x00003528, 0x000037d8, 0x0000384c,
	0x0000387a, 0x0000388d, 0x000038a2, 0x000038c1,
	0x000038ff, 0x00003916, 0x00003943, 0x00003963,
	0x00003984, 0x000039a6, 0x00003a2b, 0x00003a96,
	0x00003af8, 0x00003b3a, 0x00003ba9, 0x00003c6c,
	// Entry 120 - 13F
	0x00003ca7, 0x00003ce0, 0x00003d40, 0x00003d66,
	0x00003da2, 0x00003def, 0x00003e0d, 0x00003e45,
	0x00003e58, 0x00003e7e, 0x00003e9a, 0x00003ec0,
	0x00003ef5, 0x00003f1c, 0x00003f51, 0x00003f73,
	0x00003f87, 0x00003fbc, 0x00004001, 0x00004011,
	0x00004036, 0x00004054, 0x00004078, 0x0000409e,
	0x000040ac, 0x000040c4, 0x000040e6, 0x00004116,
	0x00004131, 0x00004146, 0x00004188, 0x00004196,
	// Entry 140 - 15F
	0x000041a5, 0x000041e5, 0x00004218, 0x00004255,
	0x000042a6, 0x000042e1, 0x0000431f, 0x00004355,
	0x000043a1, 0x000043b7, 0x000043c8, 0x000043d5,
	0x000043dd, 0x000043fd, 0x00004404, 0x00004411,
	0x0000442e, 0x00004442, 0x00004479, 0x000044ba,
	0x000044d4, 0x000044fc, 0x0000454f, 0x0000457a,
	0x00004595, 0x000045a6, 0x000045ce, 0x000045ec,
	0x00004606, 0x00004624, 0x00004646, 0x00004663,
	// Entry 160 - 17F
	0x0000467e, 0x00004692, 0x000046a0, 0x000046d8,
	0x000046fa, 0x0000471b, 0x0000473f, 0x0000476c,
	0x000047a0, 0x000047de, 0x000047f8, 0x00004803,
	0x00004817, 0x00004830, 0x00004870, 0x0000488a,
	0x000048e5, 0x00004900, 0x0000492f, 0x00004946,
	0x0000495c, 0x00004997, 0x000049b5, 0x000049d0,
	0x000049e6, 0x00004a0a, 0x00004a1b, 0x00004a68,
	0x00004a72, 0x00004a9c, 0x00004ad4, 0x00004ae8,
	// Entry 180 - 19F
	0x00004b46, 0x00004b68, 0x00004b94, 0x00004bac,
	0x00004bc8, 0x00004c0d, 0x00004c55, 0x00004c9d,
} // Size: 1592 bytes

const enData string = "" + // Size: 19613 bytes
	"\x04\x03   \x00\x22\x02Then export its private key with:\x02(debug tool)" +
	" Copy LM sector metadata into Curio DB\x02(for init) limit storage space" +
	" for sectors (expensive for very large paths!)\x02(for init) path weight" +
	"\x02(for init) use path for long-term storage\x02(for init) use path for" +
	" sealing\x02--machine flag in cli command should point to the node where" +
	" storage to redeclare is attached\x021. Test your PDP service with: pdpt" +
	"ool ping --service-url https://%[1]s --service-name public\x021. Test yo" +
	"ur PDP service with: pdptool ping --service-url https://your-domain.com " +
	"--service-name public\x021278 (3.5 years)\x022 KiB\x022. Register your F" +
	"WSS node\x023. Explore FWSS & PDP tools at https://www.filecoin.services" +
	"\x0232 GiB (recommended for mainnet)\x024. Join the community: Filecoin " +
	"Slack #fil-pdp\x0264 GiB\x028 MiB\x02<sector>\x02Aborting migration.\x02" +
	"Aborting remaining steps.\x02Accept a proposed service actor\x02Add URL " +
	"to fetch data for offline deals\x02Add new storage path\x02Additional in" +
	"fo is at http://docs.curiostorage.org\x02Address to listen for the GUI o" +
	"n\x02Amount in FIL\x02Amount to deposit (FIL)\x02Amount to redeem (FIL)" +
	"\x02Analyze and display the layout of batch sealer threads\x02Analyze an" +
	"d display the layout of batch sealer threads on your CPU.\x0a\x0aIt prov" +
	"ides detailed information about CPU utilization for batch sealing operat" +
	"ions, including core allocation, thread\x0adistribution for different ba" +
	"tch sizes.\x02Both (seal and store)\x02CSV file location to use for mult" +
	"iple deal input. Each line in the file should be in the format 'uuid,raw" +
	" size,url,header1,header2...'\x02Cancel a pending client withdrawal requ" +
	"est\x02Cancel a pending service withdrawal request\x02Cannot reach the D" +
	"B: %[1]s\x02Cannot read the config.toml file in the provided directory, " +
	"Error: %[1]s\x02Check data integrity in unsealed sector files\x02Client " +
	"actor\x02Client actor address\x02Client sender address\x02Collection of " +
	"debugging utilities\x02Command separated list of hostnames for yugabyte " +
	"cluster\x02Compare the configurations %[1]s to %[2]s. Changes between th" +
	"e miner IDs other than wallet addreses should be a new, minimal layer fo" +
	"r runners that need it.\x02Complete a pending client withdrawal after th" +
	"e withdrawal window elapses\x02Complete a pending service withdrawal aft" +
	"er the withdrawal window elapses\x02Compute WindowPoSt for performance a" +
	"nd configuration testing.\x02Compute WindowPoSt vanilla proofs and verif" +
	"y them.\x02Compute a proof-of-spacetime for a sector (requires the secto" +
	"r to be pre-sealed). These will not send to the chain.\x02Configuration " +
	"'base' was created to resemble this lotus-miner's config.toml .\x02Confi" +
	"guration 'base' was updated to include this miner's address\x02Configura" +
	"tion 'base' was updated to include this miner's address (%[1]s) and its " +
	"wallet setup.\x02Configuring HTTP settings for PDP...\x02Connected to Yu" +
	"gabyte\x02Connected to Yugabyte. Schema is current.\x02Continue to conne" +
	"ct and update schema.\x02Continue to verify the addresses and create a n" +
	"ew miner actor.\x02Cordon a machine, set it to maintenance mode\x02Could" +
	" not create repo from directory: %[1]s. Aborting migration\x02Could not " +
	"lock miner repo. Your miner must be stopped: %[1]s\x0a Aborting migratio" +
	"n\x02Create a check task for a specific sector, wait for its completion," +
	" and output the result.\x0a   <miner-id>: The storage provider ID\x0a   " +
	"<sector-number>: The sector number\x02Create a client voucher\x02Create " +
	"a new miner\x02Create a new offline verified DDO deal for Curio\x02Creat" +
	"e a provider voucher\x02Create new configuration for a new cluster\x02Cr" +
	"eating PDP configuration layer...\x02Ctrl+C pressed in Terminal\x02Cumul" +
	"ative amount (FIL)\x02Custom `HEADER` to include in the HTTP request\x04" +
	"\x00\x01 <\x02Database config error occurred, abandoning migration: %[1]" +
	"s\x02Database: %[1]s\x02Delete %[1]s\x02Deposit FIL into the Router cont" +
	"ract (client)\x02Deposit funds into the service pool (service role)\x04" +
	"\x00\x01 \x0f\x02Documentation:\x02Downgrade a cluster's database to a p" +
	"revious software version.\x02Each step needs your confirmation and can b" +
	"e reversed. Press Ctrl+C to exit at any time.\x02Enable load balancing f" +
	"or connecting to the Postgres database in Yugabyte cluster\x02Enter %[1]" +
	"s address\x02Enter storage path to add\x02Enter the Yugabyte database %[" +
	"1]s\x02Enter the Yugabyte database host(s)\x02Enter the info to connect " +
	"to your Yugabyte database installation (https://download.yugabyte.com/)" +
	"\x02Enter the info to create a new miner\x02Enter the owner address\x02E" +
	"nter the path to the configuration directory used by %[1]s\x02Enter your" +
	" delegated wallet private key (hex format):\x02Enter your domain name (e" +
	".g., market.mydomain.com)\x02Error connecting to Yugabyte database: %[1]" +
	"s\x02Error connecting to full node API: %[1]s\x02Error expanding path: %" +
	"[1]s\x02Error generating PDP config: %[1]s\x02Error getting API: %[1]s" +
	"\x02Error getting home directory: %[1]s\x02Error getting token: %[1]s" +
	"\x02Error loading existing PDP config: %[1]s\x02Error saving PDP config:" +
	" %[1]s\x02Error saving config to layer: %[1]s. Aborting Migration\x02Err" +
	"or writing file: %[1]s\x02Error writing storage.json: %[1]s\x02Ethereum " +
	"address (0x): %[1]s\x02Execute cli commands\x02Failed to create auth tok" +
	"en: %[1]s\x02Failed to create the miner actor: %[1]s\x02Failed to decode" +
	" private key: %[1]s\x02Failed to generate default config: %[1]s\x02Faile" +
	"d to generate random bytes for secret: %[1]s\x02Failed to get API info f" +
	"or FullNode: %[1]s\x02Failed to import PDP key: %[1]s\x02Failed to inser" +
	"t 'base' config layer in database: %[1]s\x02Failed to insert config into" +
	" database: %[1]s\x02Failed to load base config from database: %[1]s\x02F" +
	"ailed to parse base config: %[1]s\x02Failed to parse sector size: %[1]s" +
	"\x02Failed to parse the address: %[1]s\x02Failed to regenerate base conf" +
	"ig: %[1]s\x02Fetch proving parameters\x02Filecoin %[1]s channels: %[2]s " +
	"and %[3]s\x02Filecoin decentralized storage network provider\x02Filter b" +
	"y storage provider ID\x02Filter events by actor address; lists all if no" +
	"t specified\x02Filter events by sector number; requires --actor to be sp" +
	"ecified\x02Fix Boost migration\x02For detailed documentation, see: https" +
	"://docs.curiostorage.org/experimental-features/enable-pdp\x02For more se" +
	"rvers, make /etc/curio.env with the curio.env database env and add the C" +
	"URIO_LAYERS env to assign purposes.\x02Generate a supra_seal configurati" +
	"on\x02Generate a supra_seal configuration for a given batch size.\x0a" +
	"\x0aThis command outputs a configuration expected by SupraSeal. Main pur" +
	"pose of this command is for debugging and testing.\x0aThe config can be " +
	"used directly with SupraSeal binaries to test it without involving Curio" +
	".\x02Get Curio node info\x02Get a config layer by name. You may want to " +
	"pipe the output to a file, or use 'less'\x02Get information about unseal" +
	"ed data\x02Go Back\x02Host: %[1]s\x02How long to commit sectors for\x02H" +
	"ow would you like to proceed?\x02I want to:\x02If, however, the upgrade " +
	"has a serious bug and you need to downgrade, first shutdown all nodes in" +
	" your cluster and then run this command. Finally, only start downgraded " +
	"nodes.\x02Ignore sectors that cannot be migrated\x02Import delegated wal" +
	"let private key\x02Increase reliability using redundancy: start multiple" +
	" machines with at-least the post layer: 'curio run --layers=post'\x02Ini" +
	"tializing a new miner actor.\x02Initiate a withdrawal request from the c" +
	"lient's deposit\x02Initiate a withdrawal request from the service pool" +
	"\x02Interpret stacked config layers by this version of curio, with syste" +
	"m-generated comments.\x02Invalid private key: %[1]s\x04\x00\x01 \x15\x02" +
	"Layer %[1]s created.\x02Limit output to the last N events\x02List config" +
	" layers present in the DB.\x02List data from the sectors_unseal_pipeline" +
	" and sectors_meta tables\x02List log systems\x02List pipeline events\x02" +
	"Listen address for HTTP server\x02Location of the service provider\x02Lo" +
	"tus-Miner to Curio Migration.\x02Make sure to send FIL/tFIL to your 0x w" +
	"allet address for PDP operations.\x02Manage batch sealing operations\x02" +
	"Manage logging\x02Manage node config by layers. The layer 'base' will al" +
	"ways be applied at Curio start-up.\x02Manage storage paths for this serv" +
	"er.\x02Manage the sealing pipeline\x02Manage unsealed data\x02Math Utils" +
	"\x02Maximum piece size\x02Migrate from existing Lotus-Miner\x02Migrating" +
	" lotus-miner config.toml to Curio in-database configuration.\x02Migratin" +
	"g metadata for %[1]d sectors.\x02Miner %[1]s created successfully\x04" +
	"\x00\x01 %\x02Miner creation error occurred: %[1]s\x02Minimum number of " +
	"hugepages required\x02Minimum piece size\x02Moves funds from the deal co" +
	"llateral wallet into escrow with the storage market actor\x02Name of the" +
	" Postgres database in Yugabyte cluster\x02New Miner initialization compl" +
	"ete.\x02New service actor address\x02Next steps:\x02No address provided" +
	"\x02No domain provided, skipping HTTP configuration\x02No host provided" +
	"\x02No path provided\x04\x00\x01 '\x02No path provided, abandoning migra" +
	"tion\x02No private key provided\x02No value provided\x02No, abort\x02No," +
	" keep it\x02Non-SP cluster configuration complete\x02Non-SP cluster conf" +
	"iguration created successfully\x02Non-SP cluster setup complete!\x02Note" +
	": This command is intended to be used to verify PoSt compute performance" +
	".\x0aIt will not send any messages to the chain. Since it can compute an" +
	"y deadline, output may be incorrectly timed for the chain.\x02Number of " +
	"1GB hugepages to configure\x02Number of sectors to start\x02One database" +
	" can serve multiple miner IDs: Run a migration for each lotus-miner.\x02" +
	"Optional setup steps (you can skip these and configure later):\x02Other" +
	"\x02Output file path (default: stdout)\x02Owner Wallet: %[1]s\x02PDP\x02" +
	"PDP (Proof of Data Possession) Configuration\x02PDP configuration layer " +
	"created\x02PDP layer already exists. What would you like to do?\x02PDP s" +
	"etup complete!\x02PDP wallet configured\x02PDP wallet imported\x02PDP wa" +
	"llet imported successfully!\x02Password for connecting to the Postgres d" +
	"atabase in Yugabyte cluster\x02Password: %[1]s\x02Path already exists" +
	"\x02Path to miner repo\x02Please do not run guided-setup again as miner " +
	"creation is not idempotent. You need to run 'curio config new-cluster %[" +
	"1]s' to finish the configuration\x02Please do not run guided-setup again" +
	". You need to run 'curio config new-cluster' manually to finish the conf" +
	"iguration\x02Port for connecting to the Cassandra database in Yugabyte c" +
	"luster\x02Port for connecting to the Postgres database in Yugabyte clust" +
	"er\x02Port: %[1]s\x02Pre-initialization steps complete\x02Print default " +
	"node config\x02Private key\x02Private key cannot be empty\x02Propose a n" +
	"ew service actor\x02Provider actor\x02Provider actor address\x02Provider" +
	" sender address\x02Provides a sample of CIDs from an indexed piece\x02Qu" +
	"ery the service state\x02Query the state of a client\x02Query the state " +
	"of a provider\x02Read Miner Config\x02Really delete %[1]s?\x02Reconfigur" +
	"e PDP\x02Redeem a client voucher (service role)\x02Redeem a provider vou" +
	"cher (provider role)\x02Register a PDP service provider with Filecoin Se" +
	"rvice Registry Contract\x02Remove a named config layer.\x02Remove unseal" +
	"ed copies of sector containing this deal\x02SP ID to compute WindowPoSt " +
	"for\x02Seal (fast storage for sealing operations)\x02Sector Size: %[1]s" +
	"\x04\x00\x01 \x1f\x02Sector selection failed: %[1]s\x02Sectors can be st" +
	"ored across many filesystem paths. These\x0acommands provide ways to man" +
	"age the storage a Curio node will use to store sectors\x0along term for " +
	"proving (references as 'store') as well as how sectors will be\x0astored" +
	" while moving through the sealing pipeline (references as 'seal').\x02Se" +
	"lect the Sector Size\x02Select the location of your lotus-miner config d" +
	"irectory?\x02Sender Wallet: %[1]s\x02Sender address\x02Service provider " +
	"description\x02Service provider name\x02Service sender address\x02Set a " +
	"config layer or the base by providing a filename or stdin.\x02Set log le" +
	"vel\x04\x00\x01\x0a\xf8\x03\x02Set the log level for logging systems:" +
	"\x0a\x0a   The system flag can be specified multiple times.\x0a\x0a   eg" +
	") log set-level --system chain --system chainxchg debug\x0a\x0a   Availa" +
	"ble Levels:\x0a   debug\x0a   info\x0a   warn\x0a   error\x0a\x0a   Envi" +
	"ronment Variables:\x0a   GOLOG_LOG_LEVEL - Default log level for all log" +
	" systems\x0a   GOLOG_LOG_FMT   - Change output log format (json, nocolor" +
	")\x0a   GOLOG_FILE      - Write logs to file\x0a   GOLOG_OUTPUT    - Spe" +
	"cify whether to output to file, stderr, stdout or a combination, i.e. fi" +
	"le+stderr\x02Set the target unseal state for a sector\x04\x00\x01\x0a" +
	"\x80\x07\x02Set the target unseal state for a specific sector.\x0a   <mi" +
	"ner-id>: The storage provider ID\x0a   <sector-number>: The sector numbe" +
	"r\x0a   <target-state>: The target state (true, false, or none)\x0a\x0a " +
	"  The unseal target state indicates to curio how an unsealed copy of the" +
	" sector should be maintained.\x0a\x09   If the target state is true, cur" +
	"io will ensure that the sector is unsealed.\x0a\x09   If the target stat" +
	"e is false, curio will ensure that there is no unsealed copy of the sect" +
	"or.\x0a\x09   If the target state is none, curio will not change the cur" +
	"rent state of the sector.\x0a\x0a   Currently when the curio will only s" +
	"tart new unseal processes when the target state changes from another sta" +
	"te to true.\x0a\x0a   When the target state is false, and an unsealed se" +
	"ctor file exists, the GC mark step will create a removal mark\x0a   for " +
	"the unsealed sector file. The file will only be removed after the remova" +
	"l mark is accepted.\x02Setting up PDP wallet...\x02Setup SPDK for batch " +
	"sealing (configures hugepages and binds NVMe devices)\x02Setup SPDK for " +
	"batch sealing operations.\x0a\x0aThis command automatically:\x0a- Downlo" +
	"ads SPDK if not already available\x0a- Configures 1GB hugepages (36 page" +
	"s minimum)\x0a- Binds NVMe devices for use with SupraSeal\x0a\x0aRequire" +
	"s root/sudo access for SPDK setup operations.\x02Setup non-Storage Provi" +
	"der cluster\x02Shortest frequency interval in epochs at which the SP is " +
	"willing to prove access to the stored dataset\x02Skip PDP setup\x02Skip " +
	"optional steps\x02Skip wallet setup for now\x02Specify actor address for" +
	" the deal\x02Specify actor address to start sealing sectors for\x02Speci" +
	"fy wallet address to send the funds from\x02Start Curio web interface" +
	"\x02Start a Curio process\x02Start an instance of Curio web interface. " +
	"\x0a\x09This creates the 'web' layer if it does not exist, then calls ru" +
	"n with that layer.\x02Start new sealing operations manually\x02Start sea" +
	"ling new CC sectors\x02Start sealing sectors for all actors now (not on " +
	"schedule)\x04\x00\x01\x0a\x15\x02Step Complete: %[1]s\x02Stop a running " +
	"Curio process\x02Storage\x02Storage Configuration\x04\x00\x04\x0a   \xa7" +
	"\x05\x02Storage can be attached to a Curio node using this command. The " +
	"storage volume\x0alist is stored local to the Curio node in storage.json" +
	" set in curio run. We do not\x0arecommend manually modifying this value " +
	"without further understanding of the\x0astorage system.\x0a\x0aEach stor" +
	"age volume contains a configuration file which describes the\x0acapabili" +
	"ties of the volume. When the '--init' flag is provided, this file will" +
	"\x0abe created using the additional flags.\x0a\x0aWeight\x0aA high weigh" +
	"t value means data will be more likely to be stored in this path\x0a\x0a" +
	"Seal\x0aData for the sealing process will be stored here\x0a\x0aStore" +
	"\x0aFinalized sectors that will be moved here for long term storage and " +
	"be proven\x0aover time\x02Storage path %[1]s added as %[2]s. You'll need" +
	" to initialize it with: curio cli storage attach --init --%[3]s %[4]s" +
	"\x02Storage path %[1]s removed from configuration\x02Storage path added" +
	"\x02Storage path deleted\x02Storage paths for this server:\x02Storage pr" +
	"ice per TiB per month in USDFC, Default is 1 USDFC.\x02Storage type for " +
	"%[1]s\x02Store (long-term storage for sealed sectors)\x02Supports IPNI I" +
	"PFS CID indexing\x02Supports IPNI piece CID indexing\x02Supra consensus " +
	"testing utilities\x02Test the windowpost scheduler by running it on the " +
	"next available curio. If tasks fail all retries, you will need to ctrl+c" +
	" to exit.\x02The '%[1]s' layer stores common configuration. All curio in" +
	"stances can include it in their %[2]s argument.\x02This interactive tool" +
	" creates a new miner actor and creates the basic configuration layer for" +
	" it.\x02This interactive tool migrates lotus-miner to Curio in 5 minutes" +
	".\x02This interactive tool sets up a non-Storage Provider cluster for pr" +
	"otocols like PDP, Snark market, and others.\x02This process is partially" +
	" idempotent. Once a new miner actor has been created and subsequent step" +
	"s fail, the user need to run 'curio config new-cluster < miner ID >' to " +
	"finish the configuration.\x02This setup does not create or migrate a Fil" +
	"ecoin SP actor.\x02This will configure PDP settings for your Curio clust" +
	"er.\x02To run Curio: With machine or cgroup isolation, use the command (" +
	"with example layer selection):\x02To start Curio with PDP enabled, run:" +
	"\x02To start the cluster, run: curio run --layers basic-cluster\x02To st" +
	"art, ensure your sealing pipeline is drained and shut-down lotus-miner." +
	"\x04\x00\x01 \x19\x02To work with the config:\x02Token contract for paym" +
	"ent (IERC20(address(0)) for FIL)\x02Tool Box for Curio\x04\x00\x01 !\x02" +
	"Try the web interface with %[1]s\x02URL of the service provider\x02Uncor" +
	"don a machine, resume scheduling\x02Unmigratable sectors found. Do you w" +
	"ant to continue?\x02Update data for messages in wait queue\x02Updated DB" +
	" with message data missing from chain node\x02Use existing key, ending i" +
	"n %[1]s\x02Use synthetic PoRep\x04\x00\x01 0\x02Use the arrow keys to na" +
	"vigate: ↓ ↑ → ←\x02Username for connecting to the Postgres database in Y" +
	"ugabyte cluster\x02Username: %[1]s\x02Using existing PDP wallet key: %[1" +
	"]s\x02Utility functions for testing\x02Validate a client voucher signatu" +
	"re\x02Validate a provider voucher signature\x02Voucher nonce\x02Voucher " +
	"signature (hex)\x02Wait for Curio api to come online\x02Where should we " +
	"save your database config file?\x02Withdrawal amount (in FIL)\x02Worker " +
	"Wallet: %[1]s\x02YYYYMMDD when your cluster had the preferred schema. Ex" +
	": 20251128\x02Yes, continue\x02Yes, delete it\x02You can add other layer" +
	"s for per-machine configuration changes.\x02You can create a new delegat" +
	"ed wallet using Lotus:\x02You can now migrate your market node (%[1]s), " +
	"if applicable.\x02You can now start using Curio for protocols like PDP, " +
	"Snark markets, and others.\x02You can set up the wallet later using the " +
	"Curio GUI or CLI\x02You need a delegated Filecoin wallet address to use " +
	"with PDP.\x02Your non-SP cluster has been configured successfully.\x02Ze" +
	"n3 and later supports two sectors per thread, set to false for older CPU" +
	"s\x02[SP actor address...]\x02[deadline index]\x02[layer name]\x02[level" +
	"]\x02[miner address] [sector number]\x02[path]\x02[sectorSize]\x02`URL` " +
	"to send the request to\x02a layer's file name\x02a list of layers to be " +
	"interpreted as the final config\x02allow overwrite of existing layer if " +
	"source is a different layer\x02attach local storage path\x02check how ma" +
	"ny entries need to be fixed\x02comma or space separated list of layers t" +
	"o be interpreted (base is always applied)\x02could not get API info for " +
	"FullNode: %[1]w\x02curio run --layers=gui,pdp\x02custom node name\x04" +
	"\x00\x01 #\x02deadline to compute WindowPoSt for\x02depends on output be" +
	"ing a TTY\x02detach local storage path\x02do not interpret source layer" +
	"\x02don't check full-node sync status\x02don't comment default values" +
	"\x02duration to wait till fail\x02edit a config layer\x02editor to use" +
	"\x02enables very verbose mode, useful for debugging the CLI\x02find sect" +
	"or in the storage system\x02generate ipni chunks from a file\x02generate" +
	" vanilla proof for a sector\x02host address and port the gui will listen" +
	" on\x02host address and port the worker api will listen on\x02indicates " +
	"that deal index should not be announced to the IPNI\x02initialize the pa" +
	"th first\x02layer name\x02limit to log system\x02list local storage path" +
	"s\x02list of layers to be interpreted (atop defaults). Default: base\x02" +
	"location of boost.db file\x02lotus wallet export <address> | xxd -r -p |" +
	" jq -r '.PrivateKey' | base64 -d | xxd -p -c 32\x02lotus wallet new dele" +
	"gated\x02machine host:port (curio run --listen address)\x02manage open f" +
	"ile limit\x02manage sector storage\x02maximum fee in FIL user is willing" +
	" to pay for this message\x02only list local storage paths\x02only run in" +
	"it, then return\x02output in json format\x02partition to compute WindowP" +
	"oSt for\x02path group names\x02path groups allowed to pull data from thi" +
	"s path (allow all if not specified)\x02piece-cid\x02redeclare sectors in" +
	" a local storage path\x02save the whole config into the layer, not just " +
	"the diff\x02source config layer\x02start epoch by when the deal should b" +
	"e proved by provider on-chain (default: 2 days from now)\x02start sealin" +
	"g a deal sector early\x02title of the config layer (req'd for stdin)\x02" +
	"true if --source is set\x02use color in display output\x02yugabyte hosts" +
	" to connect to over cassandra interface eg '127.0.0.1'\x02yugabyte passw" +
	"ord to connect to over cassandra interface eg 'cassandra'\x02yugabyte us" +
	"ername to connect to over cassandra interface eg 'cassandra'"

var koIndex = []uint32{ // 392 elements
	// Entry 0 - 1F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 20 - 3F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 40 - 5F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 60 - 7F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 80 - 9F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry A0 - BF
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry C0 - DF
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry E0 - FF
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 100 - 11F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 120 - 13F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 140 - 15F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 160 - 17F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 180 - 19F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
} // Size: 1592 bytes

const koData string = ""

var zhIndex = []uint32{ // 392 elements
	// Entry 0 - 1F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 20 - 3F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 40 - 5F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 60 - 7F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 80 - 9F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry A0 - BF
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry C0 - DF
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry E0 - FF
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 100 - 11F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 120 - 13F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 140 - 15F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 160 - 17F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 180 - 19F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
} // Size: 1592 bytes

const zhData string = ""

// Total table size 24389 bytes (23KiB); checksum: 70693276
