// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"ko": &dictionary{index: koIndex, data: koData},
		"zh": &dictionary{index: zhIndex, data: zhData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"2 KiB":                     80,
	"32 GiB":                    78,
	"64 GiB":                    77,
	"8 MiB":                     79,
	"Aborting migration.":       31,
	"Aborting remaining steps.": 9,
	"Additional info is at http://docs.curiostorage.org":               22,
	"Aggregate-Anonymous: version, chain, and Miner power (bucketed).": 36,
	"CURIO_LAYERS: %s":        120,
	"CURIO_NODE_NAME: %s":     122,
	"CURIO_REPO_PATH: %s":     121,
	"Cannot reach the DB: %s": 85,
	"Cannot read the config.toml file in the provided directory, Error: %s":                                                                                  59,
	"Compare the configurations %s to %s. Changes between the miner IDs other than wallet addreses should be a new, minimal layer for runners that need it.": 133,
	"Configuration 'base' was created to resemble this lotus-miner's config.toml .":                                                                          134,
	"Configuration 'base' was updated to include this miner's address":                                                                                       94,
	"Configuration 'base' was updated to include this miner's address (%s) and its wallet setup.":                                                            132,
	"Connected to Yugabyte":                                                          53,
	"Connected to Yugabyte. Schema is current.":                                      52,
	"Continue to connect and update schema.":                                         104,
	"Continue to verify the addresses and create a new miner actor.":                 70,
	"Continue update the env file.":                                                  123,
	"Could not create repo from directory: %s. Aborting migration":                   60,
	"Could not lock miner repo. Your miner must be stopped: %s\n Aborting migration": 61,
	"Create a new miner":                                                             8,
	"Ctrl+C pressed in Terminal":                                                     5,
	"Database config error occurred, abandoning migration: %s ":                      105,
	"Database: %s":    103,
	"Documentation: ": 46,
	"Each step needs your confirmation and can be reversed. Press Ctrl+C to exit at any time.": 4,
	"Enter %s address":                    75,
	"Enter the %s":                        127,
	"Enter the Yugabyte database %s":      108,
	"Enter the Yugabyte database host(s)": 106,
	"Enter the config layer name to use for this node. Base is already included by default":             125,
	"Enter the info to configure your Curio node":                                                       119,
	"Enter the info to connect to your Yugabyte database installation (https://download.yugabyte.com/)": 98,
	"Enter the info to create a new miner":                                                              65,
	"Enter the owner address":                                                                           72,
	"Enter the path to the configuration directory used by %s":                                          57,
	"Env config error occurred, abandoning: %s ":                                                        124,
	"Error checking for service file at %s: %s":                                                         113,
	"Error connecting to Yugabyte database: %s":                                                         110,
	"Error connecting to full node API: %s":                                                             86,
	"Error enabling service: %s":                                                                        117,
	"Error getting API: %s":                                                                             25,
	"Error getting miner info: %s":                                                                      41,
	"Error getting miner power: %s":                                                                     39,
	"Error getting token: %s":                                                                           27,
	"Error getting user home directory:":                                                                12,
	"Error marshalling message: %s":                                                                     40,
	"Error opening %s file in write mode:":                                                              15,
	"Error opening %s file: %s":                                                                         13,
	"Error opening or creating file %s: %s":                                                             128,
	"Error reading %s file: %s":                                                                         14,
	"Error reloading systemd: %s":                                                                       116,
	"Error saving config to layer: %s. Aborting Migration":                                              32,
	"Error sending message: %s":                                                                         43,
	"Error sending message: Status %s, Message: ":                                                       44,
	"Error signing message: %s":                                                                         42,
	"Error writing service file: %s":                                                                    114,
	"Error writing to %s file: %s":                                                                      16,
	"Error writing to file %s: %s":                                                                      129,
	"Execute 'curio service-setup' to setup the Curio service on this node and proceed to do the same on the other nodes": 20,
	"Failed to create the miner actor: %s":                 83,
	"Failed to flush thw writes to file %s: %s":            17,
	"Failed to generate default config: %s":                92,
	"Failed to generate random bytes for secret: %s":       88,
	"Failed to get API info for FullNode: %w":              90,
	"Failed to insert 'base' config layer in database: %s": 93,
	"Failed to load base config from database: %s":         95,
	"Failed to parse base config: %s":                      96,
	"Failed to parse sector size: %s":                      82,
	"Failed to parse the address: %s":                      74,
	"Failed to regenerate base config: %s":                 97,
	"Failed to verify the auth token from daemon node: %s": 91,
	"Filecoin %s channels: %s and %s":                      49,
	"Hint: I am someone running Curio on whichever chain.": 37,
	"Host: %s":   99,
	"I want to:": 6,
	"Increase reliability using redundancy: start multiple machines with at-least the post layer: 'curio run --layers=post'": 50,
	"Individual Data: Miner ID, Curio version, chain (%s or %s). Signed.":                                                    35,
	"Initializing a new miner actor.":   64,
	"Layer %s created. ":                135,
	"Lotus-Miner to Curio Migration.":   10,
	"Message sent.":                     45,
	"Migrate from existing Lotus-Miner": 7,
	"Migrating lotus-miner config.toml to Curio in-database configuration.": 24,
	"Migrating metadata for %d sectors.":                                    131,
	"Miner %s created successfully":                                         84,
	"Miner creation error occurred: %s ":                                    71,
	"New Miner initialization complete.":                                    23,
	"No address provided":                                                   73,
	"No host provided":                                                      107,
	"No layer provided":                                                     126,
	"No path provided, abandoning migration ":                               58,
	"No value provided":                                                     109,
	"No, abort":                                                             30,
	"Not adding DB variables to RC file as shell %s is not BASH or ZSH.":    11,
	"Nothing.": 38,
	"One database can serve multiple miner IDs: Run a migration for each lotus-miner.": 51,
	"Other":            56,
	"Owner Wallet: %s": 66,
	"Password: %s":     102,
	"Please do not run guided-setup again as miner creation is not idempotent. You need to run 'curio config new-cluster %s' to finish the configuration": 89,
	"Port: %s":                          100,
	"Pre-initialization steps complete": 87,
	"Read Miner Config":                 62,
	"Retrying.......(%d/5)":             18,
	"Sector Size: %s":                   69,
	"Sector selection failed: %s ":      81,
	"Select the Sector Size":            76,
	"Select the location of your lotus-miner config directory?": 55,
	"Select what you want to share with the Curio team.":        34,
	"Sender Wallet: %s":     68,
	"Service %s enabled.\n": 118,
	"Service env file /etc/curio.env created successfully.":                                                130,
	"Service file %s already exists at %s, no changes made.":                                               112,
	"Service file %s created successfully at %s":                                                           115,
	"Step Complete: %s\n":                                                                                  63,
	"The '%s' layer stores common configuration. All curio instances can include it in their %s argument.": 47,
	"The Curio team wants to improve the software you use. Tell the team you're using `%s`.":               33,
	"This interactive tool creates a new miner actor and creates the basic configuration layer for it.":    1,
	"This interactive tool creates/replace Curio service file and creates the basic env file for it.":      111,
	"This interactive tool migrates lotus-miner to Curio in 5 minutes.":                                    3,
	"This process is partially idempotent. Once a new miner actor has been created and subsequent steps fail, the user need to run 'curio config new-cluster < miner ID >' to finish the configuration.": 2,
	"To run Curio: With machine or cgroup isolation, use the command (with example layer selection):":                                                                                                    137,
	"To start, ensure your sealing pipeline is drained and shut-down lotus-miner.":                                                                                                                       54,
	"To work with the config: ":                            136,
	"Try the web interface with %s ":                       19,
	"Unmigratable sectors found. Do you want to continue?": 28,
	"Use the arrow keys to navigate: ↓ ↑ → ← ":             0,
	"Username: %s":      101,
	"Worker Wallet: %s": 67,
	"Yes, continue":     29,
	"You can add other layers for per-machine configuration changes.": 48,
	"You can now migrate your market node (%s), if applicable.":       21,
	"could not get API info for FullNode: %w":                         26,
}

var enIndex = []uint32{ // 139 elements
	// Entry 0 - 1F
	0x00000000, 0x00000035, 0x00000097, 0x0000015a,
	0x0000019c, 0x000001f5, 0x00000210, 0x0000021b,
	0x0000023d, 0x00000250, 0x0000026a, 0x0000028a,
	0x000002d0, 0x000002f3, 0x00000313, 0x00000333,
	0x0000035b, 0x0000037e, 0x000003ae, 0x000003c7,
	0x000003ed, 0x00000461, 0x0000049e, 0x000004d1,
	0x000004f4, 0x0000053a, 0x00000553, 0x0000057e,
	0x00000599, 0x000005ce, 0x000005dc, 0x000005e6,
	// Entry 20 - 3F
	0x000005fa, 0x00000632, 0x0000068c, 0x000006bf,
	0x00000709, 0x0000074a, 0x0000077f, 0x00000788,
	0x000007a9, 0x000007ca, 0x000007ea, 0x00000807,
	0x00000824, 0x00000857, 0x00000865, 0x00000879,
	0x000008e4, 0x00000924, 0x0000094d, 0x000009c4,
	0x00000a15, 0x00000a3f, 0x00000a55, 0x00000aa2,
	0x00000adc, 0x00000ae2, 0x00000b1e, 0x00000b4a,
	0x00000b93, 0x00000bd3, 0x00000c24, 0x00000c36,
	// Entry 40 - 5F
	0x00000c50, 0x00000c70, 0x00000c95, 0x00000ca9,
	0x00000cbe, 0x00000cd3, 0x00000ce6, 0x00000d25,
	0x00000d4f, 0x00000d67, 0x00000d7b, 0x00000d9e,
	0x00000db2, 0x00000dc9, 0x00000dd0, 0x00000dd7,
	0x00000ddd, 0x00000de3, 0x00000e07, 0x00000e2a,
	0x00000e52, 0x00000e73, 0x00000e8e, 0x00000eb7,
	0x00000ed9, 0x00000f0b, 0x00000fa2, 0x00000fcd,
	0x00001005, 0x0000102e, 0x00001066, 0x000010a7,
	// Entry 60 - 7F
	0x000010d7, 0x000010fa, 0x00001122, 0x00001184,
	0x00001190, 0x0000119c, 0x000011ac, 0x000011bc,
	0x000011cc, 0x000011f3, 0x00001234, 0x00001258,
	0x00001269, 0x0000128b, 0x0000129d, 0x000012ca,
	0x0000132a, 0x00001367, 0x00001397, 0x000013b9,
	0x000013ea, 0x00001409, 0x00001427, 0x00001443,
	0x0000146f, 0x00001483, 0x0000149a, 0x000014b1,
	0x000014cf, 0x00001501, 0x00001557, 0x00001569,
	// Entry 80 - 9F
	0x00001579, 0x000015a5, 0x000015c8, 0x000015fe,
	0x00001624, 0x00001683, 0x00001720, 0x0000176e,
	0x00001788, 0x000017a6, 0x00001806,
} // Size: 580 bytes

const enData string = "" + // Size: 6150 bytes
	"\x04\x00\x01 0\x02Use the arrow keys to navigate: ↓ ↑ → ←\x02This intera" +
	"ctive tool creates a new miner actor and creates the basic configuration" +
	" layer for it.\x02This process is partially idempotent. Once a new miner" +
	" actor has been created and subsequent steps fail, the user need to run " +
	"'curio config new-cluster < miner ID >' to finish the configuration.\x02" +
	"This interactive tool migrates lotus-miner to Curio in 5 minutes.\x02Eac" +
	"h step needs your confirmation and can be reversed. Press Ctrl+C to exit" +
	" at any time.\x02Ctrl+C pressed in Terminal\x02I want to:\x02Migrate fro" +
	"m existing Lotus-Miner\x02Create a new miner\x02Aborting remaining steps" +
	".\x02Lotus-Miner to Curio Migration.\x02Not adding DB variables to RC fi" +
	"le as shell %[1]s is not BASH or ZSH.\x02Error getting user home directo" +
	"ry:\x02Error opening %[1]s file: %[2]s\x02Error reading %[1]s file: %[2]" +
	"s\x02Error opening %[1]s file in write mode:\x02Error writing to %[1]s f" +
	"ile: %[2]s\x02Failed to flush thw writes to file %[1]s: %[2]s\x02Retryin" +
	"g.......(%[1]d/5)\x04\x00\x01 !\x02Try the web interface with %[1]s\x02E" +
	"xecute 'curio service-setup' to setup the Curio service on this node and" +
	" proceed to do the same on the other nodes\x02You can now migrate your m" +
	"arket node (%[1]s), if applicable.\x02Additional info is at http://docs." +
	"curiostorage.org\x02New Miner initialization complete.\x02Migrating lotu" +
	"s-miner config.toml to Curio in-database configuration.\x02Error getting" +
	" API: %[1]s\x02could not get API info for FullNode: %[1]w\x02Error getti" +
	"ng token: %[1]s\x02Unmigratable sectors found. Do you want to continue?" +
	"\x02Yes, continue\x02No, abort\x02Aborting migration.\x02Error saving co" +
	"nfig to layer: %[1]s. Aborting Migration\x02The Curio team wants to impr" +
	"ove the software you use. Tell the team you're using `%[1]s`.\x02Select " +
	"what you want to share with the Curio team.\x02Individual Data: Miner ID" +
	", Curio version, chain (%[1]s or %[2]s). Signed.\x02Aggregate-Anonymous:" +
	" version, chain, and Miner power (bucketed).\x02Hint: I am someone runni" +
	"ng Curio on whichever chain.\x02Nothing.\x02Error getting miner power: %" +
	"[1]s\x02Error marshalling message: %[1]s\x02Error getting miner info: %[" +
	"1]s\x02Error signing message: %[1]s\x02Error sending message: %[1]s\x04" +
	"\x00\x01 .\x02Error sending message: Status %[1]s, Message:\x02Message s" +
	"ent.\x04\x00\x01 \x0f\x02Documentation:\x02The '%[1]s' layer stores comm" +
	"on configuration. All curio instances can include it in their %[2]s argu" +
	"ment.\x02You can add other layers for per-machine configuration changes." +
	"\x02Filecoin %[1]s channels: %[2]s and %[3]s\x02Increase reliability usi" +
	"ng redundancy: start multiple machines with at-least the post layer: 'cu" +
	"rio run --layers=post'\x02One database can serve multiple miner IDs: Run" +
	" a migration for each lotus-miner.\x02Connected to Yugabyte. Schema is c" +
	"urrent.\x02Connected to Yugabyte\x02To start, ensure your sealing pipeli" +
	"ne is drained and shut-down lotus-miner.\x02Select the location of your " +
	"lotus-miner config directory?\x02Other\x02Enter the path to the configur" +
	"ation directory used by %[1]s\x04\x00\x01 '\x02No path provided, abandon" +
	"ing migration\x02Cannot read the config.toml file in the provided direct" +
	"ory, Error: %[1]s\x02Could not create repo from directory: %[1]s. Aborti" +
	"ng migration\x02Could not lock miner repo. Your miner must be stopped: %" +
	"[1]s\x0a Aborting migration\x02Read Miner Config\x04\x00\x01\x0a\x15\x02" +
	"Step Complete: %[1]s\x02Initializing a new miner actor.\x02Enter the inf" +
	"o to create a new miner\x02Owner Wallet: %[1]s\x02Worker Wallet: %[1]s" +
	"\x02Sender Wallet: %[1]s\x02Sector Size: %[1]s\x02Continue to verify the" +
	" addresses and create a new miner actor.\x04\x00\x01 %\x02Miner creation" +
	" error occurred: %[1]s\x02Enter the owner address\x02No address provided" +
	"\x02Failed to parse the address: %[1]s\x02Enter %[1]s address\x02Select " +
	"the Sector Size\x0264 GiB\x0232 GiB\x028 MiB\x022 KiB\x04\x00\x01 \x1f" +
	"\x02Sector selection failed: %[1]s\x02Failed to parse sector size: %[1]s" +
	"\x02Failed to create the miner actor: %[1]s\x02Miner %[1]s created succe" +
	"ssfully\x02Cannot reach the DB: %[1]s\x02Error connecting to full node A" +
	"PI: %[1]s\x02Pre-initialization steps complete\x02Failed to generate ran" +
	"dom bytes for secret: %[1]s\x02Please do not run guided-setup again as m" +
	"iner creation is not idempotent. You need to run 'curio config new-clust" +
	"er %[1]s' to finish the configuration\x02Failed to get API info for Full" +
	"Node: %[1]w\x02Failed to verify the auth token from daemon node: %[1]s" +
	"\x02Failed to generate default config: %[1]s\x02Failed to insert 'base' " +
	"config layer in database: %[1]s\x02Configuration 'base' was updated to i" +
	"nclude this miner's address\x02Failed to load base config from database:" +
	" %[1]s\x02Failed to parse base config: %[1]s\x02Failed to regenerate bas" +
	"e config: %[1]s\x02Enter the info to connect to your Yugabyte database i" +
	"nstallation (https://download.yugabyte.com/)\x02Host: %[1]s\x02Port: %[1" +
	"]s\x02Username: %[1]s\x02Password: %[1]s\x02Database: %[1]s\x02Continue " +
	"to connect and update schema.\x04\x00\x01 <\x02Database config error occ" +
	"urred, abandoning migration: %[1]s\x02Enter the Yugabyte database host(s" +
	")\x02No host provided\x02Enter the Yugabyte database %[1]s\x02No value p" +
	"rovided\x02Error connecting to Yugabyte database: %[1]s\x02This interact" +
	"ive tool creates/replace Curio service file and creates the basic env fi" +
	"le for it.\x02Service file %[1]s already exists at %[2]s, no changes mad" +
	"e.\x02Error checking for service file at %[1]s: %[2]s\x02Error writing s" +
	"ervice file: %[1]s\x02Service file %[1]s created successfully at %[2]s" +
	"\x02Error reloading systemd: %[1]s\x02Error enabling service: %[1]s\x04" +
	"\x00\x01\x0a\x17\x02Service %[1]s enabled.\x02Enter the info to configur" +
	"e your Curio node\x02CURIO_LAYERS: %[1]s\x02CURIO_REPO_PATH: %[1]s\x02CU" +
	"RIO_NODE_NAME: %[1]s\x02Continue update the env file.\x04\x00\x01 -\x02E" +
	"nv config error occurred, abandoning: %[1]s\x02Enter the config layer na" +
	"me to use for this node. Base is already included by default\x02No layer" +
	" provided\x02Enter the %[1]s\x02Error opening or creating file %[1]s: %[" +
	"2]s\x02Error writing to file %[1]s: %[2]s\x02Service env file /etc/curio" +
	".env created successfully.\x02Migrating metadata for %[1]d sectors.\x02C" +
	"onfiguration 'base' was updated to include this miner's address (%[1]s) " +
	"and its wallet setup.\x02Compare the configurations %[1]s to %[2]s. Chan" +
	"ges between the miner IDs other than wallet addreses should be a new, mi" +
	"nimal layer for runners that need it.\x02Configuration 'base' was create" +
	"d to resemble this lotus-miner's config.toml .\x04\x00\x01 \x15\x02Layer" +
	" %[1]s created.\x04\x00\x01 \x19\x02To work with the config:\x02To run C" +
	"urio: With machine or cgroup isolation, use the command (with example la" +
	"yer selection):"

var koIndex = []uint32{ // 139 elements
	// Entry 0 - 1F
	0x00000000, 0x00000044, 0x000000c1, 0x000001c1,
	0x0000020e, 0x00000289, 0x000002aa, 0x000002bc,
	0x000002e5, 0x00000300, 0x00000325, 0x00000348,
	0x000003aa, 0x000003e8, 0x00000418, 0x00000448,
	0x00000483, 0x000004b3, 0x00000502, 0x00000524,
	0x00000563, 0x000005f5, 0x00000645, 0x00000685,
	0x000006ab, 0x00000704, 0x00000723, 0x0000075f,
	0x0000078f, 0x000007df, 0x000007eb, 0x000007fd,
	// Entry 20 - 3F
	0x00000818, 0x00000870, 0x000008fc, 0x00000935,
	0x0000098b, 0x000009c9, 0x00000a17, 0x00000a32,
	0x00000a6c, 0x00000a9f, 0x00000ad9, 0x00000b03,
	0x00000b2d, 0x00000b6f, 0x00000b93, 0x00000ba0,
	0x00000c26, 0x00000c78, 0x00000c9f, 0x00000d3b,
	0x00000dcd, 0x00000e0e, 0x00000e24, 0x00000e8f,
	0x00000ede, 0x00000ee5, 0x00000f2d, 0x00000f7f,
	0x00000fd9, 0x00001043, 0x000010d4, 0x000010ec,
	// Entry 40 - 5F
	0x00001106, 0x0000112a, 0x0000115d, 0x00001175,
	0x0000118d, 0x000011a5, 0x000011ba, 0x00001211,
	0x0000123c, 0x00001254, 0x0000127b, 0x0000129e,
	0x000012b2, 0x000012c7, 0x000012ce, 0x000012d5,
	0x000012db, 0x000012e1, 0x00001302, 0x0000132c,
	0x00001352, 0x0000138b, 0x000013c3, 0x000013fb,
	0x0000141a, 0x00001466, 0x00001524, 0x00001570,
	0x000015be, 0x000015e1, 0x0000163d, 0x0000168d,
	// Entry 60 - 7F
	0x000016e2, 0x00001725, 0x00001764, 0x000017d2,
	0x000017e3, 0x000017f1, 0x00001809, 0x0000181d,
	0x00001837, 0x00001861, 0x000018c4, 0x00001900,
	0x0000192a, 0x00001962, 0x00001986, 0x000019da,
	0x00001a46, 0x00001a97, 0x00001add, 0x00001b11,
	0x00001b5b, 0x00001b93, 0x00001bc9, 0x00001bfb,
	0x00001c32, 0x00001c46, 0x00001c5d, 0x00001c74,
	0x00001ca3, 0x00001cd7, 0x00001d57, 0x00001d81,
	// Entry 80 - 9F
	0x00001da2, 0x00001de7, 0x00001e17, 0x00001e6d,
	0x00001ea5, 0x00001f1e, 0x00001fd8, 0x0000202f,
	0x0000205e, 0x00002085, 0x00002111,
} // Size: 580 bytes

const koData string = "" + // Size: 8465 bytes
	"\x04\x00\x01 ?\x02화살표 키를 사용하여 이동하세요: ↓ ↑ → ←\x02이 대화형 도구는 새로운 채굴자 액터를 생성" +
	"하고 그에 대한 기본 구성 레이어를 생성합니다.\x02이 프로세스는 부분적으로 항등원적입니다. 새로운 채굴자 액터가 생성되었고" +
	" 후속 단계가 실패하는 경우 사용자는 구성을 완료하기 위해 'curio config new-cluster < 채굴자 ID >'를 " +
	"실행해야 합니다.\x02이 대화형 도구는 5분 안에 lotus-miner를 Curio로 이주합니다.\x02각 단계는 확인이 필" +
	"요하며 되돌릴 수 있습니다. 언제든지 Ctrl+C를 눌러 종료할 수 있습니다.\x02터미널에서 Ctrl+C가 눌림\x02나는 " +
	"원한다:\x02기존의 Lotus-Miner에서 이전하기\x02새로운 채굴자 생성\x02나머지 단계를 중단합니다.\x02Lotu" +
	"s-Miner에서 Curio로 이주.\x02셸 %[1]s이 BASH 또는 ZSH가 아니므로 RC 파일에 DB 변수를 추가하지 않습" +
	"니다.\x02사용자 홈 디렉토리를 가져오는 중 오류 발생:\x02%[1]s 파일을 여는 중 오류 발생: %[2]s\x02%[1" +
	"]s 파일을 읽는 중 오류 발생: %[2]s\x02%[1]s 파일을 쓰기 모드로 여는 중 오류 발생:\x02%[1]s 파일에 쓰는" +
	" 중 오류 발생: %[2]s\x02%[1]s 파일에 쓰기 내용을 플러시하는 데 실패했습니다: %[2]s\x02다시 시도 중...." +
	"...(%[1]d/5)\x04\x00\x01 :\x02%[1]s와 함께 웹 인터페이스를 시도해보세요\x02이 노드에서 Curio " +
	"서비스를 설정하려면 'curio service-setup'을 실행하고 다른 노드에서도 동일하게 진행하십시오.\x02해당하는 경" +
	"우 이제 시장 노드를 이주할 수 있습니다 (%[1]s).\x02추가 정보는 http://docs.curiostorage.org" +
	" 에 있습니다.\x02새로운 채굴자 초기화 완료.\x02lotus-miner config.toml을 Curio의 데이터베이스 구성" +
	"으로 이전 중입니다.\x02API 가져오기 오류: %[1]s\x02FullNode의 API 정보를 가져올 수 없습니다: %[1" +
	"]w\x02토큰을 가져오는 중 오류 발생: %[1]s\x02이동할 수 없는 섹터가 발견되었습니다. 계속하시겠습니까?\x02예, 계" +
	"속\x02아니오, 중단\x02마이그레이션 중단.\x02레이어에 구성을 저장하는 중 오류 발생: %[1]s. 마이그레이션 중단" +
	"\x02Curio 팀은 당신이 사용하는 소프트웨어를 개선하고자 합니다. 팀에게 `%[1]s`를 사용 중이라고 알려주세요.\x02C" +
	"urio 팀과 공유하고 싶은 것을 선택하세요.\x02개별 데이터: 채굴자 ID, Curio 버전, 체인 (%[1]s 또는 %[2]" +
	"s). 서명됨.\x02집계-익명: 버전, 체인, 및 채굴자 파워 (버킷).\x02힌트: 나는 어떤 체인에서든 Curio를 실행 중" +
	"인 사람입니다.\x02아무것도 없습니다.\x02마이너 파워를 가져오는 중 오류 발생: %[1]s\x02메시지를 마샬하는 중 오" +
	"류 발생: %[1]s\x02마이너 정보를 가져오는 중 오류 발생: %[1]s\x02메시지 서명 중 오류 발생: %[1]s" +
	"\x02메시지 전송 중 오류 발생: %[1]s\x04\x00\x01 =\x02메시지 전송 중 오류 발생: 상태 %[1]s, 메시지" +
	":\x02메시지가 전송되었습니다.\x04\x00\x01 \x08\x02문서:\x02'%[1]s' 레이어에는 공통 구성이 저장됩니다" +
	". 모든 Curio 인스턴스는 %[2]s 인수에 포함시킬 수 있습니다.\x02기계별 구성 변경을 위해 다른 레이어를 추가할 수 있" +
	"습니다.\x02Filecoin %[1]s 채널: %[2]s 및 %[3]s\x02신뢰성 향상을 위한 중복성 사용: 적어도 pos" +
	"t 레이어를 사용하여 여러 대의 기계를 시작하십시오: 'curio run --layers=post'\x02한 개의 데이터베이스는 " +
	"여러 광부 ID를 제공할 수 있습니다: 각 lotus-miner에 대해 마이그레이션을 실행하세요.\x02Yugabyte에 연결" +
	"되었습니다. 스키마가 현재입니다.\x02Yugabyte에 연결됨\x02시작하려면 밀봉 파이프라인이 비어 있고 lotus-min" +
	"er가 종료되었는지 확인하세요.\x02로터스 마이너 구성 디렉토리의 위치를 선택하시겠습니까?\x02기타\x02%[1]s에서 사용하" +
	"는 구성 디렉터리 경로를 입력하세요.\x04\x00\x01 M\x02경로가 제공되지 않았으므로 마이그레이션을 포기합니다\x02" +
	"제공된 디렉토리에서 config.toml 파일을 읽을 수 없습니다. 오류: %[1]s\x02디렉토리에서 저장소를 생성할 수 없" +
	"습니다: %[1]s. 마이그레이션을 중단합니다.\x02광부 저장소를 잠금 해제할 수 없습니다. 귀하의 광부를 중지해야 합니다:" +
	" %[1]s\x0a 마이그레이션을 중단합니다.\x02마이너 구성 읽기\x04\x00\x01\x0a\x15\x02단계 완료: %[1" +
	"]s\x02새 채굴자 액터 초기화 중.\x02새 채굴자를 생성하기 위한 정보 입력\x02소유자 지갑: %[1]s\x02작업자 지갑" +
	": %[1]s\x02발송자 지갑: %[1]s\x02섹터 크기: %[1]s\x02주소를 확인하고 새 채굴자 액터를 생성하려면 계속 " +
	"진행하세요.\x04\x00\x01 &\x02채굴자 생성 오류 발생: %[1]s\x02소유자 주소 입력\x02주소가 제공되지 않" +
	"았습니다\x02주소 구문 분석 실패: %[1]s\x02%[1]s 주소 입력\x02섹터 크기 선택\x0264 GiB\x0232 " +
	"GiB\x028 MiB\x022 KiB\x04\x00\x01 \x1c\x02섹터 선택 실패: %[1]s\x02섹터 크기 구문 분석" +
	" 실패: %[1]s\x02채굴자 액터 생성 실패: %[1]s\x02%[1]s 채굴자가 성공적으로 생성되었습니다\x02데이터베이스에" +
	" 연결할 수 없습니다: %[1]s\x02풀 노드 API에 연결하는 중 오류 발생: %[1]s\x02사전 초기화 단계 완료\x02비" +
	"밀번호를 위한 랜덤 바이트 생성에 실패했습니다: %[1]s\x02마이너 생성은 idempotent하지 않으므로 가이드 설정을 " +
	"다시 실행하지 마십시오. 구성을 완료하려면 'curio config new-cluster %[1]s'를 실행해야 합니다." +
	"\x02FullNode에 대한 API 정보를 가져오는 데 실패했습니다: %[1]w\x02데몬 노드로부터 인증 토큰을 확인하는 중 " +
	"오류 발생: %[1]s\x02기본 구성 생성 실패: %[1]s\x02데이터베이스에 'base' 구성 레이어를 삽입하는 데 실패" +
	"했습니다: %[1]s\x02이 마이너 주소를 포함한 구성 'base'가 업데이트되었습니다.\x02데이터베이스에서 기본 구성을 " +
	"로드하는 데 실패했습니다: %[1]s\x02기본 구성을 구문 분석하는 데 실패했습니다: %[1]s\x02기본 구성을 재생성하는" +
	" 데 실패했습니다: %[1]s\x02Yugabyte 데이터베이스 설치에 연결할 정보를 입력하십시오 (https://download" +
	".yugabyte.com/)\x02호스트: %[1]s\x02포트: %[1]s\x02사용자 이름: %[1]s\x02비밀번호: %[1" +
	"]s\x02데이터베이스: %[1]s\x02계속 연결 및 스키마 업데이트.\x04\x00\x01 ^\x02데이터베이스 구성 오류가 " +
	"발생하여 마이그레이션을 포기합니다: %[1]s\x02Yugabyte 데이터베이스 호스트를 입력하십시오\x02호스트가 제공되지 " +
	"않았습니다\x02Yugabyte 데이터베이스 %[1]s을 입력하십시오\x02값이 제공되지 않았습니다\x02Yugabyte 데이" +
	"터베이스에 연결하는 중 오류가 발생했습니다: %[1]s\x02이 대화형 도구는 Curio 서비스 파일을 생성/교체하고 기본 e" +
	"nv 파일을 생성합니다.\x02서비스 파일 %[1]s이 %[2]s에 이미 존재합니다. 변경 사항 없음.\x02%[1]s에서 서비스" +
	" 파일을 확인하는 중 오류 발생: %[2]s\x02서비스 파일을 쓰는 중 오류 발생: %[1]s\x02서비스 파일 %[1]s이 %" +
	"[2]s에 성공적으로 생성되었습니다.\x02systemd를 다시 로드하는 중 오류 발생: %[1]s\x02서비스를 활성화하는 중 " +
	"오류 발생: %[1]s\x04\x00\x01\x0a-\x02서비스 %[1]s이 활성화되었습니다.\x02Curio 노드를 구성할" +
	" 정보를 입력하십시오\x02CURIO_LAYERS: %[1]s\x02CURIO_REPO_PATH: %[1]s\x02CURIO_NO" +
	"DE_NAME: %[1]s\x02env 파일 업데이트를 계속하십시오.\x04\x00\x01 /\x02환경 설정 오류 발생, 중단 " +
	"중: %[1]s\x02이 노드에 사용할 구성 레이어 이름을 입력하십시오. 기본값으로 Base가 이미 포함되어 있습니다\x02레" +
	"이어가 제공되지 않았습니다\x02%[1]s을(를) 입력하십시오\x02파일 %[1]s을(를) 열거나 생성하는 중 오류 발생: %" +
	"[2]s\x02파일 %[1]s에 쓰는 중 오류 발생: %[2]s\x02서비스 환경 파일 /etc/curio.env이(가) 성공적으" +
	"로 생성되었습니다.\x02%[1]d 섹터의 메타데이터를 이동 중입니다.\x02기본 설정 'base'가 이 마이너의 주소(%[1" +
	"]s) 및 지갑 설정을 포함하도록 업데이트되었습니다.\x02구성 %[1]s를 %[2]s과 비교하세요. 지갑 주소 이외의 마이너 I" +
	"D 사이의 변경 사항은 필요한 실행자를 위한 새로운 최소한의 레이어여야 합니다.\x02'base' 설정이 이 lotus-miner" +
	"의 config.toml과 유사하게 만들어졌습니다.\x04\x00\x01 *\x02레이어 %[1]s가 생성되었습니다.\x04" +
	"\x00\x01 \x22\x02구성 파일을 사용하려면:\x02Curio를 실행하려면: 기계 또는 cgroup 격리를 사용하여 다음" +
	" 명령을 사용하세요 (예제 레이어 선택과 함께):"

var zhIndex = []uint32{ // 139 elements
	// Entry 0 - 1F
	0x00000000, 0x00000033, 0x0000008b, 0x00000134,
	0x0000017c, 0x000001cb, 0x000001e4, 0x000001f1,
	0x00000211, 0x0000022a, 0x00000240, 0x0000025d,
	0x000002bb, 0x000002db, 0x000002ff, 0x00000323,
	0x00000350, 0x00000374, 0x000003a6, 0x000003c0,
	0x000003e6, 0x00000453, 0x00000494, 0x000004c7,
	0x000004e3, 0x00000528, 0x00000545, 0x0000056e,
	0x0000058c, 0x000005c0, 0x000005d0, 0x000005dd,
	// Entry 20 - 3F
	0x000005ed, 0x00000626, 0x0000067a, 0x000006a7,
	0x000006f6, 0x00000731, 0x00000766, 0x00000770,
	0x00000794, 0x000007b2, 0x000007d6, 0x000007f4,
	0x00000812, 0x00000847, 0x0000085a, 0x00000869,
	0x000008c3, 0x00000900, 0x00000928, 0x00000987,
	0x000009d7, 0x00000a04, 0x00000a19, 0x00000a64,
	0x00000a94, 0x00000a9b, 0x00000ac5, 0x00000ae9,
	0x00000b2d, 0x00000b5f, 0x00000ba8, 0x00000bbb,
	// Entry 40 - 5F
	0x00000bd5, 0x00000bf4, 0x00000c19, 0x00000c30,
	0x00000c44, 0x00000c5b, 0x00000c6f, 0x00000ca0,
	0x00000cc5, 0x00000cdb, 0x00000ceb, 0x00000d05,
	0x00000d19, 0x00000d2c, 0x00000d33, 0x00000d3a,
	0x00000d40, 0x00000d46, 0x00000d65, 0x00000d85,
	0x00000da5, 0x00000dbf, 0x00000ddc, 0x00000e0d,
	0x00000e26, 0x00000e4f, 0x00000edc, 0x00000f08,
	0x00000f43, 0x00000f63, 0x00000f94, 0x00000fc7,
	// Entry 60 - 7F
	0x00000ff4, 0x00001015, 0x0000103b, 0x00001095,
	0x000010a4, 0x000010b3, 0x000010c5, 0x000010d4,
	0x000010e6, 0x00001105, 0x0000113d, 0x00001162,
	0x00001172, 0x00001190, 0x0000119d, 0x000011c9,
	0x00001222, 0x00001260, 0x0000128d, 0x000012b0,
	0x000012dc, 0x00001302, 0x0000131f, 0x0000133e,
	0x00001367, 0x0000137b, 0x00001392, 0x000013a9,
	0x000013c4, 0x000013f5, 0x00001440, 0x0000144d,
	// Entry 80 - 9F
	0x0000145a, 0x00001487, 0x000014ab, 0x000014e0,
	0x0000150a, 0x0000155b, 0x000015dd, 0x00001624,
	0x0000163e, 0x00001656, 0x000016ad,
} // Size: 580 bytes

const zhData string = "" + // Size: 5805 bytes
	"\x04\x00\x01 .\x02使用箭头键进行导航：↓ ↑ → ←\x02此交互式工具将创建一个新的矿工角色，并为其创建基本配置层。\x02" +
	"该过程部分幂等。一旦创建了新的矿工角色，并且随后的步骤失败，用户需要运行 'curio config new-cluster < 矿工 ID" +
	" >' 来完成配置。\x02这个交互式工具可以在5分钟内将lotus-miner迁移到Curio。\x02每一步都需要您的确认，并且可以撤销。随" +
	"时按Ctrl+C退出。\x02在终端中按下Ctrl+C\x02我想要：\x02从现有的 Lotus-Miner 迁移\x02创建一个新的矿工" +
	"\x02中止剩余步骤。\x02Lotus-Miner到Curio迁移。\x02由于 shell %[1]s 不是 BASH 或 ZSH，因此未将" +
	"数据库变量添加到 RC 文件中。\x02获取用户主目录时出错:\x02打开文件 %[1]s 时出错: %[2]s\x02读取文件 %[1]s" +
	" 时出错: %[2]s\x02以写入模式打开文件 %[1]s 时出错:\x02写入文件 %[1]s 时出错: %[2]s\x02无法将写入内容刷" +
	"新到文件 %[1]s: %[2]s\x02重试中.......(%[1]d/5)\x04\x00\x01 !\x02尝试使用%[1]s的网页" +
	"界面\x02执行 'curio service-setup' 以在此节点上设置 Curio 服务，并在其他节点上执行相同操作\x02如果适用" +
	"，您现在可以迁移您的市场节点(%[1]s)。\x02更多信息请访问 http://docs.curiostorage.org\x02新矿工初" +
	"始化完成。\x02将 lotus-miner config.toml 迁移到 Curio 的数据库配置中。\x02获取 API 时出错：%[" +
	"1]s\x02无法获取FullNode的API信息：%[1]w\x02获取令牌时出错：%[1]s\x02发现无法迁移的扇区。您想要继续吗？" +
	"\x02是的，继续\x02不，中止\x02中止迁移。\x02保存配置到层时出错：%[1]s。正在中止迁移\x02Curio 团队希望改进您使用的" +
	"软件。告诉团队您正在使用 `%[1]s`。\x02选择您想与Curio团队分享的内容。\x02个人数据：矿工 ID，Curio 版本，链（%" +
	"[1]s 或 %[2]s）。签名。\x02聚合-匿名：版本，链和矿工算力（分桶）。\x02提示：我是在任何链上运行 Curio 的人。\x02没" +
	"有。\x02获取矿工功率时出错：%[1]s\x02整理消息时出错：%[1]s\x02获取矿工信息时出错：%[1]s\x02签署消息时出错：%" +
	"[1]s\x02发送消息时出错：%[1]s\x04\x00\x01 0\x02发送消息时出错：状态%[1]s，消息：\x02消息已发送。\x04" +
	"\x00\x01 \x0a\x02文档：\x02'%[1]s'层存储通用配置。所有Curio实例都可以在其%[2]s参数中包含它。\x02您可以" +
	"添加其他层进行每台机器的配置更改。\x02Filecoin %[1]s 频道：%[2]s 和 %[3]s\x02通过冗余增加可靠性：使用至少" +
	"后层启动多台机器：'curio run --layers=post'\x02一个数据库可以服务多个矿工ID：为每个lotus-miner运行" +
	"迁移。\x02已连接到Yugabyte。模式是当前的。\x02已连接到Yugabyte\x02开始之前，请确保您的密封管道已排空并关闭lot" +
	"us-miner。\x02选择您的lotus-miner配置目录的位置？\x02其他\x02输入%[1]s使用的配置目录的路径\x04\x00" +
	"\x01 \x1f\x02未提供路径，放弃迁移\x02无法读取提供的目录中的config.toml文件，错误：%[1]s\x02无法从目录创建r" +
	"epo：%[1]s。 中止迁移\x02无法锁定矿工repo。 您的矿工必须停止：%[1]s\x0a 中止迁移\x02读取矿工配置\x04\x00" +
	"\x01\x0a\x15\x02步骤完成：%[1]s\x02初始化新的矿工角色。\x02输入创建新矿工所需的信息\x02所有者钱包: %[1]s" +
	"\x02工人钱包: %[1]s\x02发送者钱包: %[1]s\x02扇区大小: %[1]s\x02继续验证地址并创建新的矿工角色。\x04" +
	"\x00\x01  \x02矿工创建错误发生: %[1]s\x02输入所有者地址\x02未提供地址\x02解析地址失败: %[1]s\x02输入" +
	" %[1]s 地址\x02选择扇区大小\x0264 GiB\x0232 GiB\x028 MiB\x022 KiB\x04\x00\x01 " +
	"\x1a\x02扇区选择失败: %[1]s\x02解析扇区大小失败: %[1]s\x02创建矿工角色失败: %[1]s\x02矿工 %[1]s " +
	"创建成功\x02无法访问数据库: %[1]s\x02连接到完整节点 API 时发生错误: %[1]s\x02预初始化步骤完成\x02生成密码" +
	"的随机字节失败: %[1]s\x02请不要再次运行引导设置，因为矿工创建不是幂等的。 您需要运行 'curio config new-clu" +
	"ster %[1]s' 来完成配置。\x02无法获取 FullNode 的 API 信息: %[1]w\x02无法验证来自守护进程节点的授权令牌" +
	": %[1]s\x02无法生成默认配置: %[1]s\x02无法将 'base' 配置层插入数据库: %[1]s\x02配置 'base' 已更" +
	"新以包含此矿工的地址\x02从数据库加载基本配置失败：%[1]s\x02解析基本配置失败：%[1]s\x02重新生成基本配置失败: %[1]" +
	"s\x02输入连接到您的Yugabyte数据库安装的信息（https://download.yugabyte.com/）\x02主机：%[1]s" +
	"\x02端口：%[1]s\x02用户名：%[1]s\x02密码：%[1]s\x02数据库：%[1]s\x02继续连接和更新架构。\x04\x00" +
	"\x01 3\x02发生数据库配置错误，放弃迁移：%[1]s\x02输入Yugabyte数据库主机（S）\x02未提供主机\x02输入Yugab" +
	"yte数据库 %[1]s\x02未提供值\x02连接到Yugabyte数据库时出错：%[1]s\x02此交互式工具创建/替换 Curio 服务文" +
	"件并为其创建基本的 env 文件。\x02服务文件 %[1]s 已存在于 %[2]s，未做任何更改。\x02检查 %[1]s 的服务文件时出" +
	"错: %[2]s\x02写入服务文件时出错: %[1]s\x02服务文件 %[1]s 已成功创建于 %[2]s\x02重新加载 system" +
	"d 时出错: %[1]s\x02启用服务时出错: %[1]s\x04\x00\x01\x0a\x1a\x02服务 %[1]s 已启用。\x02输" +
	"入信息以配置您的 Curio 节点\x02CURIO_LAYERS: %[1]s\x02CURIO_REPO_PATH: %[1]s\x02" +
	"CURIO_NODE_NAME: %[1]s\x02继续更新 env 文件。\x04\x00\x01 ,\x02发生环境配置错误，放弃中: %[" +
	"1]s\x02输入此节点要使用的配置层名称。默认情况下已包含 Base\x02未提供层\x02输入 %[1]s\x02打开或创建文件 %[1]s" +
	" 时出错: %[2]s\x02写入文件 %[1]s 时出错: %[2]s\x02服务环境文件 /etc/curio.env 已成功创建。\x02" +
	"正在迁移%[1]d个扇区的元数据。\x02'base'配置已更新，包括该矿工的地址（%[1]s）及其钱包设置。\x02比较配置%[1]s和%" +
	"[2]s。矿工ID之间除了钱包地址的变化应该是需要的运行者的一个新的、最小的层。\x02'base'配置已创建，以类似于这个lotus-mine" +
	"r的config.toml。\x04\x00\x01 \x15\x02层%[1]s已创建。\x04\x00\x01 \x13\x02要使用配置：" +
	"\x02运行Curio：使用机器或cgroup隔离，使用命令（附带示例层选择）："

	// Total table size 22160 bytes (21KiB); checksum: 7C0037F2
