// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"ko": &dictionary{index: koIndex, data: koData},
		"zh": &dictionary{index: zhIndex, data: zhData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"(debug tool) Copy LM sector metadata into Curio DB":                           93,
	"(for init) limit storage space for sectors (expensive for very large paths!)": 110,
	"(for init) path weight":                    107,
	"(for init) use path for long-term storage": 109,
	"(for init) use path for sealing":           108,
	"--machine flag in cli command should point to the node where storage to redeclare is attached": 120,
	"1278 (3.5 years)":          92,
	"2 KiB":                     218,
	"32 GiB":                    216,
	"64 GiB":                    215,
	"8 MiB":                     217,
	"<sector>":                  62,
	"Aborting migration.":       156,
	"Aborting remaining steps.": 153,
	"Add URL to fetch data for offline deals":                          63,
	"Additional info is at http://docs.curiostorage.org":               161,
	"Address to listen for the GUI on":                                 85,
	"Aggregate-Anonymous: version, chain, and Miner power (bucketed).": 174,
	"Analyze and display the layout of batch sealer threads":           1,
	"Analyze and display the layout of batch sealer threads on your CPU.\n\nIt provides detailed information about CPU utilization for batch sealing operations, including core allocation, thread\ndistribution for different batch sizes.": 2,
	"CSV file location to use for multiple deal input. Each line in the file should be in the format 'uuid,raw size,url,header1,header2...'":                                                                                                 64,
	"Cannot reach the DB: %s": 223,
	"Cannot read the config.toml file in the provided directory, Error: %s": 197,
	"Check data integrity in unsealed sector files":                         142,
	"Collection of debugging utilities":                                     131,
	"Command separated list of hostnames for yugabyte cluster":              49,
	"Compare the configurations %s to %s. Changes between the miner IDs other than wallet addreses should be a new, minimal layer for runners that need it.": 251,
	"Compute WindowPoSt for performance and configuration testing.":                                                                                          126,
	"Compute a proof-of-spacetime for a sector (requires the sector to be pre-sealed). These will not send to the chain.":                                    122,
	"Configuration 'base' was created to resemble this lotus-miner's config.toml .":                                                                          252,
	"Configuration 'base' was updated to include this miner's address":                                                                                       232,
	"Configuration 'base' was updated to include this miner's address (%s) and its wallet setup.":                                                            250,
	"Connected to Yugabyte":                                                          191,
	"Connected to Yugabyte. Schema is current.":                                      190,
	"Continue to connect and update schema.":                                         242,
	"Continue to verify the addresses and create a new miner actor.":                 208,
	"Cordon a machine, set it to maintenance mode":                                   36,
	"Could not create repo from directory: %s. Aborting migration":                   198,
	"Could not lock miner repo. Your miner must be stopped: %s\n Aborting migration": 199,
	"Create a check task for a specific sector, wait for its completion, and output the result.\n   <miner-id>: The storage provider ID\n   <sector-number>: The sector number": 143,
	"Create a new miner": 152,
	"Create a new offline verified DDO deal for Curio":          70,
	"Create new configuration for a new cluster":                34,
	"Ctrl+C pressed in Terminal":                                149,
	"Custom `HEADER` to include in the HTTP request":            65,
	"Database config error occurred, abandoning migration: %s ": 243,
	"Database: %s":    241,
	"Documentation: ": 184,
	"Each step needs your confirmation and can be reversed. Press Ctrl+C to exit at any time.": 148,
	"Enable load balancing for connecting to the Postgres database in Yugabyte cluster":        55,
	"Enter %s address":                    213,
	"Enter the Yugabyte database %s":      246,
	"Enter the Yugabyte database host(s)": 244,
	"Enter the info to connect to your Yugabyte database installation (https://download.yugabyte.com/)": 236,
	"Enter the info to create a new miner":                             203,
	"Enter the owner address":                                          210,
	"Enter the path to the configuration directory used by %s":         195,
	"Error connecting to Yugabyte database: %s":                        248,
	"Error connecting to full node API: %s":                            224,
	"Error getting API: %s":                                            164,
	"Error getting miner info: %s":                                     179,
	"Error getting miner power: %s":                                    177,
	"Error getting token: %s":                                          166,
	"Error marshalling message: %s":                                    178,
	"Error saving config to layer: %s. Aborting Migration":             170,
	"Error sending message: %s":                                        181,
	"Error sending message: Status %s, Message: ":                      182,
	"Error signing message: %s":                                        180,
	"Error writing file: %s":                                           157,
	"Execute cli commands":                                             6,
	"Failed to create the miner actor: %s":                             221,
	"Failed to generate default config: %s":                            230,
	"Failed to generate random bytes for secret: %s":                   226,
	"Failed to get API info for FullNode: %w":                          228,
	"Failed to insert 'base' config layer in database: %s":             231,
	"Failed to load base config from database: %s":                     233,
	"Failed to parse base config: %s":                                  234,
	"Failed to parse sector size: %s":                                  220,
	"Failed to parse the address: %s":                                  212,
	"Failed to regenerate base config: %s":                             235,
	"Failed to verify the auth token from daemon node: %s":             229,
	"Fetch proving parameters":                                         57,
	"Filecoin %s channels: %s and %s":                                  187,
	"Filecoin decentralized storage network provider":                  46,
	"Filter by storage provider ID":                                    138,
	"Filter events by actor address; lists all if not specified":       97,
	"Filter events by sector number; requires --actor to be specified": 98,
	"For more servers, make /etc/curio.env with the curio.env database env and add the CURIO_LAYERS env to assign purposes.": 159,
	"Generate a supra_seal configuration": 3,
	"Generate a supra_seal configuration for a given batch size.\n\nThis command outputs a configuration expected by SupraSeal. Main purpose of this command is for debugging and testing.\nThe config can be used directly with SupraSeal binaries to test it without involving Curio.": 4,
	"Get Curio node info": 39,
	"Get a config layer by name. You may want to pipe the output to a file, or use 'less'": 19,
	"Get information about unsealed data":                                                  136,
	"Hint: I am someone running Curio on whichever chain.":                                 175,
	"Host: %s":                               237,
	"How long to commit sectors for":         91,
	"I want to:":                             150,
	"Ignore sectors that cannot be migrated": 95,
	"Increase reliability using redundancy: start multiple machines with at-least the post layer: 'curio run --layers=post'": 188,
	"Individual Data: Miner ID, Curio version, chain (%s or %s). Signed.":                                                    173,
	"Initializing a new miner actor.": 202,
	"Interpret stacked config layers by this version of curio, with system-generated comments.": 23,
	"Layer %s created. ":                                                 253,
	"Limit output to the last N events":                                  99,
	"List config layers present in the DB.":                              21,
	"List data from the sectors_unseal_pipeline and sectors_meta tables": 137,
	"List log systems":                                                   41,
	"List pipeline events":                                               96,
	"Lotus-Miner to Curio Migration.":                                    154,
	"Manage logging":                                                     40,
	"Manage node config by layers. The layer 'base' will always be applied at Curio start-up.": 13,
	"Manage the sealing pipeline":       86,
	"Manage unsealed data":              135,
	"Math Utils":                        0,
	"Message sent.":                     183,
	"Migrate from existing Lotus-Miner": 151,
	"Migrating lotus-miner config.toml to Curio in-database configuration.":                 163,
	"Migrating metadata for %d sectors.":                                                    249,
	"Miner %s created successfully":                                                         222,
	"Miner creation error occurred: %s ":                                                    209,
	"Moves funds from the deal collateral wallet into escrow with the storage market actor": 67,
	"Name of the Postgres database in Yugabyte cluster":                                     50,
	"New Miner initialization complete.":                                                    162,
	"No address provided":                                                                   211,
	"No host provided":                                                                      245,
	"No path provided, abandoning migration ":                                               196,
	"No value provided":                                                                     247,
	"No, abort":                                                                             169,
	"Note: This command is intended to be used to verify PoSt compute performance.\nIt will not send any messages to the chain. Since it can compute any deadline, output may be incorrectly timed for the chain.": 127,
	"Nothing.":                   176,
	"Number of sectors to start": 90,
	"One database can serve multiple miner IDs: Run a migration for each lotus-miner.": 189,
	"Other":                              194,
	"Output file path (default: stdout)": 139,
	"Owner Wallet: %s":                   204,
	"Password for connecting to the Postgres database in Yugabyte cluster": 52,
	"Password: %s":       240,
	"Path to miner repo": 94,
	"Please do not run guided-setup again as miner creation is not idempotent. You need to run 'curio config new-cluster %s' to finish the configuration": 227,
	"Port for connecting to the Cassandra database in Yugabyte cluster":                                                                                   54,
	"Port for connecting to the Postgres database in Yugabyte cluster":                                                                                    53,
	"Port: %s":                                              238,
	"Pre-initialization steps complete":                     225,
	"Print default node config":                             14,
	"Provides a sample of CIDs from an indexed piece":       10,
	"Read Miner Config":                                     200,
	"Remove a named config layer.":                          22,
	"Remove unsealed copies of sector containing this deal": 72,
	"SP ID to compute WindowPoSt for":                       125,
	"Sector Size: %s":                                       207,
	"Sector selection failed: %s ":                          219,
	"Sectors can be stored across many filesystem paths. These\ncommands provide ways to manage the storage a Curio node will use to store sectors\nlong term for proving (references as 'store') as well as how sectors will be\nstored while moving through the sealing pipeline (references as 'seal').": 102,
	"Select the Sector Size":                                           214,
	"Select the location of your lotus-miner config directory?":        193,
	"Select what you want to share with the Curio team.":               172,
	"Sender Wallet: %s":                                                206,
	"Set a config layer or the base by providing a filename or stdin.": 16,
	"Set log level": 42,
	"Set the log level for logging systems:\n\n   The system flag can be specified multiple times.\n\n   eg) log set-level --system chain --system chainxchg debug\n\n   Available Levels:\n   debug\n   info\n   warn\n   error\n\n   Environment Variables:\n   GOLOG_LOG_LEVEL - Default log level for all log systems\n   GOLOG_LOG_FMT   - Change output log format (json, nocolor)\n   GOLOG_FILE      - Write logs to file\n   GOLOG_OUTPUT    - Specify whether to output to file, stderr, stdout or a combination, i.e. file+stderr\n": 44,
	"Set the target unseal state for a sector": 140,
	"Set the target unseal state for a specific sector.\n   <miner-id>: The storage provider ID\n   <sector-number>: The sector number\n   <target-state>: The target state (true, false, or none)\n\n   The unseal target state indicates to curio how an unsealed copy of the sector should be maintained.\n\t   If the target state is true, curio will ensure that the sector is unsealed.\n\t   If the target state is false, curio will ensure that there is no unsealed copy of the sector.\n\t   If the target state is none, curio will not change the current state of the sector.\n\n   Currently when the curio will only start new unseal processes when the target state changes from another state to true.\n\n   When the target state is false, and an unsealed sector file exists, the GC mark step will create a removal mark\n   for the unsealed sector file. The file will only be removed after the removal mark is accepted.\n": 141,
	"Specify actor address for the deal":                 71,
	"Specify actor address to start sealing sectors for": 60,
	"Specify wallet address to send the funds from":      69,
	"Start Curio web interface":                          83,
	"Start a Curio process":                              75,
	"Start an instance of Curio web interface. \n\tThis creates the 'web' layer if it does not exist, then calls run with that layer.": 84,
	"Start new sealing operations manually":                      87,
	"Start sealing new CC sectors":                               89,
	"Start sealing sectors for all actors now (not on schedule)": 88,
	"Step Complete: %s\n":                                        201,
	"Stop a running Curio process":                               100,
	"Storage can be attached to a Curio node using this command. The storage volume\nlist is stored local to the Curio node in storage.json set in curio run. We do not\nrecommend manually modifying this value without further understanding of the\nstorage system.\n\nEach storage volume contains a configuration file which describes the\ncapabilities of the volume. When the '--init' flag is provided, this file will\nbe created using the additional flags.\n\nWeight\nA high weight value means data will be more likely to be stored in this path\n\nSeal\nData for the sealing process will be stored here\n\nStore\nFinalized sectors that will be moved here for long term storage and be proven\nover time\n   ": 105,
	"Test the windowpost scheduler by running it on the next available curio. If tasks fail all retries, you will need to ctrl+c to exit.":                                                               123,
	"The '%s' layer stores common configuration. All curio instances can include it in their %s argument.":                                                                                               185,
	"The Curio team wants to improve the software you use. Tell the team you're using `%s`.":                                                                                                             171,
	"This interactive tool creates a new miner actor and creates the basic configuration layer for it.":                                                                                                  145,
	"This interactive tool migrates lotus-miner to Curio in 5 minutes.":                                                                                                                                  147,
	"This process is partially idempotent. Once a new miner actor has been created and subsequent steps fail, the user need to run 'curio config new-cluster < miner ID >' to finish the configuration.": 146,
	"To run Curio: With machine or cgroup isolation, use the command (with example layer selection):":                                                                                                    255,
	"To start, ensure your sealing pipeline is drained and shut-down lotus-miner.":                                                                                                                       192,
	"To work with the config: ":                                            254,
	"Tool Box for Curio":                                                   132,
	"Try the web interface with %s ":                                       158,
	"Uncordon a machine, resume scheduling":                                37,
	"Unmigratable sectors found. Do you want to continue?":                 167,
	"Update data for messages in wait queue":                               134,
	"Updated DB with message data missing from chain node":                 133,
	"Use synthetic PoRep":                                                  61,
	"Use the arrow keys to navigate: ↓ ↑ → ← ":                             144,
	"Username for connecting to the Postgres database in Yugabyte cluster": 51,
	"Username: %s":                                    239,
	"Utility functions for testing":                   121,
	"Wait for Curio api to come online":               8,
	"Where should we save your database config file?": 155,
	"Worker Wallet: %s":                               205,
	"Yes, continue":                                   168,
	"You can add other layers for per-machine configuration changes.":             186,
	"You can now migrate your market node (%s), if applicable.":                   160,
	"Zen3 and later supports two sectors per thread, set to false for older CPUs": 5,
	"[SP actor address...]":           35,
	"[deadline index]":                128,
	"[layer name]":                    27,
	"[level]":                         43,
	"[miner address] [sector number]": 117,
	"[path]":                          104,
	"[sectorSize]":                    58,
	"`URL` to send the request to":    66,
	"a layer's file name":             17,
	"a list of layers to be interpreted as the final config":                             24,
	"allow overwrite of existing layer if source is a different layer":                   30,
	"attach local storage path":                                                          103,
	"comma or space separated list of layers to be interpreted (base is always applied)": 25,
	"could not get API info for FullNode: %w":                                            165,
	"custom node name":                                                82,
	"deadline to compute WindowPoSt for ":                             124,
	"depends on output being a TTY":                                   48,
	"detach local storage path":                                       113,
	"do not interpret source layer":                                   32,
	"don't check full-node sync status":                               78,
	"don't comment default values":                                    15,
	"duration to wait till fail":                                      9,
	"edit a config layer":                                             26,
	"editor to use":                                                   28,
	"enables very verbose mode, useful for debugging the CLI":         56,
	"find sector in the storage system":                               116,
	"generate ipni chunks from a file":                                38,
	"generate vanilla proof for a sector":                             118,
	"host address and port the gui will listen on":                    77,
	"host address and port the worker api will listen on":             76,
	"indicates that deal index should not be announced to the IPNI":   73,
	"initialize the path first":                                       106,
	"layer name":                                                      20,
	"limit to log system":                                             45,
	"list local storage paths":                                        114,
	"list of layers to be interpreted (atop defaults). Default: base": 81,
	"machine host:port (curio run --listen address)":                  7,
	"manage open file limit":                                          80,
	"manage sector storage":                                           101,
	"maximum fee in FIL user is willing to pay for this message":      68,
	"only list local storage paths":                                   115,
	"only run init, then return":                                      79,
	"output in json format":                                           12,
	"partition to compute WindowPoSt for":                             130,
	"path group names":                                                111,
	"path groups allowed to pull data from this path (allow all if not specified)": 112,
	"path to json file containing storage config":                                  129,
	"piece-cid": 11,
	"redeclare sectors in a local storage path":               119,
	"save the whole config into the layer, not just the diff": 31,
	"source config layer":                                     29,
	"start epoch by when the deal should be proved by provider on-chain (default: 2 days from now)": 74,
	"start sealing a deal sector early":           59,
	"title of the config layer (req'd for stdin)": 18,
	"true if --source is set":                     33,
	"use color in display output":                 47,
}

var enIndex = []uint32{ // 257 elements
	// Entry 0 - 1F
	0x00000000, 0x0000000b, 0x00000042, 0x00000126,
	0x0000014a, 0x0000025a, 0x000002a6, 0x000002bb,
	0x000002ea, 0x0000030c, 0x00000327, 0x00000357,
	0x00000361, 0x00000377, 0x000003d0, 0x000003ea,
	0x00000407, 0x00000448, 0x0000045c, 0x00000488,
	0x000004dd, 0x000004e8, 0x0000050e, 0x0000052b,
	0x00000585, 0x000005bc, 0x0000060f, 0x00000623,
	0x00000630, 0x0000063e, 0x00000652, 0x00000693,
	// Entry 20 - 3F
	0x000006cb, 0x000006e9, 0x00000701, 0x0000072c,
	0x00000742, 0x0000076f, 0x00000795, 0x000007b6,
	0x000007ca, 0x000007d9, 0x000007ea, 0x000007f8,
	0x00000800, 0x000009fe, 0x00000a12, 0x00000a42,
	0x00000a5e, 0x00000a7c, 0x00000ab5, 0x00000ae7,
	0x00000b2c, 0x00000b71, 0x00000bb2, 0x00000bf4,
	0x00000c46, 0x00000c7e, 0x00000c97, 0x00000ca4,
	0x00000cc6, 0x00000cf9, 0x00000d0d, 0x00000d16,
	// Entry 40 - 5F
	0x00000d3e, 0x00000dc5, 0x00000df4, 0x00000e11,
	0x00000e67, 0x00000ea2, 0x00000ed0, 0x00000f01,
	0x00000f24, 0x00000f5a, 0x00000f98, 0x00000ff6,
	0x0000100c, 0x00001040, 0x0000106d, 0x0000108f,
	0x000010aa, 0x000010c1, 0x00001101, 0x00001112,
	0x0000112c, 0x000011ab, 0x000011cc, 0x000011e8,
	0x0000120e, 0x00001249, 0x00001266, 0x00001281,
	0x000012a0, 0x000012b1, 0x000012e4, 0x000012f7,
	// Entry 60 - 7F
	0x0000131e, 0x00001333, 0x0000136e, 0x000013af,
	0x000013d1, 0x000013ee, 0x00001404, 0x00001527,
	0x00001541, 0x00001548, 0x000017f8, 0x00001812,
	0x00001829, 0x00001849, 0x00001873, 0x000018c0,
	0x000018d1, 0x0000191e, 0x00001938, 0x00001951,
	0x0000196f, 0x00001991, 0x000019b1, 0x000019d5,
	0x000019ff, 0x00001a5d, 0x00001a7b, 0x00001aef,
	0x00001b74, 0x00001b9c, 0x00001bbc, 0x00001bfa,
	// Entry 80 - 9F
	0x00001cc6, 0x00001cd7, 0x00001d03, 0x00001d27,
	0x00001d49, 0x00001d5c, 0x00001d91, 0x00001db8,
	0x00001dcd, 0x00001df1, 0x00001e34, 0x00001e52,
	0x00001e75, 0x00001e9e, 0x00002224, 0x00002252,
	0x000022fa, 0x0000232f, 0x00002391, 0x00002454,
	0x00002496, 0x000024ef, 0x0000250a, 0x00002515,
	0x00002537, 0x0000254a, 0x00002564, 0x00002584,
	0x000025b4, 0x000025c8, 0x000025e2, 0x00002608,
	// Entry A0 - BF
	0x0000267f, 0x000026bc, 0x000026ef, 0x00002712,
	0x00002758, 0x00002771, 0x0000279c, 0x000027b7,
	0x000027ec, 0x000027fa, 0x00002804, 0x0000283c,
	0x00002896, 0x000028c9, 0x00002913, 0x00002954,
	0x00002989, 0x00002992, 0x000029b3, 0x000029d4,
	0x000029f4, 0x00002a11, 0x00002a2e, 0x00002a61,
	0x00002a6f, 0x00002a83, 0x00002aee, 0x00002b2e,
	0x00002b57, 0x00002bce, 0x00002c1f, 0x00002c49,
	// Entry C0 - DF
	0x00002c5f, 0x00002cac, 0x00002ce6, 0x00002cec,
	0x00002d28, 0x00002d54, 0x00002d9d, 0x00002ddd,
	0x00002e2e, 0x00002e40, 0x00002e5a, 0x00002e7a,
	0x00002e9f, 0x00002eb3, 0x00002ec8, 0x00002edd,
	0x00002ef0, 0x00002f2f, 0x00002f59, 0x00002f71,
	0x00002f85, 0x00002fa8, 0x00002fbc, 0x00002fd3,
	0x00002fda, 0x00002fe1, 0x00002fe7, 0x00002fed,
	0x00003011, 0x00003034, 0x0000305c, 0x0000307d,
	// Entry E0 - FF
	0x00003098, 0x000030c1, 0x000030e3, 0x00003115,
	0x000031ac, 0x000031d7, 0x0000320f, 0x00003238,
	0x00003270, 0x000032b1, 0x000032e1, 0x00003304,
	0x0000332c, 0x0000338e, 0x0000339a, 0x000033a6,
	0x000033b6, 0x000033c6, 0x000033d6, 0x000033fd,
	0x0000343e, 0x00003462, 0x00003473, 0x00003495,
	0x000034a7, 0x000034d4, 0x000034fa, 0x00003559,
	0x000035f6, 0x00003644, 0x0000365e, 0x0000367c,
	// Entry 100 - 11F
	0x000036dc,
} // Size: 1052 bytes

const enData string = "" + // Size: 14044 bytes
	"\x02Math Utils\x02Analyze and display the layout of batch sealer threads" +
	"\x02Analyze and display the layout of batch sealer threads on your CPU." +
	"\x0a\x0aIt provides detailed information about CPU utilization for batch" +
	" sealing operations, including core allocation, thread\x0adistribution f" +
	"or different batch sizes.\x02Generate a supra_seal configuration\x02Gene" +
	"rate a supra_seal configuration for a given batch size.\x0a\x0aThis comm" +
	"and outputs a configuration expected by SupraSeal. Main purpose of this " +
	"command is for debugging and testing.\x0aThe config can be used directly" +
	" with SupraSeal binaries to test it without involving Curio.\x02Zen3 and" +
	" later supports two sectors per thread, set to false for older CPUs\x02E" +
	"xecute cli commands\x02machine host:port (curio run --listen address)" +
	"\x02Wait for Curio api to come online\x02duration to wait till fail\x02P" +
	"rovides a sample of CIDs from an indexed piece\x02piece-cid\x02output in" +
	" json format\x02Manage node config by layers. The layer 'base' will alwa" +
	"ys be applied at Curio start-up.\x02Print default node config\x02don't c" +
	"omment default values\x02Set a config layer or the base by providing a f" +
	"ilename or stdin.\x02a layer's file name\x02title of the config layer (r" +
	"eq'd for stdin)\x02Get a config layer by name. You may want to pipe the " +
	"output to a file, or use 'less'\x02layer name\x02List config layers pres" +
	"ent in the DB.\x02Remove a named config layer.\x02Interpret stacked conf" +
	"ig layers by this version of curio, with system-generated comments.\x02a" +
	" list of layers to be interpreted as the final config\x02comma or space " +
	"separated list of layers to be interpreted (base is always applied)\x02e" +
	"dit a config layer\x02[layer name]\x02editor to use\x02source config lay" +
	"er\x02allow overwrite of existing layer if source is a different layer" +
	"\x02save the whole config into the layer, not just the diff\x02do not in" +
	"terpret source layer\x02true if --source is set\x02Create new configurat" +
	"ion for a new cluster\x02[SP actor address...]\x02Cordon a machine, set " +
	"it to maintenance mode\x02Uncordon a machine, resume scheduling\x02gener" +
	"ate ipni chunks from a file\x02Get Curio node info\x02Manage logging\x02" +
	"List log systems\x02Set log level\x02[level]\x04\x00\x01\x0a\xf8\x03\x02" +
	"Set the log level for logging systems:\x0a\x0a   The system flag can be " +
	"specified multiple times.\x0a\x0a   eg) log set-level --system chain --s" +
	"ystem chainxchg debug\x0a\x0a   Available Levels:\x0a   debug\x0a   info" +
	"\x0a   warn\x0a   error\x0a\x0a   Environment Variables:\x0a   GOLOG_LOG" +
	"_LEVEL - Default log level for all log systems\x0a   GOLOG_LOG_FMT   - C" +
	"hange output log format (json, nocolor)\x0a   GOLOG_FILE      - Write lo" +
	"gs to file\x0a   GOLOG_OUTPUT    - Specify whether to output to file, st" +
	"derr, stdout or a combination, i.e. file+stderr\x02limit to log system" +
	"\x02Filecoin decentralized storage network provider\x02use color in disp" +
	"lay output\x02depends on output being a TTY\x02Command separated list of" +
	" hostnames for yugabyte cluster\x02Name of the Postgres database in Yuga" +
	"byte cluster\x02Username for connecting to the Postgres database in Yuga" +
	"byte cluster\x02Password for connecting to the Postgres database in Yuga" +
	"byte cluster\x02Port for connecting to the Postgres database in Yugabyte" +
	" cluster\x02Port for connecting to the Cassandra database in Yugabyte cl" +
	"uster\x02Enable load balancing for connecting to the Postgres database i" +
	"n Yugabyte cluster\x02enables very verbose mode, useful for debugging th" +
	"e CLI\x02Fetch proving parameters\x02[sectorSize]\x02start sealing a dea" +
	"l sector early\x02Specify actor address to start sealing sectors for\x02" +
	"Use synthetic PoRep\x02<sector>\x02Add URL to fetch data for offline dea" +
	"ls\x02CSV file location to use for multiple deal input. Each line in the" +
	" file should be in the format 'uuid,raw size,url,header1,header2...'\x02" +
	"Custom `HEADER` to include in the HTTP request\x02`URL` to send the requ" +
	"est to\x02Moves funds from the deal collateral wallet into escrow with t" +
	"he storage market actor\x02maximum fee in FIL user is willing to pay for" +
	" this message\x02Specify wallet address to send the funds from\x02Create" +
	" a new offline verified DDO deal for Curio\x02Specify actor address for " +
	"the deal\x02Remove unsealed copies of sector containing this deal\x02ind" +
	"icates that deal index should not be announced to the IPNI\x02start epoc" +
	"h by when the deal should be proved by provider on-chain (default: 2 day" +
	"s from now)\x02Start a Curio process\x02host address and port the worker" +
	" api will listen on\x02host address and port the gui will listen on\x02d" +
	"on't check full-node sync status\x02only run init, then return\x02manage" +
	" open file limit\x02list of layers to be interpreted (atop defaults). De" +
	"fault: base\x02custom node name\x02Start Curio web interface\x02Start an" +
	" instance of Curio web interface. \x0a\x09This creates the 'web' layer i" +
	"f it does not exist, then calls run with that layer.\x02Address to liste" +
	"n for the GUI on\x02Manage the sealing pipeline\x02Start new sealing ope" +
	"rations manually\x02Start sealing sectors for all actors now (not on sch" +
	"edule)\x02Start sealing new CC sectors\x02Number of sectors to start\x02" +
	"How long to commit sectors for\x021278 (3.5 years)\x02(debug tool) Copy " +
	"LM sector metadata into Curio DB\x02Path to miner repo\x02Ignore sectors" +
	" that cannot be migrated\x02List pipeline events\x02Filter events by act" +
	"or address; lists all if not specified\x02Filter events by sector number" +
	"; requires --actor to be specified\x02Limit output to the last N events" +
	"\x02Stop a running Curio process\x02manage sector storage\x02Sectors can" +
	" be stored across many filesystem paths. These\x0acommands provide ways " +
	"to manage the storage a Curio node will use to store sectors\x0along ter" +
	"m for proving (references as 'store') as well as how sectors will be\x0a" +
	"stored while moving through the sealing pipeline (references as 'seal')." +
	"\x02attach local storage path\x02[path]\x04\x00\x04\x0a   \xa7\x05\x02St" +
	"orage can be attached to a Curio node using this command. The storage vo" +
	"lume\x0alist is stored local to the Curio node in storage.json set in cu" +
	"rio run. We do not\x0arecommend manually modifying this value without fu" +
	"rther understanding of the\x0astorage system.\x0a\x0aEach storage volume" +
	" contains a configuration file which describes the\x0acapabilities of th" +
	"e volume. When the '--init' flag is provided, this file will\x0abe creat" +
	"ed using the additional flags.\x0a\x0aWeight\x0aA high weight value mean" +
	"s data will be more likely to be stored in this path\x0a\x0aSeal\x0aData" +
	" for the sealing process will be stored here\x0a\x0aStore\x0aFinalized s" +
	"ectors that will be moved here for long term storage and be proven\x0aov" +
	"er time\x02initialize the path first\x02(for init) path weight\x02(for i" +
	"nit) use path for sealing\x02(for init) use path for long-term storage" +
	"\x02(for init) limit storage space for sectors (expensive for very large" +
	" paths!)\x02path group names\x02path groups allowed to pull data from th" +
	"is path (allow all if not specified)\x02detach local storage path\x02lis" +
	"t local storage paths\x02only list local storage paths\x02find sector in" +
	" the storage system\x02[miner address] [sector number]\x02generate vanil" +
	"la proof for a sector\x02redeclare sectors in a local storage path\x02--" +
	"machine flag in cli command should point to the node where storage to re" +
	"declare is attached\x02Utility functions for testing\x02Compute a proof-" +
	"of-spacetime for a sector (requires the sector to be pre-sealed). These " +
	"will not send to the chain.\x02Test the windowpost scheduler by running " +
	"it on the next available curio. If tasks fail all retries, you will need" +
	" to ctrl+c to exit.\x04\x00\x01 #\x02deadline to compute WindowPoSt for" +
	"\x02SP ID to compute WindowPoSt for\x02Compute WindowPoSt for performanc" +
	"e and configuration testing.\x02Note: This command is intended to be use" +
	"d to verify PoSt compute performance.\x0aIt will not send any messages t" +
	"o the chain. Since it can compute any deadline, output may be incorrectl" +
	"y timed for the chain.\x02[deadline index]\x02path to json file containi" +
	"ng storage config\x02partition to compute WindowPoSt for\x02Collection o" +
	"f debugging utilities\x02Tool Box for Curio\x02Updated DB with message d" +
	"ata missing from chain node\x02Update data for messages in wait queue" +
	"\x02Manage unsealed data\x02Get information about unsealed data\x02List " +
	"data from the sectors_unseal_pipeline and sectors_meta tables\x02Filter " +
	"by storage provider ID\x02Output file path (default: stdout)\x02Set the " +
	"target unseal state for a sector\x04\x00\x01\x0a\x80\x07\x02Set the targ" +
	"et unseal state for a specific sector.\x0a   <miner-id>: The storage pro" +
	"vider ID\x0a   <sector-number>: The sector number\x0a   <target-state>: " +
	"The target state (true, false, or none)\x0a\x0a   The unseal target stat" +
	"e indicates to curio how an unsealed copy of the sector should be mainta" +
	"ined.\x0a\x09   If the target state is true, curio will ensure that the " +
	"sector is unsealed.\x0a\x09   If the target state is false, curio will e" +
	"nsure that there is no unsealed copy of the sector.\x0a\x09   If the tar" +
	"get state is none, curio will not change the current state of the sector" +
	".\x0a\x0a   Currently when the curio will only start new unseal processe" +
	"s when the target state changes from another state to true.\x0a\x0a   Wh" +
	"en the target state is false, and an unsealed sector file exists, the GC" +
	" mark step will create a removal mark\x0a   for the unsealed sector file" +
	". The file will only be removed after the removal mark is accepted.\x02C" +
	"heck data integrity in unsealed sector files\x02Create a check task for " +
	"a specific sector, wait for its completion, and output the result.\x0a  " +
	" <miner-id>: The storage provider ID\x0a   <sector-number>: The sector n" +
	"umber\x04\x00\x01 0\x02Use the arrow keys to navigate: ↓ ↑ → ←\x02This i" +
	"nteractive tool creates a new miner actor and creates the basic configur" +
	"ation layer for it.\x02This process is partially idempotent. Once a new " +
	"miner actor has been created and subsequent steps fail, the user need to" +
	" run 'curio config new-cluster < miner ID >' to finish the configuration" +
	".\x02This interactive tool migrates lotus-miner to Curio in 5 minutes." +
	"\x02Each step needs your confirmation and can be reversed. Press Ctrl+C " +
	"to exit at any time.\x02Ctrl+C pressed in Terminal\x02I want to:\x02Migr" +
	"ate from existing Lotus-Miner\x02Create a new miner\x02Aborting remainin" +
	"g steps.\x02Lotus-Miner to Curio Migration.\x02Where should we save your" +
	" database config file?\x02Aborting migration.\x02Error writing file: %[1" +
	"]s\x04\x00\x01 !\x02Try the web interface with %[1]s\x02For more servers" +
	", make /etc/curio.env with the curio.env database env and add the CURIO_" +
	"LAYERS env to assign purposes.\x02You can now migrate your market node (" +
	"%[1]s), if applicable.\x02Additional info is at http://docs.curiostorage" +
	".org\x02New Miner initialization complete.\x02Migrating lotus-miner conf" +
	"ig.toml to Curio in-database configuration.\x02Error getting API: %[1]s" +
	"\x02could not get API info for FullNode: %[1]w\x02Error getting token: %" +
	"[1]s\x02Unmigratable sectors found. Do you want to continue?\x02Yes, con" +
	"tinue\x02No, abort\x02Error saving config to layer: %[1]s. Aborting Migr" +
	"ation\x02The Curio team wants to improve the software you use. Tell the " +
	"team you're using `%[1]s`.\x02Select what you want to share with the Cur" +
	"io team.\x02Individual Data: Miner ID, Curio version, chain (%[1]s or %[" +
	"2]s). Signed.\x02Aggregate-Anonymous: version, chain, and Miner power (b" +
	"ucketed).\x02Hint: I am someone running Curio on whichever chain.\x02Not" +
	"hing.\x02Error getting miner power: %[1]s\x02Error marshalling message: " +
	"%[1]s\x02Error getting miner info: %[1]s\x02Error signing message: %[1]s" +
	"\x02Error sending message: %[1]s\x04\x00\x01 .\x02Error sending message:" +
	" Status %[1]s, Message:\x02Message sent.\x04\x00\x01 \x0f\x02Documentati" +
	"on:\x02The '%[1]s' layer stores common configuration. All curio instance" +
	"s can include it in their %[2]s argument.\x02You can add other layers fo" +
	"r per-machine configuration changes.\x02Filecoin %[1]s channels: %[2]s a" +
	"nd %[3]s\x02Increase reliability using redundancy: start multiple machin" +
	"es with at-least the post layer: 'curio run --layers=post'\x02One databa" +
	"se can serve multiple miner IDs: Run a migration for each lotus-miner." +
	"\x02Connected to Yugabyte. Schema is current.\x02Connected to Yugabyte" +
	"\x02To start, ensure your sealing pipeline is drained and shut-down lotu" +
	"s-miner.\x02Select the location of your lotus-miner config directory?" +
	"\x02Other\x02Enter the path to the configuration directory used by %[1]s" +
	"\x04\x00\x01 '\x02No path provided, abandoning migration\x02Cannot read " +
	"the config.toml file in the provided directory, Error: %[1]s\x02Could no" +
	"t create repo from directory: %[1]s. Aborting migration\x02Could not loc" +
	"k miner repo. Your miner must be stopped: %[1]s\x0a Aborting migration" +
	"\x02Read Miner Config\x04\x00\x01\x0a\x15\x02Step Complete: %[1]s\x02Ini" +
	"tializing a new miner actor.\x02Enter the info to create a new miner\x02" +
	"Owner Wallet: %[1]s\x02Worker Wallet: %[1]s\x02Sender Wallet: %[1]s\x02S" +
	"ector Size: %[1]s\x02Continue to verify the addresses and create a new m" +
	"iner actor.\x04\x00\x01 %\x02Miner creation error occurred: %[1]s\x02Ent" +
	"er the owner address\x02No address provided\x02Failed to parse the addre" +
	"ss: %[1]s\x02Enter %[1]s address\x02Select the Sector Size\x0264 GiB\x02" +
	"32 GiB\x028 MiB\x022 KiB\x04\x00\x01 \x1f\x02Sector selection failed: %[" +
	"1]s\x02Failed to parse sector size: %[1]s\x02Failed to create the miner " +
	"actor: %[1]s\x02Miner %[1]s created successfully\x02Cannot reach the DB:" +
	" %[1]s\x02Error connecting to full node API: %[1]s\x02Pre-initialization" +
	" steps complete\x02Failed to generate random bytes for secret: %[1]s\x02" +
	"Please do not run guided-setup again as miner creation is not idempotent" +
	". You need to run 'curio config new-cluster %[1]s' to finish the configu" +
	"ration\x02Failed to get API info for FullNode: %[1]w\x02Failed to verify" +
	" the auth token from daemon node: %[1]s\x02Failed to generate default co" +
	"nfig: %[1]s\x02Failed to insert 'base' config layer in database: %[1]s" +
	"\x02Configuration 'base' was updated to include this miner's address\x02" +
	"Failed to load base config from database: %[1]s\x02Failed to parse base " +
	"config: %[1]s\x02Failed to regenerate base config: %[1]s\x02Enter the in" +
	"fo to connect to your Yugabyte database installation (https://download.y" +
	"ugabyte.com/)\x02Host: %[1]s\x02Port: %[1]s\x02Username: %[1]s\x02Passwo" +
	"rd: %[1]s\x02Database: %[1]s\x02Continue to connect and update schema." +
	"\x04\x00\x01 <\x02Database config error occurred, abandoning migration: " +
	"%[1]s\x02Enter the Yugabyte database host(s)\x02No host provided\x02Ente" +
	"r the Yugabyte database %[1]s\x02No value provided\x02Error connecting t" +
	"o Yugabyte database: %[1]s\x02Migrating metadata for %[1]d sectors.\x02C" +
	"onfiguration 'base' was updated to include this miner's address (%[1]s) " +
	"and its wallet setup.\x02Compare the configurations %[1]s to %[2]s. Chan" +
	"ges between the miner IDs other than wallet addreses should be a new, mi" +
	"nimal layer for runners that need it.\x02Configuration 'base' was create" +
	"d to resemble this lotus-miner's config.toml .\x04\x00\x01 \x15\x02Layer" +
	" %[1]s created.\x04\x00\x01 \x19\x02To work with the config:\x02To run C" +
	"urio: With machine or cgroup isolation, use the command (with example la" +
	"yer selection):"

var koIndex = []uint32{ // 257 elements
	// Entry 0 - 1F
	0x00000000, 0x00000014, 0x0000004e, 0x00000168,
	0x00000181, 0x000002b1, 0x00000328, 0x0000033a,
	0x0000036e, 0x000003aa, 0x000003cf, 0x00000405,
	0x00000410, 0x00000429, 0x00000498, 0x000004b4,
	0x000004d9, 0x0000052e, 0x00000549, 0x00000576,
	0x000005f5, 0x00000606, 0x0000062c, 0x00000659,
	0x000006b8, 0x000006e7, 0x00000742, 0x0000075a,
	0x0000076d, 0x00000781, 0x00000799, 0x000007e3,
	// Entry 20 - 3F
	0x00000822, 0x00000847, 0x00000869, 0x00000896,
	0x000008ac, 0x000008e2, 0x00000914, 0x00000934,
	0x00000955, 0x00000963, 0x0000097b, 0x00000990,
	0x00000999, 0x00000bc1, 0x00000bdf, 0x00000c13,
	0x00000c3b, 0x00000c53, 0x00000ca2, 0x00000cde,
	0x00000d3b, 0x00000d94, 0x00000de7, 0x00000e3b,
	0x00000ea8, 0x00000eeb, 0x00000f0c, 0x00000f1c,
	0x00000f45, 0x00000f6e, 0x00000f82, 0x00000f8b,
	// Entry 40 - 5F
	0x00000fc1, 0x00001056, 0x00001089, 0x000010a0,
	0x000010fa, 0x00001147, 0x0000116d, 0x000011bd,
	0x000011f3, 0x0000124a, 0x00001295, 0x0000131e,
	0x00001338, 0x00001375, 0x000013a8, 0x000013d3,
	0x000013f2, 0x0000140e, 0x0000144d, 0x0000146c,
	0x0000148d, 0x0000152f, 0x0000154e, 0x0000156c,
	0x00001592, 0x000015d9, 0x000015f5, 0x0000160a,
	0x00001625, 0x00001633, 0x00001676, 0x00001691,
	// Entry 60 - 7F
	0x000016b4, 0x000016d5, 0x00001736, 0x00001772,
	0x000017a2, 0x000017ca, 0x000017e5, 0x00001931,
	0x00001953, 0x0000195c, 0x00001c95, 0x00001cb0,
	0x00001cd0, 0x00001cf7, 0x00001d25, 0x00001d8d,
	0x00001da2, 0x00001e0a, 0x00001e2c, 0x00001e4e,
	0x00001e73, 0x00001e9e, 0x00001ec1, 0x00001eea,
	0x00001f23, 0x00001f94, 0x00001fb5, 0x0000202b,
	0x000020d5, 0x000020f9, 0x0000211b, 0x00002154,
	// Entry 80 - 9F
	0x00002246, 0x00002259, 0x00002297, 0x000022b9,
	0x000022d7, 0x000022eb, 0x00002353, 0x0000238f,
	0x000023ad, 0x000023df, 0x00002426, 0x0000244d,
	0x0000247d, 0x000024a6, 0x00002886, 0x000028bc,
	0x00002970, 0x000029b4, 0x00002a31, 0x00002b31,
	0x00002b7e, 0x00002bf9, 0x00002c1a, 0x00002c2c,
	0x00002c55, 0x00002c70, 0x00002c95, 0x00002cb8,
	0x00002cfe, 0x00002d19, 0x00002d35, 0x00002d74,
	// Entry A0 - BF
	0x00002e2a, 0x00002e7a, 0x00002eba, 0x00002ee0,
	0x00002f39, 0x00002f58, 0x00002f94, 0x00002fc4,
	0x00003014, 0x00003020, 0x00003032, 0x0000308a,
	0x00003116, 0x0000314f, 0x000031a5, 0x000031e3,
	0x00003231, 0x0000324c, 0x00003286, 0x000032b9,
	0x000032f3, 0x0000331d, 0x00003347, 0x00003389,
	0x000033ad, 0x000033ba, 0x00003440, 0x00003492,
	0x000034b9, 0x00003555, 0x000035e7, 0x00003628,
	// Entry C0 - DF
	0x0000363e, 0x000036a9, 0x000036f8, 0x000036ff,
	0x00003747, 0x00003799, 0x000037f3, 0x0000385d,
	0x000038ee, 0x00003906, 0x00003920, 0x00003944,
	0x00003977, 0x0000398f, 0x000039a7, 0x000039bf,
	0x000039d4, 0x00003a2b, 0x00003a56, 0x00003a6e,
	0x00003a95, 0x00003ab8, 0x00003acc, 0x00003ae1,
	0x00003ae8, 0x00003aef, 0x00003af5, 0x00003afb,
	0x00003b1c, 0x00003b46, 0x00003b6c, 0x00003ba5,
	// Entry E0 - FF
	0x00003bdd, 0x00003c15, 0x00003c34, 0x00003c80,
	0x00003d3e, 0x00003d8a, 0x00003dd8, 0x00003dfb,
	0x00003e57, 0x00003ea7, 0x00003efc, 0x00003f3f,
	0x00003f7e, 0x00003fec, 0x00003ffd, 0x0000400b,
	0x00004023, 0x00004037, 0x00004051, 0x0000407b,
	0x000040de, 0x0000411a, 0x00004144, 0x0000417c,
	0x000041a0, 0x000041f4, 0x0000422c, 0x000042a5,
	0x0000435f, 0x000043b6, 0x000043e5, 0x0000440c,
	// Entry 100 - 11F
	0x00004498,
} // Size: 1052 bytes

const koData string = "" + // Size: 17560 bytes
	"\x02수학 유틸리티\x02배치 실러 스레드의 레이아웃 분석 및 표시\x02CPU에서 배치 실러 스레드의 레이아웃을 분석하고 표시" +
	"합니다.\x0a\x0a이 작업은 배치 실링 작업의 CPU 사용량에 대한 자세한 정보를 제공하며, 여기에는 코어 할당 및 다양한" +
	" 배치 크기에 대한 스레드 분포가 포함됩니다.\x02supra_seal 구성 생성\x02주어진 배치 크기에 대한 supra_sea" +
	"l 구성을 생성합니다.\x0a\x0a이 명령은 SupraSeal에서 기대하는 구성을 출력하며, 주로 디버깅 및 테스트를 목적으로 " +
	"합니다.\x0a구성은 Curio를 사용하지 않고도 SupraSeal 바이너리에서 직접 사용할 수 있습니다.\x02Zen3 및 " +
	"이후 버전은 스레드당 두 개의 섹터를 지원하며, 이전 CPU에서는 false로 설정합니다\x02CLI 명령 실행\x02기계 호" +
	"스트:포트 (curio run --listen 주소)\x02Curio API가 온라인 상태가 될 때까지 기다리기\x02실패할 " +
	"때까지 대기할 시간\x02색인된 조각에서 CID 샘플을 제공합니다.\x02조각 CID\x02JSON 형식으로 출력\x02노드 " +
	"구성을 레이어별로 관리합니다. 'base' 레이어는 항상 Curio 시작 시 적용됩니다.\x02기본 노드 구성 출력\x02기본" +
	"값에 주석을 달지 않음\x02파일 이름 또는 stdin을 제공하여 구성 레이어 또는 기본값 설정.\x02레이어의 파일 이름" +
	"\x02구성 레이어의 제목 (stdin에 필요)\x02이름으로 구성 레이어를 가져옵니다. 출력을 파일로 파이핑하거나 'less'를" +
	" 사용할 수 있습니다.\x02레이어 이름\x02DB에 있는 구성 레이어 목록.\x02이름이 지정된 구성 레이어 제거.\x02시스템" +
	" 생성 주석과 함께 이 버전의 Curio에서 스택된 구성 레이어 해석.\x02최종 구성으로 해석될 레이어 목록\x02쉼표 또는 공" +
	"백으로 구분된 해석될 레이어 목록 (base는 항상 적용됨)\x02구성 레이어 편집\x02[레이어 이름]\x02사용할 편집기" +
	"\x02원본 구성 레이어\x02원본이 다른 레이어일 경우 기존 레이어 덮어쓰기 허용\x02차이점만이 아니라 전체 구성을 레이어에 " +
	"저장\x02원본 레이어 해석하지 않음\x02--source가 설정된 경우 true\x02새 클러스터에 대한 새 구성 생성" +
	"\x02[SP 액터 주소...]\x02노드를 격리하고 유지 보수 모드로 설정\x02노드 격리를 해제하고 스케줄링 재개\x02파일에" +
	"서 IPNI 청크 생성\x02Curio 노드 정보 가져오기\x02로깅 관리\x02로그 시스템 목록\x02로그 레벨 설정\x02" +
	"[레벨]\x04\x00\x01\x0a\xa2\x04\x02로깅 시스템의 로그 레벨을 설정합니다:\x0a\x0a   시스템 플래그는" +
	" 여러 번 지정할 수 있습니다.\x0a\x0a   예) log set-level --system chain --system cha" +
	"inxchg debug\x0a\x0a   사용 가능한 레벨:\x0a   debug\x0a   info\x0a   warn\x0a " +
	"  error\x0a\x0a   환경 변수:\x0a   GOLOG_LOG_LEVEL - 모든 로그 시스템의 기본 로그 레벨\x0a" +
	"   GOLOG_LOG_FMT   - 출력 로그 형식 변경 (json, nocolor)\x0a   GOLOG_FILE      -" +
	" 로그를 파일에 기록\x0a   GOLOG_OUTPUT    - 출력 위치 지정 (파일, stderr, stdout 또는 조합, " +
	"예: file+stderr)\x02로그 시스템으로 제한\x02Filecoin 분산 스토리지 네트워크 제공자\x02디스플레이 출" +
	"력에 색상 사용\x02출력이 TTY에 의존\x02유가바이트 클러스터의 호스트 이름을 쉼표로 구분한 목록\x02Yugabyte " +
	"클러스터의 Postgres 데이터베이스 이름\x02Yugabyte 클러스터의 Postgres 데이터베이스에 연결하기 위한 사용" +
	"자 이름\x02Yugabyte 클러스터의 Postgres 데이터베이스에 연결하기 위한 비밀번호\x02Yugabyte 클러스터의" +
	" Postgres 데이터베이스에 연결하기 위한 포트\x02Yugabyte 클러스터의 Cassandra 데이터베이스에 연결하기 위한" +
	" 포트\x02Yugabyte 클러스터의 Postgres 데이터베이스에 연결할 때 로드 밸런싱을 활성화하세요\x02매우 상세한 모드" +
	"를 활성화하여 CLI 디버깅에 유용\x02증명 매개변수 가져오기\x02[섹터 크기]\x02거래 섹터를 조기에 실링 시작\x02" +
	"실링할 섹터의 액터 주소 지정\x02합성 PoRep 사용\x02<섹터>\x02오프라인 거래 데이터를 가져올 URL 추가\x02" +
	"여러 거래 입력에 사용할 CSV 파일 위치. 파일의 각 행은 'uuid, 원시 크기, url, header1, header2." +
	"..' 형식이어야 합니다.\x02HTTP 요청에 포함할 사용자 정의 `HEADER`\x02요청을 보낼 `URL`\x02거래 담보 " +
	"지갑에서 자금을 스토리지 시장 액터의 에스크로로 이동\x02사용자가 이 메시지에 대해 지불하려는 FIL의 최대 수수료\x02자" +
	"금을 보낼 지갑 주소 지정\x02Curio에 대한 새로운 오프라인 검증된 DDO 거래를 생성합니다.\x02거래에 사용할 액터 " +
	"주소를 지정하세요.\x02이 거래를 포함하는 섹터의 봉인되지 않은 복사본을 제거합니다.\x02거래 인덱스가 IPNI에 발표되지" +
	" 않아야 함을 나타냅니다.\x02거래가 제공업체에 의해 온체인에서 입증되어야 하는 시작 에포크입니다. (기본값: 현재로부터 2일 " +
	"후)\x02Curio 프로세스 시작\x02작업자 API가 수신 대기할 호스트 주소와 포트\x02GUI가 수신 대기할 호스트 주" +
	"소와 포트\x02풀 노드 동기화 상태 확인 안 함\x02init만 실행하고 돌아옴\x02열린 파일 제한 관리\x02해석될 레이" +
	"어 목록 (기본값 위에). 기본값: base\x02사용자 지정 노드 이름\x02Curio 웹 인터페이스 시작\x02Curio " +
	"웹 인터페이스 인스턴스를 시작합니다.\x0a\x09존재하지 않으면 'web' 레이어를 생성하고 해당 레이어로 실행을 호출합니다" +
	".\x02GUI가 수신 대기할 주소\x02실링 파이프라인 관리\x02새로운 실링 작업 수동 시작\x02모든 액터에 대한 섹터 실링" +
	" 즉시 시작 (일정에 없음)\x02새 CC 섹터 실링 시작\x02시작할 섹터 수\x02섹터를 커밋할 기간\x021278 (3.5년" +
	")\x02(디버그 도구) LM 섹터 메타데이터를 Curio DB로 복사\x02마이너 저장소 경로\x02이동할 수 없는 섹터 무시" +
	"\x02파이프라인 이벤트 목록\x02액터 주소로 이벤트 필터링; 지정하지 않으면 모든 이벤트를 나열합니다\x02섹터 번호로 이벤트" +
	" 필터링; --actor 지정 필요\x02출력을 마지막 N개의 이벤트로 제한\x02실행 중인 Curio 프로세스 중지\x02섹터 " +
	"스토리지 관리\x02섹터는 여러 파일 시스템 경로에 걸쳐 저장될 수 있습니다.\x0a이 명령은 Curio 노드가 섹터를 장기 " +
	"저장(증명용, 'store'로 참조)하는 스토리지를 관리하는 방법과\x0a실링 파이프라인을 통해 이동하는 동안 섹터가 어떻게 " +
	"저장될지를 관리합니다('seal'로 참조).\x02로컬 스토리지 경로 연결\x02[경로]\x04\x00\x04\x0a   " +
	"\xb0\x06\x02이 명령을 사용하여 Curio 노드에 스토리지를 연결할 수 있습니다. 스토리지 볼륨 목록은 curio run" +
	"에 설정된 storage.json에 로컬로 저장됩니다.\x0a스토리지 시스템에 대한 추가 이해 없이 수동으로 이 값을 수정하는" +
	" 것은 권장하지 않습니다.\x0a\x0a각 스토리지 볼륨에는 볼륨의 기능을 설명하는 구성 파일이 포함되어 있습니다. '--init" +
	"' 플래그가 제공되면 이 파일은 추가 플래그를 사용하여 생성됩니다.\x0a\x0aWeight\x0a높은 가중치 값은 데이터가 이 " +
	"경로에 저장될 가능성이 더 높다는 것을 의미합니다\x0a\x0aSeal\x0a실링 프로세스 데이터를 여기에 저장합니다\x0a" +
	"\x0aStore\x0a완료된 섹터는 장기 저장을 위해 여기로 이동되며 시간이 지남에 따라 증명됩니다\x02경로를 먼저 초기화" +
	"\x02(초기화용) 경로 가중치\x02(초기화용) 실링에 경로 사용\x02(초기화용) 장기 저장에 경로 사용\x02(초기화용) 섹" +
	"터에 대한 저장 공간 제한 (매우 큰 경로에서는 비용이 많이 듦!)\x02경로 그룹 이름\x02이 경로에서 데이터를 가져올 수" +
	" 있는 경로 그룹 (지정하지 않으면 모두 허용)\x02로컬 스토리지 경로 분리\x02로컬 스토리지 경로 목록\x02로컬 스토리지 " +
	"경로만 나열\x02스토리지 시스템에서 섹터 찾기\x02[마이너 주소] [섹터 번호]\x02섹터에 대한 바닐라 증명 생성\x02" +
	"로컬 스토리지 경로에서 섹터를 다시 선언\x02CLI 명령의 --machine 플래그는 다시 선언할 스토리지가 연결된 노드를 " +
	"가리켜야 합니다\x02테스트용 유틸리티 기능\x02섹터에 대한 증명 계산 (섹터가 사전 실링되어야 함). 이는 체인으로 전송되" +
	"지 않습니다.\x02다음 사용 가능한 Curio에서 windowpost 스케줄러를 실행하여 테스트합니다. 모든 재시도가 실패하" +
	"면 ctrl+c를 눌러 종료해야 합니다.\x04\x00\x01 \x1f\x02WindowPoSt를 계산할 기한\x02Windo" +
	"wPoSt 계산을 위한 SP ID\x02성능 및 구성 테스트를 위한 WindowPoSt 계산.\x02참고: 이 명령은 PoSt 계" +
	"산 성능을 검증하기 위해 사용됩니다.\x0a체인으로 메시지를 전송하지 않습니다. 모든 기한을 계산할 수 있으므로 출력이 체인과" +
	" 부정확하게 일치할 수 있습니다.\x02[기한 인덱스]\x02스토리지 구성 파일이 포함된 JSON 파일의 경로\x02WindowP" +
	"oSt를 계산할 파티션\x02디버깅 유틸리티 모음\x02Curio 도구 상자\x02체인 노드에서 누락된 메시지 데이터를 사용하여 " +
	"데이터베이스를 업데이트함\x02대기 큐에 있는 메시지의 데이터를 업데이트\x02미봉인 데이터를 관리\x02미봉인 데이터에 대한" +
	" 정보 가져오기\x02sectors_unseal_pipeline 및 sectors_meta 테이블의 데이터 나열\x02스토리지 제" +
	"공자 ID로 필터링\x02출력 파일 경로 (기본값: 표준 출력)\x02섹터의 목표 미봉인 상태 설정\x04\x00\x01" +
	"\x0a\xda\x07\x02특정 섹터의 목표 미봉인 상태를 설정합니다.\x0a   <miner-id>: 스토리지 제공자 ID" +
	"\x0a   <sector-number>: 섹터 번호\x0a   <target-state>: 목표 상태 (true, false, " +
	"none 중 하나)\x0a\x0a   미봉인 목표 상태는 Curio가 섹터의 미봉인 복사본을 어떻게 유지할지를 나타냅니다.\x0a" +
	"\x09   목표 상태가 true이면 Curio는 섹터가 미봉인 상태로 유지되도록 보장합니다.\x0a\x09   목표 상태가 fa" +
	"lse이면 Curio는 섹터에 미봉인 복사본이 없도록 보장합니다.\x0a\x09   목표 상태가 none이면 Curio는 섹터의 " +
	"현재 상태를 변경하지 않습니다.\x0a\x0a   현재, 목표 상태가 다른 상태에서 true로 변경될 때만 Curio는 새로운" +
	" 미봉인 프로세스를 시작합니다.\x0a\x0a   목표 상태가 false이고 미봉인 섹터 파일이 존재하는 경우, GC 마크 단계는" +
	" 미봉인 섹터 파일에 대한 제거 마크를 생성합니다. 파일은 제거 마크가 승인된 후에만 제거됩니다.\x02미봉인 섹터 파일의 데이터" +
	" 무결성 확인\x02특정 섹터에 대한 검사 작업을 생성하고 완료를 기다린 후 결과를 출력합니다.\x0a   <miner-id>: " +
	"스토리지 제공자 ID\x0a   <sector-number>: 섹터 번호\x04\x00\x01 ?\x02화살표 키를 사용하여 " +
	"이동하세요: ↓ ↑ → ←\x02이 대화형 도구는 새로운 채굴자 액터를 생성하고 그에 대한 기본 구성 레이어를 생성합니다." +
	"\x02이 프로세스는 부분적으로 항등원적입니다. 새로운 채굴자 액터가 생성되었고 후속 단계가 실패하는 경우 사용자는 구성을 완료하" +
	"기 위해 'curio config new-cluster < 채굴자 ID >'를 실행해야 합니다.\x02이 대화형 도구는 5분 " +
	"안에 lotus-miner를 Curio로 이주합니다.\x02각 단계는 확인이 필요하며 되돌릴 수 있습니다. 언제든지 Ctrl+" +
	"C를 눌러 종료할 수 있습니다.\x02터미널에서 Ctrl+C가 눌림\x02나는 원한다:\x02기존의 Lotus-Miner에서 이전" +
	"하기\x02새로운 채굴자 생성\x02나머지 단계를 중단합니다.\x02Lotus-Miner에서 Curio로 이주.\x02데이터베" +
	"이스 구성 파일을 어디에 저장해야 하나요?\x02마이그레이션 중단.\x02파일 쓰기 오류: %[1]s\x04\x00\x01 :" +
	"\x02%[1]s와 함께 웹 인터페이스를 시도해보세요\x02더 많은 서버를 위해 /etc/curio.env 파일을 curio.en" +
	"v 데이터베이스 환경으로 만들고 목적을 할당하기 위해 CURIO_LAYERS 환경 변수를 추가하세요.\x02해당하는 경우 이제 시" +
	"장 노드를 이주할 수 있습니다 (%[1]s).\x02추가 정보는 http://docs.curiostorage.org 에 있습니" +
	"다.\x02새로운 채굴자 초기화 완료.\x02lotus-miner config.toml을 Curio의 데이터베이스 구성으로 이" +
	"전 중입니다.\x02API 가져오기 오류: %[1]s\x02FullNode의 API 정보를 가져올 수 없습니다: %[1]w" +
	"\x02토큰을 가져오는 중 오류 발생: %[1]s\x02이동할 수 없는 섹터가 발견되었습니다. 계속하시겠습니까?\x02예, 계속" +
	"\x02아니오, 중단\x02레이어에 구성을 저장하는 중 오류 발생: %[1]s. 마이그레이션 중단\x02Curio 팀은 당신이 사" +
	"용하는 소프트웨어를 개선하고자 합니다. 팀에게 `%[1]s`를 사용 중이라고 알려주세요.\x02Curio 팀과 공유하고 싶은 " +
	"것을 선택하세요.\x02개별 데이터: 채굴자 ID, Curio 버전, 체인 (%[1]s 또는 %[2]s). 서명됨.\x02집계" +
	"-익명: 버전, 체인, 및 채굴자 파워 (버킷).\x02힌트: 나는 어떤 체인에서든 Curio를 실행 중인 사람입니다.\x02아무" +
	"것도 없습니다.\x02마이너 파워를 가져오는 중 오류 발생: %[1]s\x02메시지를 마샬하는 중 오류 발생: %[1]s" +
	"\x02마이너 정보를 가져오는 중 오류 발생: %[1]s\x02메시지 서명 중 오류 발생: %[1]s\x02메시지 전송 중 오류 " +
	"발생: %[1]s\x04\x00\x01 =\x02메시지 전송 중 오류 발생: 상태 %[1]s, 메시지:\x02메시지가 전송되었" +
	"습니다.\x04\x00\x01 \x08\x02문서:\x02'%[1]s' 레이어에는 공통 구성이 저장됩니다. 모든 Curio 인" +
	"스턴스는 %[2]s 인수에 포함시킬 수 있습니다.\x02기계별 구성 변경을 위해 다른 레이어를 추가할 수 있습니다.\x02Fi" +
	"lecoin %[1]s 채널: %[2]s 및 %[3]s\x02신뢰성 향상을 위한 중복성 사용: 적어도 post 레이어를 사용하여 " +
	"여러 대의 기계를 시작하십시오: 'curio run --layers=post'\x02한 개의 데이터베이스는 여러 광부 ID를 " +
	"제공할 수 있습니다: 각 lotus-miner에 대해 마이그레이션을 실행하세요.\x02Yugabyte에 연결되었습니다. 스키마" +
	"가 현재입니다.\x02Yugabyte에 연결됨\x02시작하려면 밀봉 파이프라인이 비어 있고 lotus-miner가 종료되었는지" +
	" 확인하세요.\x02로터스 마이너 구성 디렉토리의 위치를 선택하시겠습니까?\x02기타\x02%[1]s에서 사용하는 구성 디렉터리 " +
	"경로를 입력하세요.\x04\x00\x01 M\x02경로가 제공되지 않았으므로 마이그레이션을 포기합니다\x02제공된 디렉토리에서" +
	" config.toml 파일을 읽을 수 없습니다. 오류: %[1]s\x02디렉토리에서 저장소를 생성할 수 없습니다: %[1]s. " +
	"마이그레이션을 중단합니다.\x02광부 저장소를 잠금 해제할 수 없습니다. 귀하의 광부를 중지해야 합니다: %[1]s\x0a 마" +
	"이그레이션을 중단합니다.\x02마이너 구성 읽기\x04\x00\x01\x0a\x15\x02단계 완료: %[1]s\x02새 채굴" +
	"자 액터 초기화 중.\x02새 채굴자를 생성하기 위한 정보 입력\x02소유자 지갑: %[1]s\x02작업자 지갑: %[1]s" +
	"\x02발송자 지갑: %[1]s\x02섹터 크기: %[1]s\x02주소를 확인하고 새 채굴자 액터를 생성하려면 계속 진행하세요." +
	"\x04\x00\x01 &\x02채굴자 생성 오류 발생: %[1]s\x02소유자 주소 입력\x02주소가 제공되지 않았습니다\x02" +
	"주소 구문 분석 실패: %[1]s\x02%[1]s 주소 입력\x02섹터 크기 선택\x0264 GiB\x0232 GiB\x028" +
	" MiB\x022 KiB\x04\x00\x01 \x1c\x02섹터 선택 실패: %[1]s\x02섹터 크기 구문 분석 실패: %[1" +
	"]s\x02채굴자 액터 생성 실패: %[1]s\x02%[1]s 채굴자가 성공적으로 생성되었습니다\x02데이터베이스에 연결할 수 없" +
	"습니다: %[1]s\x02풀 노드 API에 연결하는 중 오류 발생: %[1]s\x02사전 초기화 단계 완료\x02비밀번호를 위" +
	"한 랜덤 바이트 생성에 실패했습니다: %[1]s\x02마이너 생성은 idempotent하지 않으므로 가이드 설정을 다시 실행하" +
	"지 마십시오. 구성을 완료하려면 'curio config new-cluster %[1]s'를 실행해야 합니다.\x02FullN" +
	"ode에 대한 API 정보를 가져오는 데 실패했습니다: %[1]w\x02데몬 노드로부터 인증 토큰을 확인하는 중 오류 발생: %[" +
	"1]s\x02기본 구성 생성 실패: %[1]s\x02데이터베이스에 'base' 구성 레이어를 삽입하는 데 실패했습니다: %[1]s" +
	"\x02이 마이너 주소를 포함한 구성 'base'가 업데이트되었습니다.\x02데이터베이스에서 기본 구성을 로드하는 데 실패했습니다" +
	": %[1]s\x02기본 구성을 구문 분석하는 데 실패했습니다: %[1]s\x02기본 구성을 재생성하는 데 실패했습니다: %[1]" +
	"s\x02Yugabyte 데이터베이스 설치에 연결할 정보를 입력하십시오 (https://download.yugabyte.com/)" +
	"\x02호스트: %[1]s\x02포트: %[1]s\x02사용자 이름: %[1]s\x02비밀번호: %[1]s\x02데이터베이스: %" +
	"[1]s\x02계속 연결 및 스키마 업데이트.\x04\x00\x01 ^\x02데이터베이스 구성 오류가 발생하여 마이그레이션을 포기" +
	"합니다: %[1]s\x02Yugabyte 데이터베이스 호스트를 입력하십시오\x02호스트가 제공되지 않았습니다\x02Yugaby" +
	"te 데이터베이스 %[1]s을 입력하십시오\x02값이 제공되지 않았습니다\x02Yugabyte 데이터베이스에 연결하는 중 오류가 " +
	"발생했습니다: %[1]s\x02%[1]d 섹터의 메타데이터를 이동 중입니다.\x02기본 설정 'base'가 이 마이너의 주소(" +
	"%[1]s) 및 지갑 설정을 포함하도록 업데이트되었습니다.\x02구성 %[1]s를 %[2]s과 비교하세요. 지갑 주소 이외의 마이" +
	"너 ID 사이의 변경 사항은 필요한 실행자를 위한 새로운 최소한의 레이어여야 합니다.\x02'base' 설정이 이 lotus-" +
	"miner의 config.toml과 유사하게 만들어졌습니다.\x04\x00\x01 *\x02레이어 %[1]s가 생성되었습니다." +
	"\x04\x00\x01 \x22\x02구성 파일을 사용하려면:\x02Curio를 실행하려면: 기계 또는 cgroup 격리를 사용하" +
	"여 다음 명령을 사용하세요 (예제 레이어 선택과 함께):"

var zhIndex = []uint32{ // 257 elements
	// Entry 0 - 1F
	0x00000000, 0x0000000d, 0x00000038, 0x000000e6,
	0x000000ff, 0x000001d8, 0x00000229, 0x0000023b,
	0x0000026c, 0x00000284, 0x000002a0, 0x000002c4,
	0x000002cf, 0x000002e5, 0x0000032f, 0x00000348,
	0x0000035e, 0x000003a4, 0x000003b4, 0x000003df,
	0x00000438, 0x00000442, 0x0000046a, 0x00000486,
	0x000004d6, 0x000004fb, 0x00000543, 0x00000553,
	0x0000055f, 0x00000572, 0x0000057f, 0x000005b3,
	// Entry 20 - 3F
	0x000005ea, 0x000005fd, 0x00000624, 0x00000640,
	0x00000655, 0x00000686, 0x000006ae, 0x000006c7,
	0x000006e1, 0x000006f4, 0x00000707, 0x0000071a,
	0x00000723, 0x000008f0, 0x00000906, 0x00000931,
	0x00000950, 0x0000096c, 0x0000099a, 0x000009c9,
	0x00000a02, 0x00000a38, 0x00000a6e, 0x00000aa5,
	0x00000aed, 0x00000b1f, 0x00000b32, 0x00000b41,
	0x00000b60, 0x00000b88, 0x00000b9b, 0x00000ba4,
	// Entry 40 - 5F
	0x00000bce, 0x00000c4b, 0x00000c76, 0x00000c8c,
	0x00000cd8, 0x00000d0b, 0x00000d2d, 0x00000d5e,
	0x00000d86, 0x00000dba, 0x00000de5, 0x00000e40,
	0x00000e54, 0x00000e7e, 0x00000ea1, 0x00000ec0,
	0x00000ee2, 0x00000efe, 0x00000f3c, 0x00000f52,
	0x00000f6c, 0x00000feb, 0x00000fff, 0x00001015,
	0x00001034, 0x0000106e, 0x0000108b, 0x000010a4,
	0x000010c0, 0x000010cf, 0x00001111, 0x00001124,
	// Entry 60 - 7F
	0x00001140, 0x00001156, 0x00001193, 0x000011c6,
	0x000011eb, 0x0000120e, 0x00001221, 0x0000130a,
	0x00001323, 0x0000132c, 0x0000157f, 0x00001592,
	0x000015b4, 0x000015dc, 0x0000160a, 0x0000166b,
	0x0000167b, 0x000016cd, 0x000016e6, 0x000016ff,
	0x0000171b, 0x0000173a, 0x00001758, 0x0000177a,
	0x000017a5, 0x000017f7, 0x0000180d, 0x0000186b,
	0x000018f0, 0x00001917, 0x00001945, 0x00001979,
	// Entry 80 - 9F
	0x00001a26, 0x00001a3b, 0x00001a66, 0x00001a82,
	0x00001a95, 0x00001aa5, 0x00001adf, 0x00001b04,
	0x00001b1d, 0x00001b3c, 0x00001b7f, 0x00001b9c,
	0x00001bca, 0x00001bec, 0x00001eed, 0x00001f1e,
	0x00001fa4, 0x00001fd7, 0x0000202f, 0x000020d8,
	0x00002120, 0x0000216f, 0x00002188, 0x00002195,
	0x000021b5, 0x000021ce, 0x000021e4, 0x00002201,
	0x0000223e, 0x0000224e, 0x00002268, 0x0000228e,
	// Entry A0 - BF
	0x00002315, 0x00002356, 0x00002389, 0x000023a5,
	0x000023ea, 0x00002407, 0x00002430, 0x0000244e,
	0x00002482, 0x00002492, 0x0000249f, 0x000024d8,
	0x0000252c, 0x00002559, 0x000025a8, 0x000025e3,
	0x00002618, 0x00002622, 0x00002646, 0x00002664,
	0x00002688, 0x000026a6, 0x000026c4, 0x000026f9,
	0x0000270c, 0x0000271b, 0x00002775, 0x000027b2,
	0x000027da, 0x00002839, 0x00002889, 0x000028b6,
	// Entry C0 - DF
	0x000028cb, 0x00002916, 0x00002946, 0x0000294d,
	0x00002977, 0x0000299b, 0x000029df, 0x00002a11,
	0x00002a5a, 0x00002a6d, 0x00002a87, 0x00002aa6,
	0x00002acb, 0x00002ae2, 0x00002af6, 0x00002b0d,
	0x00002b21, 0x00002b52, 0x00002b77, 0x00002b8d,
	0x00002b9d, 0x00002bb7, 0x00002bcb, 0x00002bde,
	0x00002be5, 0x00002bec, 0x00002bf2, 0x00002bf8,
	0x00002c17, 0x00002c37, 0x00002c57, 0x00002c71,
	// Entry E0 - FF
	0x00002c8e, 0x00002cbf, 0x00002cd8, 0x00002d01,
	0x00002d8e, 0x00002dba, 0x00002df5, 0x00002e15,
	0x00002e46, 0x00002e79, 0x00002ea6, 0x00002ec7,
	0x00002eed, 0x00002f47, 0x00002f56, 0x00002f65,
	0x00002f77, 0x00002f86, 0x00002f98, 0x00002fb7,
	0x00002fef, 0x00003014, 0x00003024, 0x00003042,
	0x0000304f, 0x0000307b, 0x000030a5, 0x000030f6,
	0x00003178, 0x000031bf, 0x000031d9, 0x000031f1,
	// Entry 100 - 11F
	0x00003248,
} // Size: 1052 bytes

const zhData string = "" + // Size: 12872 bytes
	"\x02数学工具\x02分析并显示批量封装线程的布局\x02分析并显示CPU上批量封装线程的布局。\x0a\x0a提供有关批量封装操作的CPU利" +
	"用率的详细信息，包括核心分配和不同批量大小的线程分布。\x02生成 supra_seal 配置\x02为指定的批量大小生成 supra_se" +
	"al 配置。\x0a\x0a此命令输出 SupraSeal 所需的配置，主要用于调试和测试。配置可以直接用于 SupraSeal 二进制文件进行" +
	"测试，而无需涉及 Curio。\x02Zen3 及以后版本支持每个线程两个扇区，旧版CPU请设置为 false\x02执行 CLI 命令" +
	"\x02机器主机:端口 (curio run --listen address)\x02等待 Curio API 上线\x02等待失败的持续时间" +
	"\x02提供索引片段的 CID 示例。\x02片段 CID\x02以 JSON 格式输出\x02通过层管理节点配置。Curio 启动时始终应用“" +
	"base”层。\x02打印默认节点配置\x02不要注释默认值\x02通过提供文件名或标准输入来设置配置层或基础层。\x02层的文件名\x02配置" +
	"层的标题（标准输入必需）\x02通过名称获取配置层。您可能希望将输出传递到文件，或使用 'less'\x02层名称\x02列出数据库中存在的" +
	"配置层。\x02移除命名的配置层。\x02由此版本的 Curio 解释堆叠的配置层，带有系统生成的注释。\x02要解释为最终配置的层列表" +
	"\x02要解释的层列表，以逗号或空格分隔（base 始终应用）\x02编辑配置层\x02[层名称]\x02使用的编辑器\x02源配置层\x02如" +
	"果源是不同的层，则允许覆盖现有层\x02将整个配置保存到层中，而不仅仅是差异\x02不要解释源层\x02如果设置了 --source，则为 " +
	"true\x02为新集群创建新配置\x02[SP actor 地址...]\x02隔离一个节点，将其设置为维护模式\x02取消隔离一个节点，恢复" +
	"调度\x02从文件生成 IPNI 块\x02获取 Curio 节点信息\x02管理日志记录\x02列出日志系统\x02设置日志级别\x02[" +
	"级别]\x04\x00\x01\x0a\xc7\x03\x02为日志系统设置日志级别：\x0a\x0a 系统标志可以多次指定。\x0a" +
	"\x0a 例如) log set-level --system chain --system chainxchg debug\x0a\x0a 可" +
	"用级别：\x0a debug\x0a info\x0a warn\x0a error\x0a\x0a 环境变量：\x0a GOLOG_LOG" +
	"_LEVEL - 所有日志系统的默认日志级别\x0a GOLOG_LOG_FMT   - 更改输出日志格式 (json, nocolor)" +
	"\x0a GOLOG_FILE      - 将日志写入文件\x0a GOLOG_OUTPUT    - 指定是否输出到文件、stderr、st" +
	"dout 或组合，例如 file+stderr\x02限制到日志系统\x02Filecoin 去中心化存储网络提供商\x02在显示输出中使用颜色" +
	"\x02取决于输出是否为TTY\x02Yugabyte 集群的主机名命令分隔列表\x02Yugabyte 集群中 Postgres 数据库的名称" +
	"\x02连接 Yugabyte 集群中 Postgres 数据库的用户名\x02连接 Yugabyte 集群中 Postgres 数据库的密码" +
	"\x02连接 Yugabyte 集群中 Postgres 数据库的端口\x02连接 Yugabyte 集群中 Cassandra 数据库的端口" +
	"\x02为连接到 Yugabyte 集群中的 Postgres 数据库启用负载均衡\x02启用非常详细的模式，有助于调试 CLI\x02获取证明" +
	"参数\x02[扇区大小]\x02提前开始封装交易扇区\x02指定演员地址以开始封装扇区\x02使用合成 PoRep\x02<扇区>\x02添" +
	"加 URL 以获取离线交易的数据\x02用于多交易输入的 CSV 文件位置。文件中的每一行应为格式 'uuid, 原始大小, URL, he" +
	"ader1, header2...'\x02在 HTTP 请求中包含自定义 `HEADER`\x02发送请求的 `URL`\x02将资金从交易抵" +
	"押钱包转移到存储市场参与者的托管账户\x02用户愿意为此消息支付的最大 FIL 费用\x02指定发送资金的钱包地址\x02为 Curio 创" +
	"建新的离线验证 DDO 交易。\x02请指定此交易的参与者地址。\x02删除包含此交易的扇区的未密封副本。\x02表示交易索引不应向 IPN" +
	"I 公布。\x02交易应由提供者在链上证明的起始 epoch。（默认值：从现在起 2 天）\x02启动 Curio 进程\x02worker A" +
	"PI 监听的主机地址和端口\x02GUI 监听的主机地址和端口\x02不检查全节点同步状态\x02仅运行初始化，然后返回\x02管理打开文件的限" +
	"制\x02要解释的层列表（在默认值之上）。默认：base\x02自定义节点名称\x02启动 Curio 网络界面\x02启动 Curio 网" +
	"络界面的一个实例。\x0a\x09如果“web”层不存在，则创建该层，然后使用该层调用运行。\x02GUI 监听的地址\x02管理封装流水线" +
	"\x02手动开始新的封装操作\x02立即为所有演员开始封装扇区（非计划内）\x02开始封装新的 CC 扇区\x02要开始的扇区数量\x02承诺扇" +
	"区的时间长度\x021278 (3.5 年)\x02（调试工具）将 LM 扇区元数据复制到 Curio 数据库\x02矿工库的路径\x02忽" +
	"略无法迁移的扇区\x02列出流水线事件\x02按演员地址过滤事件；如果未指定则列出所有\x02按扇区编号过滤事件；需要指定 --actor" +
	"\x02将输出限制为最后 N 个事件\x02停止正在运行的 Curio 进程\x02管理扇区存储\x02扇区可以存储在多个文件系统路径中。这些命" +
	"令提供了管理 Curio 节点用于长期存储和证明的存储方法（参考为“store”），以及封装过程中扇区的存储方式（参考为“seal”）。" +
	"\x02附加本地存储路径\x02[路径]\x04\x00\x04\x0a   \xca\x04\x02可以使用此命令将存储附加到 Curio 节" +
	"点。存储卷列表存储在本地 Curio 节点中的 storage.json 文件中，通过 curio run 设置。建议在了解存储系统之前，不" +
	"要手动修改此值。\x0a\x0a每个存储卷包含一个配置文件，该文件描述了该卷的功能。提供 '--init' 标志时，将使用其他标志创建此文件" +
	"。\x0a\x0a权重\x0a较高的权重值意味着数据更有可能存储在此路径中\x0a\x0a封装\x0a封装过程的数据将存储在这里\x0a" +
	"\x0a存储\x0a已完成的扇区将移至此处进行长期存储，并随着时间推移进行证明\x02先初始化路径\x02（用于初始化）路径权重\x02（用于初" +
	"始化）路径用于封装\x02（用于初始化）路径用于长期存储\x02（用于初始化）限制扇区的存储空间（对非常大的路径来说成本较高！）\x02路径" +
	"组名称\x02允许从此路径提取数据的路径组（如果未指定，则允许所有）\x02分离本地存储路径\x02列出本地存储路径\x02仅列出本地存储路" +
	"径\x02在存储系统中查找扇区\x02[矿工地址] [扇区编号]\x02为一个扇区生成原始证明\x02在本地存储路径中重新声明扇区\x02C" +
	"LI 命令中的 --machine 标志应指向连接了要重新声明存储的节点\x02测试的实用功能\x02为扇区计算时空证明（需要预封装的扇区）。这" +
	"些将不会发送到链上。\x02通过在下一个可用的 Curio 上运行来测试窗口后调度器。如果所有重试都失败，则需要按 ctrl+c 退出。" +
	"\x04\x00\x01 \x22\x02计算 WindowPoSt 的截止日期\x02用于计算 WindowPoSt 的存储提供者 ID" +
	"\x02计算 WindowPoSt 以进行性能和配置测试。\x02注意：此命令旨在用于验证 PoSt 计算性能。\x0a它不会向链发送任何消息。" +
	"由于它可以计算任何截止日期，输出的时间可能与链不符。\x02[截止日期索引]\x02包含存储配置的 JSON 文件的路径\x02计算 Win" +
	"dowPoSt 的分区\x02调试工具集合\x02Curio 工具箱\x02已使用链节点中缺失的消息数据更新数据库\x02更新等待队列中的消息数" +
	"据\x02管理未密封的数据\x02获取未密封数据的信息\x02列出来自 sectors_unseal_pipeline 和 sectors_" +
	"meta 表的数据\x02按存储提供者 ID 过滤\x02输出文件路径（默认：标准输出）\x02设置扇区的目标解封状态\x04\x00\x01" +
	"\x0a\xfb\x05\x02为特定扇区设置目标解封状态。\x0a   <miner-id>: 存储提供者 ID\x0a   <sector-" +
	"number>: 扇区号\x0a   <target-state>: 目标状态（true、false 或 none）\x0a\x0a   解封目" +
	"标状态表示 Curio 应如何维护扇区的未密封副本。\x0a\x09   如果目标状态为 true，Curio 将确保扇区未密封。\x0a" +
	"\x09   如果目标状态为 false，Curio 将确保扇区没有未密封副本。\x0a\x09   如果目标状态为 none，Curio 将不" +
	"会更改扇区的当前状态。\x0a\x0a   当前，Curio 仅在目标状态从其他状态更改为 true 时启动新的解封进程。\x0a\x0a " +
	"  当目标状态为 false 且存在未密封的扇区文件时，GC 标记步骤将为未密封的扇区文件创建一个删除标记。文件将在删除标记被接受后才会被移除。" +
	"\x02检查未密封扇区文件中的数据完整性\x02为特定扇区创建检查任务，等待其完成并输出结果。\x0a   <miner-id>: 存储提供者 " +
	"ID\x0a   <sector-number>: 扇区号\x04\x00\x01 .\x02使用箭头键进行导航：↓ ↑ → ←\x02此交互式" +
	"工具将创建一个新的矿工角色，并为其创建基本配置层。\x02该过程部分幂等。一旦创建了新的矿工角色，并且随后的步骤失败，用户需要运行 'cur" +
	"io config new-cluster < 矿工 ID >' 来完成配置。\x02这个交互式工具可以在5分钟内将lotus-miner迁移到" +
	"Curio。\x02每一步都需要您的确认，并且可以撤销。随时按Ctrl+C退出。\x02在终端中按下Ctrl+C\x02我想要：\x02从现有的" +
	" Lotus-Miner 迁移\x02创建一个新的矿工\x02中止剩余步骤。\x02Lotus-Miner到Curio迁移。\x02我们应该把你" +
	"的数据库配置文件保存在哪里？\x02中止迁移。\x02写入文件错误: %[1]s\x04\x00\x01 !\x02尝试使用%[1]s的网页" +
	"界面\x02对于更多服务器，请使用 curio.env 数据库环境创建 /etc/curio.env 并添加 CURIO_LAYERS 环境" +
	"变量以分配用途。\x02如果适用，您现在可以迁移您的市场节点(%[1]s)。\x02更多信息请访问 http://docs.curiosto" +
	"rage.org\x02新矿工初始化完成。\x02将 lotus-miner config.toml 迁移到 Curio 的数据库配置中。" +
	"\x02获取 API 时出错：%[1]s\x02无法获取FullNode的API信息：%[1]w\x02获取令牌时出错：%[1]s\x02发现无" +
	"法迁移的扇区。您想要继续吗？\x02是的，继续\x02不，中止\x02保存配置到层时出错：%[1]s。正在中止迁移\x02Curio 团队希" +
	"望改进您使用的软件。告诉团队您正在使用 `%[1]s`。\x02选择您想与Curio团队分享的内容。\x02个人数据：矿工 ID，Curio" +
	" 版本，链（%[1]s 或 %[2]s）。签名。\x02聚合-匿名：版本，链和矿工算力（分桶）。\x02提示：我是在任何链上运行 Curio 的" +
	"人。\x02没有。\x02获取矿工功率时出错：%[1]s\x02整理消息时出错：%[1]s\x02获取矿工信息时出错：%[1]s\x02签署" +
	"消息时出错：%[1]s\x02发送消息时出错：%[1]s\x04\x00\x01 0\x02发送消息时出错：状态%[1]s，消息：\x02消" +
	"息已发送。\x04\x00\x01 \x0a\x02文档：\x02'%[1]s'层存储通用配置。所有Curio实例都可以在其%[2]s参数中" +
	"包含它。\x02您可以添加其他层进行每台机器的配置更改。\x02Filecoin %[1]s 频道：%[2]s 和 %[3]s\x02通过冗" +
	"余增加可靠性：使用至少后层启动多台机器：'curio run --layers=post'\x02一个数据库可以服务多个矿工ID：为每个lo" +
	"tus-miner运行迁移。\x02已连接到Yugabyte。模式是当前的。\x02已连接到Yugabyte\x02开始之前，请确保您的密封管道" +
	"已排空并关闭lotus-miner。\x02选择您的lotus-miner配置目录的位置？\x02其他\x02输入%[1]s使用的配置目录的" +
	"路径\x04\x00\x01 \x1f\x02未提供路径，放弃迁移\x02无法读取提供的目录中的config.toml文件，错误：%[1]s" +
	"\x02无法从目录创建repo：%[1]s。 中止迁移\x02无法锁定矿工repo。 您的矿工必须停止：%[1]s\x0a 中止迁移\x02读取" +
	"矿工配置\x04\x00\x01\x0a\x15\x02步骤完成：%[1]s\x02初始化新的矿工角色。\x02输入创建新矿工所需的信息" +
	"\x02所有者钱包: %[1]s\x02工人钱包: %[1]s\x02发送者钱包: %[1]s\x02扇区大小: %[1]s\x02继续验证地址" +
	"并创建新的矿工角色。\x04\x00\x01  \x02矿工创建错误发生: %[1]s\x02输入所有者地址\x02未提供地址\x02解析地" +
	"址失败: %[1]s\x02输入 %[1]s 地址\x02选择扇区大小\x0264 GiB\x0232 GiB\x028 MiB\x022 " +
	"KiB\x04\x00\x01 \x1a\x02扇区选择失败: %[1]s\x02解析扇区大小失败: %[1]s\x02创建矿工角色失败: %[" +
	"1]s\x02矿工 %[1]s 创建成功\x02无法访问数据库: %[1]s\x02连接到完整节点 API 时发生错误: %[1]s\x02预初" +
	"始化步骤完成\x02生成密码的随机字节失败: %[1]s\x02请不要再次运行引导设置，因为矿工创建不是幂等的。 您需要运行 'curio " +
	"config new-cluster %[1]s' 来完成配置。\x02无法获取 FullNode 的 API 信息: %[1]w\x02无法验" +
	"证来自守护进程节点的授权令牌: %[1]s\x02无法生成默认配置: %[1]s\x02无法将 'base' 配置层插入数据库: %[1]s" +
	"\x02配置 'base' 已更新以包含此矿工的地址\x02从数据库加载基本配置失败：%[1]s\x02解析基本配置失败：%[1]s\x02重新" +
	"生成基本配置失败: %[1]s\x02输入连接到您的Yugabyte数据库安装的信息（https://download.yugabyte.c" +
	"om/）\x02主机：%[1]s\x02端口：%[1]s\x02用户名：%[1]s\x02密码：%[1]s\x02数据库：%[1]s\x02继续" +
	"连接和更新架构。\x04\x00\x01 3\x02发生数据库配置错误，放弃迁移：%[1]s\x02输入Yugabyte数据库主机（S）" +
	"\x02未提供主机\x02输入Yugabyte数据库 %[1]s\x02未提供值\x02连接到Yugabyte数据库时出错：%[1]s\x02正" +
	"在迁移%[1]d个扇区的元数据。\x02'base'配置已更新，包括该矿工的地址（%[1]s）及其钱包设置。\x02比较配置%[1]s和%[" +
	"2]s。矿工ID之间除了钱包地址的变化应该是需要的运行者的一个新的、最小的层。\x02'base'配置已创建，以类似于这个lotus-miner" +
	"的config.toml。\x04\x00\x01 \x15\x02层%[1]s已创建。\x04\x00\x01 \x13\x02要使用配置" +
	"：\x02运行Curio：使用机器或cgroup隔离，使用命令（附带示例层选择）："

	// Total table size 47632 bytes (46KiB); checksum: CD748F3A
