// Code generated by MockGen. DO NOT EDIT.
// Source: replace.go

// Package replace_mock is a generated GoMock package.
package replace_mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	cid "github.com/ipfs/go-cid"

	address "github.com/filecoin-project/go-address"
	big "github.com/filecoin-project/go-state-types/big"

	api "github.com/filecoin-project/lotus/api"
	types "github.com/filecoin-project/lotus/chain/types"
)

// MockMessageReplaceAPI is a mock of MessageReplaceAPI interface.
type MockMessageReplaceAPI struct {
	ctrl     *gomock.Controller
	recorder *MockMessageReplaceAPIMockRecorder
}

// MockMessageReplaceAPIMockRecorder is the mock recorder for MockMessageReplaceAPI.
type MockMessageReplaceAPIMockRecorder struct {
	mock *MockMessageReplaceAPI
}

// NewMockMessageReplaceAPI creates a new mock instance.
func NewMockMessageReplaceAPI(ctrl *gomock.Controller) *MockMessageReplaceAPI {
	mock := &MockMessageReplaceAPI{ctrl: ctrl}
	mock.recorder = &MockMessageReplaceAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageReplaceAPI) EXPECT() *MockMessageReplaceAPIMockRecorder {
	return m.recorder
}

// GasEstimateMessageGas mocks base method.
func (m *MockMessageReplaceAPI) GasEstimateMessageGas(ctx context.Context, msg *types.Message, spec *api.MessageSendSpec, tsk types.TipSetKey) (*types.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GasEstimateMessageGas", ctx, msg, spec, tsk)
	ret0, _ := ret[0].(*types.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GasEstimateMessageGas indicates an expected call of GasEstimateMessageGas.
func (mr *MockMessageReplaceAPIMockRecorder) GasEstimateMessageGas(ctx, msg, spec, tsk interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GasEstimateMessageGas", reflect.TypeOf((*MockMessageReplaceAPI)(nil).GasEstimateMessageGas), ctx, msg, spec, tsk)
}

// MpoolPush mocks base method.
func (m *MockMessageReplaceAPI) MpoolPush(ctx context.Context, smsg *types.SignedMessage) (cid.Cid, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MpoolPush", ctx, smsg)
	ret0, _ := ret[0].(cid.Cid)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MpoolPush indicates an expected call of MpoolPush.
func (mr *MockMessageReplaceAPIMockRecorder) MpoolPush(ctx, smsg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MpoolPush", reflect.TypeOf((*MockMessageReplaceAPI)(nil).MpoolPush), ctx, smsg)
}

// StateAccountKey mocks base method.
func (m *MockMessageReplaceAPI) StateAccountKey(ctx context.Context, addr address.Address, tsk types.TipSetKey) (address.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StateAccountKey", ctx, addr, tsk)
	ret0, _ := ret[0].(address.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StateAccountKey indicates an expected call of StateAccountKey.
func (mr *MockMessageReplaceAPIMockRecorder) StateAccountKey(ctx, addr, tsk interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StateAccountKey", reflect.TypeOf((*MockMessageReplaceAPI)(nil).StateAccountKey), ctx, addr, tsk)
}

// StateGetActor mocks base method.
func (m *MockMessageReplaceAPI) StateGetActor(ctx context.Context, actor address.Address, tsk types.TipSetKey) (*types.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StateGetActor", ctx, actor, tsk)
	ret0, _ := ret[0].(*types.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StateGetActor indicates an expected call of StateGetActor.
func (mr *MockMessageReplaceAPIMockRecorder) StateGetActor(ctx, actor, tsk interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StateGetActor", reflect.TypeOf((*MockMessageReplaceAPI)(nil).StateGetActor), ctx, actor, tsk)
}

// StateMinerInfo mocks base method.
func (m *MockMessageReplaceAPI) StateMinerInfo(ctx context.Context, actor address.Address, tsk types.TipSetKey) (api.MinerInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StateMinerInfo", ctx, actor, tsk)
	ret0, _ := ret[0].(api.MinerInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StateMinerInfo indicates an expected call of StateMinerInfo.
func (mr *MockMessageReplaceAPIMockRecorder) StateMinerInfo(ctx, actor, tsk interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StateMinerInfo", reflect.TypeOf((*MockMessageReplaceAPI)(nil).StateMinerInfo), ctx, actor, tsk)
}

// WalletBalance mocks base method.
func (m *MockMessageReplaceAPI) WalletBalance(ctx context.Context, addr address.Address) (big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WalletBalance", ctx, addr)
	ret0, _ := ret[0].(big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WalletBalance indicates an expected call of WalletBalance.
func (mr *MockMessageReplaceAPIMockRecorder) WalletBalance(ctx, addr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WalletBalance", reflect.TypeOf((*MockMessageReplaceAPI)(nil).WalletBalance), ctx, addr)
}
