CREATE TABLE IF NOT EXISTS sectors_cc_scheduler (
    sp_id BIGINT NOT NULL,
    to_seal BIGINT NOT NULL,
    weight BIGINT NOT NULL DEFAULT 1000,
    duration_days BIGINT NOT NULL DEFAULT 182,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (sp_id)
);
