// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: cuzk/v1/proving.proto

package cuzk

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProvingEngine_SubmitProof_FullMethodName = "/cuzk.v1.ProvingEngine/SubmitProof"
	ProvingEngine_AwaitProof_FullMethodName  = "/cuzk.v1.ProvingEngine/AwaitProof"
	ProvingEngine_Prove_FullMethodName       = "/cuzk.v1.ProvingEngine/Prove"
	ProvingEngine_CancelProof_FullMethodName = "/cuzk.v1.ProvingEngine/CancelProof"
	ProvingEngine_GetStatus_FullMethodName   = "/cuzk.v1.ProvingEngine/GetStatus"
	ProvingEngine_GetMetrics_FullMethodName  = "/cuzk.v1.ProvingEngine/GetMetrics"
	ProvingEngine_PreloadSRS_FullMethodName  = "/cuzk.v1.ProvingEngine/PreloadSRS"
	ProvingEngine_EvictSRS_FullMethodName    = "/cuzk.v1.ProvingEngine/EvictSRS"
)

// ProvingEngineClient is the client API for ProvingEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProvingEngineClient interface {
	// Submit a proof request. Returns immediately with a job ID.
	SubmitProof(ctx context.Context, in *SubmitProofRequest, opts ...grpc.CallOption) (*SubmitProofResponse, error)
	// Block until a submitted proof completes or is cancelled.
	AwaitProof(ctx context.Context, in *AwaitProofRequest, opts ...grpc.CallOption) (*AwaitProofResponse, error)
	// Submit + Await in one call (convenience for synchronous clients).
	Prove(ctx context.Context, in *ProveRequest, opts ...grpc.CallOption) (*ProveResponse, error)
	// Cancel a pending or in-progress proof.
	CancelProof(ctx context.Context, in *CancelProofRequest, opts ...grpc.CallOption) (*CancelProofResponse, error)
	// Query daemon capabilities, loaded SRS, GPU status.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// Prometheus-compatible metrics snapshot.
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error)
	// Explicitly load an SRS into hot tier (pre-warm before proofs arrive).
	PreloadSRS(ctx context.Context, in *PreloadSrsRequest, opts ...grpc.CallOption) (*PreloadSrsResponse, error)
	// Explicitly evict an SRS from hot tier.
	EvictSRS(ctx context.Context, in *EvictSrsRequest, opts ...grpc.CallOption) (*EvictSrsResponse, error)
}

type provingEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewProvingEngineClient(cc grpc.ClientConnInterface) ProvingEngineClient {
	return &provingEngineClient{cc}
}

func (c *provingEngineClient) SubmitProof(ctx context.Context, in *SubmitProofRequest, opts ...grpc.CallOption) (*SubmitProofResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitProofResponse)
	err := c.cc.Invoke(ctx, ProvingEngine_SubmitProof_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provingEngineClient) AwaitProof(ctx context.Context, in *AwaitProofRequest, opts ...grpc.CallOption) (*AwaitProofResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AwaitProofResponse)
	err := c.cc.Invoke(ctx, ProvingEngine_AwaitProof_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provingEngineClient) Prove(ctx context.Context, in *ProveRequest, opts ...grpc.CallOption) (*ProveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProveResponse)
	err := c.cc.Invoke(ctx, ProvingEngine_Prove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provingEngineClient) CancelProof(ctx context.Context, in *CancelProofRequest, opts ...grpc.CallOption) (*CancelProofResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelProofResponse)
	err := c.cc.Invoke(ctx, ProvingEngine_CancelProof_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provingEngineClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, ProvingEngine_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provingEngineClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetricsResponse)
	err := c.cc.Invoke(ctx, ProvingEngine_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provingEngineClient) PreloadSRS(ctx context.Context, in *PreloadSrsRequest, opts ...grpc.CallOption) (*PreloadSrsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreloadSrsResponse)
	err := c.cc.Invoke(ctx, ProvingEngine_PreloadSRS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provingEngineClient) EvictSRS(ctx context.Context, in *EvictSrsRequest, opts ...grpc.CallOption) (*EvictSrsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvictSrsResponse)
	err := c.cc.Invoke(ctx, ProvingEngine_EvictSRS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProvingEngineServer is the server API for ProvingEngine service.
// All implementations must embed UnimplementedProvingEngineServer
// for forward compatibility.
type ProvingEngineServer interface {
	// Submit a proof request. Returns immediately with a job ID.
	SubmitProof(context.Context, *SubmitProofRequest) (*SubmitProofResponse, error)
	// Block until a submitted proof completes or is cancelled.
	AwaitProof(context.Context, *AwaitProofRequest) (*AwaitProofResponse, error)
	// Submit + Await in one call (convenience for synchronous clients).
	Prove(context.Context, *ProveRequest) (*ProveResponse, error)
	// Cancel a pending or in-progress proof.
	CancelProof(context.Context, *CancelProofRequest) (*CancelProofResponse, error)
	// Query daemon capabilities, loaded SRS, GPU status.
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// Prometheus-compatible metrics snapshot.
	GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error)
	// Explicitly load an SRS into hot tier (pre-warm before proofs arrive).
	PreloadSRS(context.Context, *PreloadSrsRequest) (*PreloadSrsResponse, error)
	// Explicitly evict an SRS from hot tier.
	EvictSRS(context.Context, *EvictSrsRequest) (*EvictSrsResponse, error)
	mustEmbedUnimplementedProvingEngineServer()
}

// UnimplementedProvingEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProvingEngineServer struct{}

func (UnimplementedProvingEngineServer) SubmitProof(context.Context, *SubmitProofRequest) (*SubmitProofResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitProof not implemented")
}
func (UnimplementedProvingEngineServer) AwaitProof(context.Context, *AwaitProofRequest) (*AwaitProofResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AwaitProof not implemented")
}
func (UnimplementedProvingEngineServer) Prove(context.Context, *ProveRequest) (*ProveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Prove not implemented")
}
func (UnimplementedProvingEngineServer) CancelProof(context.Context, *CancelProofRequest) (*CancelProofResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelProof not implemented")
}
func (UnimplementedProvingEngineServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedProvingEngineServer) GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedProvingEngineServer) PreloadSRS(context.Context, *PreloadSrsRequest) (*PreloadSrsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PreloadSRS not implemented")
}
func (UnimplementedProvingEngineServer) EvictSRS(context.Context, *EvictSrsRequest) (*EvictSrsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvictSRS not implemented")
}
func (UnimplementedProvingEngineServer) mustEmbedUnimplementedProvingEngineServer() {}
func (UnimplementedProvingEngineServer) testEmbeddedByValue()                       {}

// UnsafeProvingEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProvingEngineServer will
// result in compilation errors.
type UnsafeProvingEngineServer interface {
	mustEmbedUnimplementedProvingEngineServer()
}

func RegisterProvingEngineServer(s grpc.ServiceRegistrar, srv ProvingEngineServer) {
	// If the following call panics, it indicates UnimplementedProvingEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProvingEngine_ServiceDesc, srv)
}

func _ProvingEngine_SubmitProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvingEngineServer).SubmitProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvingEngine_SubmitProof_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvingEngineServer).SubmitProof(ctx, req.(*SubmitProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvingEngine_AwaitProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AwaitProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvingEngineServer).AwaitProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvingEngine_AwaitProof_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvingEngineServer).AwaitProof(ctx, req.(*AwaitProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvingEngine_Prove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvingEngineServer).Prove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvingEngine_Prove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvingEngineServer).Prove(ctx, req.(*ProveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvingEngine_CancelProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvingEngineServer).CancelProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvingEngine_CancelProof_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvingEngineServer).CancelProof(ctx, req.(*CancelProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvingEngine_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvingEngineServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvingEngine_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvingEngineServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvingEngine_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvingEngineServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvingEngine_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvingEngineServer).GetMetrics(ctx, req.(*GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvingEngine_PreloadSRS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreloadSrsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvingEngineServer).PreloadSRS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvingEngine_PreloadSRS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvingEngineServer).PreloadSRS(ctx, req.(*PreloadSrsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvingEngine_EvictSRS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvictSrsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvingEngineServer).EvictSRS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvingEngine_EvictSRS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvingEngineServer).EvictSRS(ctx, req.(*EvictSrsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProvingEngine_ServiceDesc is the grpc.ServiceDesc for ProvingEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProvingEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cuzk.v1.ProvingEngine",
	HandlerType: (*ProvingEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitProof",
			Handler:    _ProvingEngine_SubmitProof_Handler,
		},
		{
			MethodName: "AwaitProof",
			Handler:    _ProvingEngine_AwaitProof_Handler,
		},
		{
			MethodName: "Prove",
			Handler:    _ProvingEngine_Prove_Handler,
		},
		{
			MethodName: "CancelProof",
			Handler:    _ProvingEngine_CancelProof_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _ProvingEngine_GetStatus_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _ProvingEngine_GetMetrics_Handler,
		},
		{
			MethodName: "PreloadSRS",
			Handler:    _ProvingEngine_PreloadSRS_Handler,
		},
		{
			MethodName: "EvictSRS",
			Handler:    _ProvingEngine_EvictSRS_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cuzk/v1/proving.proto",
}
