// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: cuzk/v1/proving.proto

package cuzk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProofKind int32

const (
	ProofKind_PROOF_KIND_UNSPECIFIED ProofKind = 0
	ProofKind_POREP_SEAL_COMMIT      ProofKind = 1
	ProofKind_SNAP_DEALS_UPDATE      ProofKind = 2
	ProofKind_WINDOW_POST_PARTITION  ProofKind = 3
	ProofKind_WINNING_POST           ProofKind = 4
)

// Enum value maps for ProofKind.
var (
	ProofKind_name = map[int32]string{
		0: "PROOF_KIND_UNSPECIFIED",
		1: "POREP_SEAL_COMMIT",
		2: "SNAP_DEALS_UPDATE",
		3: "WINDOW_POST_PARTITION",
		4: "WINNING_POST",
	}
	ProofKind_value = map[string]int32{
		"PROOF_KIND_UNSPECIFIED": 0,
		"POREP_SEAL_COMMIT":      1,
		"SNAP_DEALS_UPDATE":      2,
		"WINDOW_POST_PARTITION":  3,
		"WINNING_POST":           4,
	}
)

func (x ProofKind) Enum() *ProofKind {
	p := new(ProofKind)
	*p = x
	return p
}

func (x ProofKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProofKind) Descriptor() protoreflect.EnumDescriptor {
	return file_cuzk_v1_proving_proto_enumTypes[0].Descriptor()
}

func (ProofKind) Type() protoreflect.EnumType {
	return &file_cuzk_v1_proving_proto_enumTypes[0]
}

func (x ProofKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProofKind.Descriptor instead.
func (ProofKind) EnumDescriptor() ([]byte, []int) {
	return file_cuzk_v1_proving_proto_rawDescGZIP(), []int{0}
}

type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_LOW                  Priority = 1
	Priority_NORMAL               Priority = 2
	Priority_HIGH                 Priority = 3
	Priority_CRITICAL             Priority = 4 // WinningPoSt: must complete within epoch
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "LOW",
		2: "NORMAL",
		3: "HIGH",
		4: "CRITICAL",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"LOW":                  1,
		"NORMAL":               2,
		"HIGH":                 3,
		"CRITICAL":             4,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_cuzk_v1_proving_proto_enumTypes[1].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_cuzk_v1_proving_proto_enumTypes[1]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_cuzk_v1_proving_proto_rawDescGZIP(), []int{1}
}

type AwaitProofResponse_Status int32

const (
	AwaitProofResponse_UNKNOWN   AwaitProofResponse_Status = 0
	AwaitProofResponse_COMPLETED AwaitProofResponse_Status = 1
	AwaitProofResponse_FAILED    AwaitProofResponse_Status = 2
	AwaitProofResponse_CANCELLED AwaitProofResponse_Status = 3
	AwaitProofResponse_TIMEOUT   AwaitProofResponse_Status = 4
)

// Enum value maps for AwaitProofResponse_Status.
var (
	AwaitProofResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "COMPLETED",
		2: "FAILED",
		3: "CANCELLED",
		4: "TIMEOUT",
	}
	AwaitProofResponse_Status_value = map[string]int32{
		"UNKNOWN":   0,
		"COMPLETED": 1,
		"FAILED":    2,
		"CANCELLED": 3,
		"TIMEOUT":   4,
	}
)

func (x AwaitProofResponse_Status) Enum() *AwaitProofResponse_Status {
	p := new(AwaitProofResponse_Status)
	*p = x
	return p
}

func (x AwaitProofResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AwaitProofResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_cuzk_v1_proving_proto_enumTypes[2].Descriptor()
}

func (AwaitProofResponse_Status) Type() protoreflect.EnumType {
	return &file_cuzk_v1_proving_proto_enumTypes[2]
}

func (x AwaitProofResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AwaitProofResponse_Status.Descriptor instead.
func (AwaitProofResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_cuzk_v1_proving_proto_rawDescGZIP(), []int{3, 0}
}

type SRSStatus_Tier int32

const (
	SRSStatus_HOT  SRSStatus_Tier = 0 // CUDA pinned, ready for proving
	SRSStatus_WARM SRSStatus_Tier = 1 // mmap'd / page cache, needs re-pin
	SRSStatus_COLD SRSStatus_Tier = 2 // on disk only
)

// Enum value maps for SRSStatus_Tier.
var (
	SRSStatus_Tier_name = map[int32]string{
		0: "HOT",
		1: "WARM",
		2: "COLD",
	}
	SRSStatus_Tier_value = map[string]int32{
		"HOT":  0,
		"WARM": 1,
		"COLD": 2,
	}
)

func (x SRSStatus_Tier) Enum() *SRSStatus_Tier {
	p := new(SRSStatus_Tier)
	*p = x
	return p
}

func (x SRSStatus_Tier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SRSStatus_Tier) Descriptor() protoreflect.EnumDescriptor {
	return file_cuzk_v1_proving_proto_enumTypes[3].Descriptor()
}

func (SRSStatus_Tier) Type() protoreflect.EnumType {
	return &file_cuzk_v1_proving_proto_enumTypes[3]
}

func (x SRSStatus_Tier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SRSStatus_Tier.Descriptor instead.
func (SRSStatus_Tier) EnumDescriptor() ([]byte, []int) {
	return file_cuzk_v1_proving_proto_rawDescGZIP(), []int{11, 0}
}

type SubmitProofRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // caller-provided idempotency key
	ProofKind       ProofKind              `protobuf:"varint,2,opt,name=proof_kind,json=proofKind,proto3,enum=cuzk.v1.ProofKind" json:"proof_kind,omitempty"`
	SectorSize      uint64                 `protobuf:"varint,3,opt,name=sector_size,json=sectorSize,proto3" json:"sector_size,omitempty"`                // e.g. 34359738368 for 32 GiB
	RegisteredProof uint64                 `protobuf:"varint,4,opt,name=registered_proof,json=registeredProof,proto3" json:"registered_proof,omitempty"` // numeric RegisteredSealProof / RegisteredPoStProof / RegisteredUpdateProof
	Priority        Priority               `protobuf:"varint,5,opt,name=priority,proto3,enum=cuzk.v1.Priority" json:"priority,omitempty"`
	// For PoRep C2: single monolithic C1 output (JSON, ~50 MB for 32 GiB).
	VanillaProof []byte `protobuf:"bytes,10,opt,name=vanilla_proof,json=vanillaProof,proto3" json:"vanilla_proof,omitempty"`
	// For PoSt / SnapDeals: multiple vanilla proofs (one per sector or partition).
	// PoSt: one bincode-serialized FallbackPoStSectorProof per sector.
	// SnapDeals: one bincode-serialized PartitionProof per partition.
	VanillaProofs  [][]byte `protobuf:"bytes,11,rep,name=vanilla_proofs,json=vanillaProofs,proto3" json:"vanilla_proofs,omitempty"`
	SectorNumber   uint64   `protobuf:"varint,20,opt,name=sector_number,json=sectorNumber,proto3" json:"sector_number,omitempty"`
	MinerId        uint64   `protobuf:"varint,21,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	Randomness     []byte   `protobuf:"bytes,22,opt,name=randomness,proto3" json:"randomness,omitempty"`                                // 32-byte ChallengeSeed for PoSt
	PartitionIndex uint32   `protobuf:"varint,23,opt,name=partition_index,json=partitionIndex,proto3" json:"partition_index,omitempty"` // for WindowPoSt per-partition
	// For SnapDeals: commitments as raw 32-byte arrays
	CommROld      []byte `protobuf:"bytes,30,opt,name=comm_r_old,json=commROld,proto3" json:"comm_r_old,omitempty"` // original sealed commitment (was sector_key_cid)
	CommRNew      []byte `protobuf:"bytes,31,opt,name=comm_r_new,json=commRNew,proto3" json:"comm_r_new,omitempty"` // new sealed commitment (was new_sealed_cid)
	CommDNew      []byte `protobuf:"bytes,32,opt,name=comm_d_new,json=commDNew,proto3" json:"comm_d_new,omitempty"` // new data commitment (was new_unsealed_cid)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitProofRequest) Reset() {
	*x = SubmitProofRequest{}
	mi := &file_cuzk_v1_proving_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitProofRequest) ProtoMessage() {}

func (x *SubmitProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cuzk_v1_proving_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitProofRequest.ProtoReflect.Descriptor instead.
func (*SubmitProofRequest) Descriptor() ([]byte, []int) {
	return file_cuzk_v1_proving_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitProofRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SubmitProofRequest) GetProofKind() ProofKind {
	if x != nil {
		return x.ProofKind
	}
	return ProofKind_PROOF_KIND_UNSPECIFIED
}

func (x *SubmitProofRequest) GetSectorSize() uint64 {
	if x != nil {
		return x.SectorSize
	}
	return 0
}

func (x *SubmitProofRequest) GetRegisteredProof() uint64 {
	if x != nil {
		return x.RegisteredProof
	}
	return 0
}

func (x *SubmitProofRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *SubmitProofRequest) GetVanillaProof() []byte {
	if x != nil {
		return x.VanillaProof
	}
	return nil
}

func (x *SubmitProofRequest) GetVanillaProofs() [][]byte {
	if x != nil {
		return x.VanillaProofs
	}
	return nil
}

func (x *SubmitProofRequest) GetSectorNumber() uint64 {
	if x != nil {
		return x.SectorNumber
	}
	return 0
}

func (x *SubmitProofRequest) GetMinerId() uint64 {
	if x != nil {
		return x.MinerId
	}
	return 0
}

func (x *SubmitProofRequest) GetRandomness() []byte {
	if x != nil {
		return x.Randomness
	}
	return nil
}

func (x *SubmitProofRequest) GetPartitionIndex() uint32 {
	if x != nil {
		return x.PartitionIndex
	}
	return 0
}

func (x *SubmitProofRequest) GetCommROld() []byte {
	if x != nil {
		return x.CommROld
	}
	return nil
}

func (x *SubmitProofRequest) GetCommRNew() []byte {
	if x != nil {
		return x.CommRNew
	}
	return nil
}

func (x *SubmitProofRequest) GetCommDNew() []byte {
	if x != nil {
		return x.CommDNew
	}
	return nil
}

type SubmitProofResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	QueuePosition uint32                 `protobuf:"varint,2,opt,name=queue_position,json=queuePosition,proto3" json:"queue_position,omitempty"`
	AssignedGpu   string                 `protobuf:"bytes,3,opt,name=assigned_gpu,json=assignedGpu,proto3" json:"assigned_gpu,omitempty"` // empty if not yet assigned
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitProofResponse) Reset() {
	*x = SubmitProofResponse{}
	mi := &file_cuzk_v1_proving_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitProofResponse) ProtoMessage() {}

func (x *SubmitProofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cuzk_v1_proving_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitProofResponse.ProtoReflect.Descriptor instead.
func (*SubmitProofResponse) Descriptor() ([]byte, []int) {
	return file_cuzk_v1_proving_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitProofResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SubmitProofResponse) GetQueuePosition() uint32 {
	if x != nil {
		return x.QueuePosition
	}
	return 0
}

func (x *SubmitProofResponse) GetAssignedGpu() string {
	if x != nil {
		return x.AssignedGpu
	}
	return ""
}

type AwaitProofRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TimeoutMs     uint64                 `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"` // 0 = wait forever
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwaitProofRequest) Reset() {
	*x = AwaitProofRequest{}
	mi := &file_cuzk_v1_proving_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwaitProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwaitProofRequest) ProtoMessage() {}

func (x *AwaitProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cuzk_v1_proving_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwaitProofRequest.ProtoReflect.Descriptor instead.
func (*AwaitProofRequest) Descriptor() ([]byte, []int) {
	return file_cuzk_v1_proving_proto_rawDescGZIP(), []int{2}
}

func (x *AwaitProofRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AwaitProofRequest) GetTimeoutMs() uint64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type AwaitProofResponse struct {
	state        protoimpl.MessageState    `protogen:"open.v1"`
	JobId        string                    `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status       AwaitProofResponse_Status `protobuf:"varint,2,opt,name=status,proto3,enum=cuzk.v1.AwaitProofResponse_Status" json:"status,omitempty"`
	Proof        []byte                    `protobuf:"bytes,3,opt,name=proof,proto3" json:"proof,omitempty"` // serialized Groth16 proof bytes
	ErrorMessage string                    `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Timing
	QueueWaitMs   uint64 `protobuf:"varint,10,opt,name=queue_wait_ms,json=queueWaitMs,proto3" json:"queue_wait_ms,omitempty"`
	SrsLoadMs     uint64 `protobuf:"varint,11,opt,name=srs_load_ms,json=srsLoadMs,proto3" json:"srs_load_ms,omitempty"`
	SynthesisMs   uint64 `protobuf:"varint,12,opt,name=synthesis_ms,json=synthesisMs,proto3" json:"synthesis_ms,omitempty"`
	GpuComputeMs  uint64 `protobuf:"varint,13,opt,name=gpu_compute_ms,json=gpuComputeMs,proto3" json:"gpu_compute_ms,omitempty"`
	TotalMs       uint64 `protobuf:"varint,14,opt,name=total_ms,json=totalMs,proto3" json:"total_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwaitProofResponse) Reset() {
	*x = AwaitProofResponse{}
	mi := &file_cuzk_v1_proving_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwaitProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwaitProofResponse) ProtoMessage() {}

func (x *AwaitProofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cuzk_v1_proving_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwaitProofResponse.ProtoReflect.Descriptor instead.
func (*AwaitProofResponse) Descriptor() ([]byte, []int) {
	return file_cuzk_v1_proving_proto_rawDescGZIP(), []int{3}
}

func (x *AwaitProofResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AwaitProofResponse) GetStatus() AwaitProofResponse_Status {
	if x != nil {
		return x.Status
	}
	return AwaitProofResponse_UNKNOWN
}

func (x *AwaitProofResponse) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *AwaitProofResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *AwaitProofResponse) GetQueueWaitMs() uint64 {
	if x != nil {
		return x.QueueWaitMs
	}
	return 0
}

func (x *AwaitProofResponse) GetSrsLoadMs() uint64 {
	if x != nil {
		return x.SrsLoadMs
	}
	return 0
}

func (x *AwaitProofResponse) GetSynthesisMs() uint64 {
	if x != nil {
		return x.SynthesisMs
	}
	return 0
}

func (x *AwaitProofResponse) GetGpuComputeMs() uint64 {
	if x != nil {
		return x.GpuComputeMs
	}
	return 0
}

func (x *AwaitProofResponse) GetTotalMs() uint64 {
	if x != nil {
		return x.TotalMs
	}
	return 0
}

type ProveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Submit        *SubmitProofRequest    `protobuf:"bytes,1,opt,name=submit,proto3" json:"submit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProveRequest) Reset() {
	*x = ProveRequest{}
	mi := &file_cuzk_v1_proving_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProveRequest) ProtoMessage() {}

func (x *ProveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cuzk_v1_proving_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProveRequest.ProtoReflect.Descriptor instead.
func (*ProveRequest) Descriptor() ([]byte, []int) {
	return file_cuzk_v1_proving_proto_rawDescGZIP(), []int{4}
}

func (x *ProveRequest) GetSubmit() *SubmitProofRequest {
	if x != nil {
		return x.Submit
	}
	return nil
}

type ProveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *AwaitProofResponse    `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProveResponse) Reset() {
	*x = ProveResponse{}
	mi := &file_cuzk_v1_proving_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProveResponse) ProtoMessage() {}

func (x *ProveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cuzk_v1_proving_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProveResponse.ProtoReflect.Descriptor instead.
func (*ProveResponse) Descriptor() ([]byte, []int) {
	return file_cuzk_v1_proving_proto_rawDescGZIP(), []int{5}
}

func (x *ProveResponse) GetResult() *AwaitProofResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

type CancelProofRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelProofRequest) Reset() {
	*x = CancelProofRequest{}
	mi := &file_cuzk_v1_proving_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelProofRequest) ProtoMessage() {}

func (x *CancelProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cuzk_v1_proving_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelProofRequest.ProtoReflect.Descriptor instead.
func (*CancelProofRequest) Descriptor() ([]byte, []int) {
	return file_cuzk_v1_proving_proto_rawDescGZIP(), []int{6}
}

func (x *CancelProofRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelProofResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WasRunning    bool                   `protobuf:"varint,1,opt,name=was_running,json=wasRunning,proto3" json:"was_running,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelProofResponse) Reset() {
	*x = CancelProofResponse{}
	mi := &file_cuzk_v1_proving_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelProofResponse) ProtoMessage() {}

func (x *CancelProofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cuzk_v1_proving_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelProofResponse.ProtoReflect.Descriptor instead.
func (*CancelProofResponse) Descriptor() ([]byte, []int) {
	return file_cuzk_v1_proving_proto_rawDescGZIP(), []int{7}
}

func (x *CancelProofResponse) GetWasRunning() bool {
	if x != nil {
		return x.WasRunning
	}
	return false
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_cuzk_v1_proving_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cuzk_v1_proving_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_cuzk_v1_proving_proto_rawDescGZIP(), []int{8}
}

type GetStatusResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Gpus                   []*GPUStatus           `protobuf:"bytes,1,rep,name=gpus,proto3" json:"gpus,omitempty"`
	LoadedSrs              []*SRSStatus           `protobuf:"bytes,2,rep,name=loaded_srs,json=loadedSrs,proto3" json:"loaded_srs,omitempty"`
	Queues                 []*QueueStatus         `protobuf:"bytes,3,rep,name=queues,proto3" json:"queues,omitempty"`
	TotalProofsCompleted   uint64                 `protobuf:"varint,4,opt,name=total_proofs_completed,json=totalProofsCompleted,proto3" json:"total_proofs_completed,omitempty"`
	TotalProofsFailed      uint64                 `protobuf:"varint,5,opt,name=total_proofs_failed,json=totalProofsFailed,proto3" json:"total_proofs_failed,omitempty"`
	UptimeSeconds          uint64                 `protobuf:"varint,6,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	PinnedMemoryBytes      uint64                 `protobuf:"varint,7,opt,name=pinned_memory_bytes,json=pinnedMemoryBytes,proto3" json:"pinned_memory_bytes,omitempty"`
	PinnedMemoryLimitBytes uint64                 `protobuf:"varint,8,opt,name=pinned_memory_limit_bytes,json=pinnedMemoryLimitBytes,proto3" json:"pinned_memory_limit_bytes,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_cuzk_v1_proving_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cuzk_v1_proving_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_cuzk_v1_proving_proto_rawDescGZIP(), []int{9}
}

func (x *GetStatusResponse) GetGpus() []*GPUStatus {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *GetStatusResponse) GetLoadedSrs() []*SRSStatus {
	if x != nil {
		return x.LoadedSrs
	}
	return nil
}

func (x *GetStatusResponse) GetQueues() []*QueueStatus {
	if x != nil {
		return x.Queues
	}
	return nil
}

func (x *GetStatusResponse) GetTotalProofsCompleted() uint64 {
	if x != nil {
		return x.TotalProofsCompleted
	}
	return 0
}

func (x *GetStatusResponse) GetTotalProofsFailed() uint64 {
	if x != nil {
		return x.TotalProofsFailed
	}
	return 0
}

func (x *GetStatusResponse) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *GetStatusResponse) GetPinnedMemoryBytes() uint64 {
	if x != nil {
		return x.PinnedMemoryBytes
	}
	return 0
}

func (x *GetStatusResponse) GetPinnedMemoryLimitBytes() uint64 {
	if x != nil {
		return x.PinnedMemoryLimitBytes
	}
	return 0
}

type GPUStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ordinal          uint32                 `protobuf:"varint,1,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	VramTotalBytes   uint64                 `protobuf:"varint,3,opt,name=vram_total_bytes,json=vramTotalBytes,proto3" json:"vram_total_bytes,omitempty"`
	VramFreeBytes    uint64                 `protobuf:"varint,4,opt,name=vram_free_bytes,json=vramFreeBytes,proto3" json:"vram_free_bytes,omitempty"`
	CurrentJobId     string                 `protobuf:"bytes,5,opt,name=current_job_id,json=currentJobId,proto3" json:"current_job_id,omitempty"`
	CurrentProofKind string                 `protobuf:"bytes,6,opt,name=current_proof_kind,json=currentProofKind,proto3" json:"current_proof_kind,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GPUStatus) Reset() {
	*x = GPUStatus{}
	mi := &file_cuzk_v1_proving_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUStatus) ProtoMessage() {}

func (x *GPUStatus) ProtoReflect() protoreflect.Message {
	mi := &file_cuzk_v1_proving_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUStatus.ProtoReflect.Descriptor instead.
func (*GPUStatus) Descriptor() ([]byte, []int) {
	return file_cuzk_v1_proving_proto_rawDescGZIP(), []int{10}
}

func (x *GPUStatus) GetOrdinal() uint32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *GPUStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GPUStatus) GetVramTotalBytes() uint64 {
	if x != nil {
		return x.VramTotalBytes
	}
	return 0
}

func (x *GPUStatus) GetVramFreeBytes() uint64 {
	if x != nil {
		return x.VramFreeBytes
	}
	return 0
}

func (x *GPUStatus) GetCurrentJobId() string {
	if x != nil {
		return x.CurrentJobId
	}
	return ""
}

func (x *GPUStatus) GetCurrentProofKind() string {
	if x != nil {
		return x.CurrentProofKind
	}
	return ""
}

type SRSStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CircuitId     string                 `protobuf:"bytes,1,opt,name=circuit_id,json=circuitId,proto3" json:"circuit_id,omitempty"` // e.g. "porep-32g", "wpost-32g", "winning-32g", "snap-32g"
	Tier          SRSStatus_Tier         `protobuf:"varint,2,opt,name=tier,proto3,enum=cuzk.v1.SRSStatus_Tier" json:"tier,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	RefCount      uint32                 `protobuf:"varint,4,opt,name=ref_count,json=refCount,proto3" json:"ref_count,omitempty"` // in-flight proofs using this SRS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SRSStatus) Reset() {
	*x = SRSStatus{}
	mi := &file_cuzk_v1_proving_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SRSStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRSStatus) ProtoMessage() {}

func (x *SRSStatus) ProtoReflect() protoreflect.Message {
	mi := &file_cuzk_v1_proving_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRSStatus.ProtoReflect.Descriptor instead.
func (*SRSStatus) Descriptor() ([]byte, []int) {
	return file_cuzk_v1_proving_proto_rawDescGZIP(), []int{11}
}

func (x *SRSStatus) GetCircuitId() string {
	if x != nil {
		return x.CircuitId
	}
	return ""
}

func (x *SRSStatus) GetTier() SRSStatus_Tier {
	if x != nil {
		return x.Tier
	}
	return SRSStatus_HOT
}

func (x *SRSStatus) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *SRSStatus) GetRefCount() uint32 {
	if x != nil {
		return x.RefCount
	}
	return 0
}

type QueueStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProofKind     string                 `protobuf:"bytes,1,opt,name=proof_kind,json=proofKind,proto3" json:"proof_kind,omitempty"`
	Pending       uint32                 `protobuf:"varint,2,opt,name=pending,proto3" json:"pending,omitempty"`
	InProgress    uint32                 `protobuf:"varint,3,opt,name=in_progress,json=inProgress,proto3" json:"in_progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueStatus) Reset() {
	*x = QueueStatus{}
	mi := &file_cuzk_v1_proving_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatus) ProtoMessage() {}

func (x *QueueStatus) ProtoReflect() protoreflect.Message {
	mi := &file_cuzk_v1_proving_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatus.ProtoReflect.Descriptor instead.
func (*QueueStatus) Descriptor() ([]byte, []int) {
	return file_cuzk_v1_proving_proto_rawDescGZIP(), []int{12}
}

func (x *QueueStatus) GetProofKind() string {
	if x != nil {
		return x.ProofKind
	}
	return ""
}

func (x *QueueStatus) GetPending() uint32 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *QueueStatus) GetInProgress() uint32 {
	if x != nil {
		return x.InProgress
	}
	return 0
}

type PreloadSrsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CircuitId     string                 `protobuf:"bytes,1,opt,name=circuit_id,json=circuitId,proto3" json:"circuit_id,omitempty"` // e.g. "porep-32g"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreloadSrsRequest) Reset() {
	*x = PreloadSrsRequest{}
	mi := &file_cuzk_v1_proving_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreloadSrsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreloadSrsRequest) ProtoMessage() {}

func (x *PreloadSrsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cuzk_v1_proving_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreloadSrsRequest.ProtoReflect.Descriptor instead.
func (*PreloadSrsRequest) Descriptor() ([]byte, []int) {
	return file_cuzk_v1_proving_proto_rawDescGZIP(), []int{13}
}

func (x *PreloadSrsRequest) GetCircuitId() string {
	if x != nil {
		return x.CircuitId
	}
	return ""
}

type PreloadSrsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlreadyLoaded bool                   `protobuf:"varint,1,opt,name=already_loaded,json=alreadyLoaded,proto3" json:"already_loaded,omitempty"`
	LoadTimeMs    uint64                 `protobuf:"varint,2,opt,name=load_time_ms,json=loadTimeMs,proto3" json:"load_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreloadSrsResponse) Reset() {
	*x = PreloadSrsResponse{}
	mi := &file_cuzk_v1_proving_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreloadSrsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreloadSrsResponse) ProtoMessage() {}

func (x *PreloadSrsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cuzk_v1_proving_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreloadSrsResponse.ProtoReflect.Descriptor instead.
func (*PreloadSrsResponse) Descriptor() ([]byte, []int) {
	return file_cuzk_v1_proving_proto_rawDescGZIP(), []int{14}
}

func (x *PreloadSrsResponse) GetAlreadyLoaded() bool {
	if x != nil {
		return x.AlreadyLoaded
	}
	return false
}

func (x *PreloadSrsResponse) GetLoadTimeMs() uint64 {
	if x != nil {
		return x.LoadTimeMs
	}
	return 0
}

type EvictSrsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CircuitId     string                 `protobuf:"bytes,1,opt,name=circuit_id,json=circuitId,proto3" json:"circuit_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvictSrsRequest) Reset() {
	*x = EvictSrsRequest{}
	mi := &file_cuzk_v1_proving_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvictSrsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictSrsRequest) ProtoMessage() {}

func (x *EvictSrsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cuzk_v1_proving_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictSrsRequest.ProtoReflect.Descriptor instead.
func (*EvictSrsRequest) Descriptor() ([]byte, []int) {
	return file_cuzk_v1_proving_proto_rawDescGZIP(), []int{15}
}

func (x *EvictSrsRequest) GetCircuitId() string {
	if x != nil {
		return x.CircuitId
	}
	return ""
}

type EvictSrsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WasLoaded     bool                   `protobuf:"varint,1,opt,name=was_loaded,json=wasLoaded,proto3" json:"was_loaded,omitempty"`
	FreedBytes    uint64                 `protobuf:"varint,2,opt,name=freed_bytes,json=freedBytes,proto3" json:"freed_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvictSrsResponse) Reset() {
	*x = EvictSrsResponse{}
	mi := &file_cuzk_v1_proving_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvictSrsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictSrsResponse) ProtoMessage() {}

func (x *EvictSrsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cuzk_v1_proving_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictSrsResponse.ProtoReflect.Descriptor instead.
func (*EvictSrsResponse) Descriptor() ([]byte, []int) {
	return file_cuzk_v1_proving_proto_rawDescGZIP(), []int{16}
}

func (x *EvictSrsResponse) GetWasLoaded() bool {
	if x != nil {
		return x.WasLoaded
	}
	return false
}

func (x *EvictSrsResponse) GetFreedBytes() uint64 {
	if x != nil {
		return x.FreedBytes
	}
	return 0
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_cuzk_v1_proving_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cuzk_v1_proving_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_cuzk_v1_proving_proto_rawDescGZIP(), []int{17}
}

type GetMetricsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PrometheusText string                 `protobuf:"bytes,1,opt,name=prometheus_text,json=prometheusText,proto3" json:"prometheus_text,omitempty"` // Prometheus exposition format
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_cuzk_v1_proving_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cuzk_v1_proving_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_cuzk_v1_proving_proto_rawDescGZIP(), []int{18}
}

func (x *GetMetricsResponse) GetPrometheusText() string {
	if x != nil {
		return x.PrometheusText
	}
	return ""
}

var File_cuzk_v1_proving_proto protoreflect.FileDescriptor

const file_cuzk_v1_proving_proto_rawDesc = "" +
	"\n" +
	"\x15cuzk/v1/proving.proto\x12\acuzk.v1\"\x90\x04\n" +
	"\x12SubmitProofRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x121\n" +
	"\n" +
	"proof_kind\x18\x02 \x01(\x0e2\x12.cuzk.v1.ProofKindR\tproofKind\x12\x1f\n" +
	"\vsector_size\x18\x03 \x01(\x04R\n" +
	"sectorSize\x12)\n" +
	"\x10registered_proof\x18\x04 \x01(\x04R\x0fregisteredProof\x12-\n" +
	"\bpriority\x18\x05 \x01(\x0e2\x11.cuzk.v1.PriorityR\bpriority\x12#\n" +
	"\rvanilla_proof\x18\n" +
	" \x01(\fR\fvanillaProof\x12%\n" +
	"\x0evanilla_proofs\x18\v \x03(\fR\rvanillaProofs\x12#\n" +
	"\rsector_number\x18\x14 \x01(\x04R\fsectorNumber\x12\x19\n" +
	"\bminer_id\x18\x15 \x01(\x04R\aminerId\x12\x1e\n" +
	"\n" +
	"randomness\x18\x16 \x01(\fR\n" +
	"randomness\x12'\n" +
	"\x0fpartition_index\x18\x17 \x01(\rR\x0epartitionIndex\x12\x1c\n" +
	"\n" +
	"comm_r_old\x18\x1e \x01(\fR\bcommROld\x12\x1c\n" +
	"\n" +
	"comm_r_new\x18\x1f \x01(\fR\bcommRNew\x12\x1c\n" +
	"\n" +
	"comm_d_new\x18  \x01(\fR\bcommDNew\"v\n" +
	"\x13SubmitProofResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12%\n" +
	"\x0equeue_position\x18\x02 \x01(\rR\rqueuePosition\x12!\n" +
	"\fassigned_gpu\x18\x03 \x01(\tR\vassignedGpu\"I\n" +
	"\x11AwaitProofRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\x04R\ttimeoutMs\"\x98\x03\n" +
	"\x12AwaitProofResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12:\n" +
	"\x06status\x18\x02 \x01(\x0e2\".cuzk.v1.AwaitProofResponse.StatusR\x06status\x12\x14\n" +
	"\x05proof\x18\x03 \x01(\fR\x05proof\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\"\n" +
	"\rqueue_wait_ms\x18\n" +
	" \x01(\x04R\vqueueWaitMs\x12\x1e\n" +
	"\vsrs_load_ms\x18\v \x01(\x04R\tsrsLoadMs\x12!\n" +
	"\fsynthesis_ms\x18\f \x01(\x04R\vsynthesisMs\x12$\n" +
	"\x0egpu_compute_ms\x18\r \x01(\x04R\fgpuComputeMs\x12\x19\n" +
	"\btotal_ms\x18\x0e \x01(\x04R\atotalMs\"L\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\r\n" +
	"\tCOMPLETED\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x02\x12\r\n" +
	"\tCANCELLED\x10\x03\x12\v\n" +
	"\aTIMEOUT\x10\x04\"C\n" +
	"\fProveRequest\x123\n" +
	"\x06submit\x18\x01 \x01(\v2\x1b.cuzk.v1.SubmitProofRequestR\x06submit\"D\n" +
	"\rProveResponse\x123\n" +
	"\x06result\x18\x01 \x01(\v2\x1b.cuzk.v1.AwaitProofResponseR\x06result\"+\n" +
	"\x12CancelProofRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"6\n" +
	"\x13CancelProofResponse\x12\x1f\n" +
	"\vwas_running\x18\x01 \x01(\bR\n" +
	"wasRunning\"\x12\n" +
	"\x10GetStatusRequest\"\x94\x03\n" +
	"\x11GetStatusResponse\x12&\n" +
	"\x04gpus\x18\x01 \x03(\v2\x12.cuzk.v1.GPUStatusR\x04gpus\x121\n" +
	"\n" +
	"loaded_srs\x18\x02 \x03(\v2\x12.cuzk.v1.SRSStatusR\tloadedSrs\x12,\n" +
	"\x06queues\x18\x03 \x03(\v2\x14.cuzk.v1.QueueStatusR\x06queues\x124\n" +
	"\x16total_proofs_completed\x18\x04 \x01(\x04R\x14totalProofsCompleted\x12.\n" +
	"\x13total_proofs_failed\x18\x05 \x01(\x04R\x11totalProofsFailed\x12%\n" +
	"\x0euptime_seconds\x18\x06 \x01(\x04R\ruptimeSeconds\x12.\n" +
	"\x13pinned_memory_bytes\x18\a \x01(\x04R\x11pinnedMemoryBytes\x129\n" +
	"\x19pinned_memory_limit_bytes\x18\b \x01(\x04R\x16pinnedMemoryLimitBytes\"\xdf\x01\n" +
	"\tGPUStatus\x12\x18\n" +
	"\aordinal\x18\x01 \x01(\rR\aordinal\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12(\n" +
	"\x10vram_total_bytes\x18\x03 \x01(\x04R\x0evramTotalBytes\x12&\n" +
	"\x0fvram_free_bytes\x18\x04 \x01(\x04R\rvramFreeBytes\x12$\n" +
	"\x0ecurrent_job_id\x18\x05 \x01(\tR\fcurrentJobId\x12,\n" +
	"\x12current_proof_kind\x18\x06 \x01(\tR\x10currentProofKind\"\xb8\x01\n" +
	"\tSRSStatus\x12\x1d\n" +
	"\n" +
	"circuit_id\x18\x01 \x01(\tR\tcircuitId\x12+\n" +
	"\x04tier\x18\x02 \x01(\x0e2\x17.cuzk.v1.SRSStatus.TierR\x04tier\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04R\tsizeBytes\x12\x1b\n" +
	"\tref_count\x18\x04 \x01(\rR\brefCount\"#\n" +
	"\x04Tier\x12\a\n" +
	"\x03HOT\x10\x00\x12\b\n" +
	"\x04WARM\x10\x01\x12\b\n" +
	"\x04COLD\x10\x02\"g\n" +
	"\vQueueStatus\x12\x1d\n" +
	"\n" +
	"proof_kind\x18\x01 \x01(\tR\tproofKind\x12\x18\n" +
	"\apending\x18\x02 \x01(\rR\apending\x12\x1f\n" +
	"\vin_progress\x18\x03 \x01(\rR\n" +
	"inProgress\"2\n" +
	"\x11PreloadSrsRequest\x12\x1d\n" +
	"\n" +
	"circuit_id\x18\x01 \x01(\tR\tcircuitId\"]\n" +
	"\x12PreloadSrsResponse\x12%\n" +
	"\x0ealready_loaded\x18\x01 \x01(\bR\ralreadyLoaded\x12 \n" +
	"\fload_time_ms\x18\x02 \x01(\x04R\n" +
	"loadTimeMs\"0\n" +
	"\x0fEvictSrsRequest\x12\x1d\n" +
	"\n" +
	"circuit_id\x18\x01 \x01(\tR\tcircuitId\"R\n" +
	"\x10EvictSrsResponse\x12\x1d\n" +
	"\n" +
	"was_loaded\x18\x01 \x01(\bR\twasLoaded\x12\x1f\n" +
	"\vfreed_bytes\x18\x02 \x01(\x04R\n" +
	"freedBytes\"\x13\n" +
	"\x11GetMetricsRequest\"=\n" +
	"\x12GetMetricsResponse\x12'\n" +
	"\x0fprometheus_text\x18\x01 \x01(\tR\x0eprometheusText*\x82\x01\n" +
	"\tProofKind\x12\x1a\n" +
	"\x16PROOF_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11POREP_SEAL_COMMIT\x10\x01\x12\x15\n" +
	"\x11SNAP_DEALS_UPDATE\x10\x02\x12\x19\n" +
	"\x15WINDOW_POST_PARTITION\x10\x03\x12\x10\n" +
	"\fWINNING_POST\x10\x04*Q\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03LOW\x10\x01\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x02\x12\b\n" +
	"\x04HIGH\x10\x03\x12\f\n" +
	"\bCRITICAL\x10\x042\xb5\x04\n" +
	"\rProvingEngine\x12H\n" +
	"\vSubmitProof\x12\x1b.cuzk.v1.SubmitProofRequest\x1a\x1c.cuzk.v1.SubmitProofResponse\x12E\n" +
	"\n" +
	"AwaitProof\x12\x1a.cuzk.v1.AwaitProofRequest\x1a\x1b.cuzk.v1.AwaitProofResponse\x126\n" +
	"\x05Prove\x12\x15.cuzk.v1.ProveRequest\x1a\x16.cuzk.v1.ProveResponse\x12H\n" +
	"\vCancelProof\x12\x1b.cuzk.v1.CancelProofRequest\x1a\x1c.cuzk.v1.CancelProofResponse\x12B\n" +
	"\tGetStatus\x12\x19.cuzk.v1.GetStatusRequest\x1a\x1a.cuzk.v1.GetStatusResponse\x12E\n" +
	"\n" +
	"GetMetrics\x12\x1a.cuzk.v1.GetMetricsRequest\x1a\x1b.cuzk.v1.GetMetricsResponse\x12E\n" +
	"\n" +
	"PreloadSRS\x12\x1a.cuzk.v1.PreloadSrsRequest\x1a\x1b.cuzk.v1.PreloadSrsResponse\x12?\n" +
	"\bEvictSRS\x12\x18.cuzk.v1.EvictSrsRequest\x1a\x19.cuzk.v1.EvictSrsResponseb\x06proto3"

var (
	file_cuzk_v1_proving_proto_rawDescOnce sync.Once
	file_cuzk_v1_proving_proto_rawDescData []byte
)

func file_cuzk_v1_proving_proto_rawDescGZIP() []byte {
	file_cuzk_v1_proving_proto_rawDescOnce.Do(func() {
		file_cuzk_v1_proving_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cuzk_v1_proving_proto_rawDesc), len(file_cuzk_v1_proving_proto_rawDesc)))
	})
	return file_cuzk_v1_proving_proto_rawDescData
}

var file_cuzk_v1_proving_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_cuzk_v1_proving_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_cuzk_v1_proving_proto_goTypes = []any{
	(ProofKind)(0),                 // 0: cuzk.v1.ProofKind
	(Priority)(0),                  // 1: cuzk.v1.Priority
	(AwaitProofResponse_Status)(0), // 2: cuzk.v1.AwaitProofResponse.Status
	(SRSStatus_Tier)(0),            // 3: cuzk.v1.SRSStatus.Tier
	(*SubmitProofRequest)(nil),     // 4: cuzk.v1.SubmitProofRequest
	(*SubmitProofResponse)(nil),    // 5: cuzk.v1.SubmitProofResponse
	(*AwaitProofRequest)(nil),      // 6: cuzk.v1.AwaitProofRequest
	(*AwaitProofResponse)(nil),     // 7: cuzk.v1.AwaitProofResponse
	(*ProveRequest)(nil),           // 8: cuzk.v1.ProveRequest
	(*ProveResponse)(nil),          // 9: cuzk.v1.ProveResponse
	(*CancelProofRequest)(nil),     // 10: cuzk.v1.CancelProofRequest
	(*CancelProofResponse)(nil),    // 11: cuzk.v1.CancelProofResponse
	(*GetStatusRequest)(nil),       // 12: cuzk.v1.GetStatusRequest
	(*GetStatusResponse)(nil),      // 13: cuzk.v1.GetStatusResponse
	(*GPUStatus)(nil),              // 14: cuzk.v1.GPUStatus
	(*SRSStatus)(nil),              // 15: cuzk.v1.SRSStatus
	(*QueueStatus)(nil),            // 16: cuzk.v1.QueueStatus
	(*PreloadSrsRequest)(nil),      // 17: cuzk.v1.PreloadSrsRequest
	(*PreloadSrsResponse)(nil),     // 18: cuzk.v1.PreloadSrsResponse
	(*EvictSrsRequest)(nil),        // 19: cuzk.v1.EvictSrsRequest
	(*EvictSrsResponse)(nil),       // 20: cuzk.v1.EvictSrsResponse
	(*GetMetricsRequest)(nil),      // 21: cuzk.v1.GetMetricsRequest
	(*GetMetricsResponse)(nil),     // 22: cuzk.v1.GetMetricsResponse
}
var file_cuzk_v1_proving_proto_depIdxs = []int32{
	0,  // 0: cuzk.v1.SubmitProofRequest.proof_kind:type_name -> cuzk.v1.ProofKind
	1,  // 1: cuzk.v1.SubmitProofRequest.priority:type_name -> cuzk.v1.Priority
	2,  // 2: cuzk.v1.AwaitProofResponse.status:type_name -> cuzk.v1.AwaitProofResponse.Status
	4,  // 3: cuzk.v1.ProveRequest.submit:type_name -> cuzk.v1.SubmitProofRequest
	7,  // 4: cuzk.v1.ProveResponse.result:type_name -> cuzk.v1.AwaitProofResponse
	14, // 5: cuzk.v1.GetStatusResponse.gpus:type_name -> cuzk.v1.GPUStatus
	15, // 6: cuzk.v1.GetStatusResponse.loaded_srs:type_name -> cuzk.v1.SRSStatus
	16, // 7: cuzk.v1.GetStatusResponse.queues:type_name -> cuzk.v1.QueueStatus
	3,  // 8: cuzk.v1.SRSStatus.tier:type_name -> cuzk.v1.SRSStatus.Tier
	4,  // 9: cuzk.v1.ProvingEngine.SubmitProof:input_type -> cuzk.v1.SubmitProofRequest
	6,  // 10: cuzk.v1.ProvingEngine.AwaitProof:input_type -> cuzk.v1.AwaitProofRequest
	8,  // 11: cuzk.v1.ProvingEngine.Prove:input_type -> cuzk.v1.ProveRequest
	10, // 12: cuzk.v1.ProvingEngine.CancelProof:input_type -> cuzk.v1.CancelProofRequest
	12, // 13: cuzk.v1.ProvingEngine.GetStatus:input_type -> cuzk.v1.GetStatusRequest
	21, // 14: cuzk.v1.ProvingEngine.GetMetrics:input_type -> cuzk.v1.GetMetricsRequest
	17, // 15: cuzk.v1.ProvingEngine.PreloadSRS:input_type -> cuzk.v1.PreloadSrsRequest
	19, // 16: cuzk.v1.ProvingEngine.EvictSRS:input_type -> cuzk.v1.EvictSrsRequest
	5,  // 17: cuzk.v1.ProvingEngine.SubmitProof:output_type -> cuzk.v1.SubmitProofResponse
	7,  // 18: cuzk.v1.ProvingEngine.AwaitProof:output_type -> cuzk.v1.AwaitProofResponse
	9,  // 19: cuzk.v1.ProvingEngine.Prove:output_type -> cuzk.v1.ProveResponse
	11, // 20: cuzk.v1.ProvingEngine.CancelProof:output_type -> cuzk.v1.CancelProofResponse
	13, // 21: cuzk.v1.ProvingEngine.GetStatus:output_type -> cuzk.v1.GetStatusResponse
	22, // 22: cuzk.v1.ProvingEngine.GetMetrics:output_type -> cuzk.v1.GetMetricsResponse
	18, // 23: cuzk.v1.ProvingEngine.PreloadSRS:output_type -> cuzk.v1.PreloadSrsResponse
	20, // 24: cuzk.v1.ProvingEngine.EvictSRS:output_type -> cuzk.v1.EvictSrsResponse
	17, // [17:25] is the sub-list for method output_type
	9,  // [9:17] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_cuzk_v1_proving_proto_init() }
func file_cuzk_v1_proving_proto_init() {
	if File_cuzk_v1_proving_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cuzk_v1_proving_proto_rawDesc), len(file_cuzk_v1_proving_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cuzk_v1_proving_proto_goTypes,
		DependencyIndexes: file_cuzk_v1_proving_proto_depIdxs,
		EnumInfos:         file_cuzk_v1_proving_proto_enumTypes,
		MessageInfos:      file_cuzk_v1_proving_proto_msgTypes,
	}.Build()
	File_cuzk_v1_proving_proto = out.File
	file_cuzk_v1_proving_proto_goTypes = nil
	file_cuzk_v1_proving_proto_depIdxs = nil
}
