name: Self-hosted runners example

on:
  push:

jobs:
  greet:
    # The type of runner that the job will run on
    runs-on: ["self-hosted", "linux", "x64", "4xlarge"]

    services:
      yugabyte:
        image: yugabytedb/yugabyte:latest
        command: bin/yugabyted start --background=false
        ports:
          - 7000:7000
          - 9000:9000
          - 15433:15433
          - 5433:5433
          - 9042:9042 

    steps:
    - run: docker ps
